/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* top =  1  *)
(* src = "src/fpu_FADDSUB.sv:3.1-215.10" *)
module addsub(a, b, clk, sub, nanA, nanB, infinA, infinB, A0, B0, ans);
  (* src = "src/fpu_FADDSUB.sv:4.24-4.25" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "src/fpu_FADDSUB.sv:4.26-4.27" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "src/fpu_FADDSUB.sv:5.17-5.20" *)
  input clk;
  wire clk;
  (* src = "src/fpu_FADDSUB.sv:6.17-6.20" *)
  input sub;
  wire sub;
  (* src = "src/fpu_FADDSUB.sv:7.17-7.21" *)
  input nanA;
  wire nanA;
  (* src = "src/fpu_FADDSUB.sv:7.23-7.27" *)
  input nanB;
  wire nanB;
  (* src = "src/fpu_FADDSUB.sv:7.29-7.35" *)
  input infinA;
  wire infinA;
  (* src = "src/fpu_FADDSUB.sv:7.37-7.43" *)
  input infinB;
  wire infinB;
  (* src = "src/fpu_FADDSUB.sv:7.45-7.47" *)
  input A0;
  wire A0;
  (* src = "src/fpu_FADDSUB.sv:7.49-7.51" *)
  input B0;
  wire B0;
  (* src = "src/fpu_FADDSUB.sv:8.25-8.28" *)
  output [15:0] ans;
  wire [15:0] ans;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  (* src = "src/fpu_FADDSUB.sv:63.17-63.27" *)
  wire [14:0] addsub_man;
  (* src = "src/fpu_FADDSUB.sv:60.17-60.32" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [14:0] addsub_man_norm;
  (* src = "src/fpu_FADDSUB.sv:57.17-57.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13" *)
  wire [13:0] alu_bigger;
  (* src = "src/fpu_FADDSUB.sv:58.17-58.28" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13" *)
  wire [13:0] alu_smaller;
  (* src = "src/fpu_FADDSUB.sv:180.17-180.31" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [15:0] ans_calculated;
  (* src = "src/fpu_FADDSUB.sv:181.18-181.31" *)
  wire [15:0] ans_corrected;
  (* src = "src/fpu_FADDSUB.sv:27.16-27.30" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] corrected_expA;
  (* src = "src/fpu_FADDSUB.sv:28.16-28.30" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] corrected_expB;
  (* src = "src/fpu_FADDSUB.sv:53.16-53.25" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] final_exp;
  wire [4:0] init_expA;
  wire [4:0] init_expB;
  (* src = "src/fpu_FADDSUB.sv:24.17-24.26" *)
  (* unused_bits = "21" *)
  wire [21:0] init_manA;
  (* src = "src/fpu_FADDSUB.sv:25.17-25.26" *)
  (* unused_bits = "21" *)
  wire [21:0] init_manB;
  (* src = "src/fpu_FADDSUB.sv:34.17-34.27" *)
  (* unused_bits = "11 12 13 14 15 16 17 18 19 20 21" *)
  wire [21:0] man_bigger;
  (* src = "src/fpu_FADDSUB.sv:68.18-68.28" *)
  (* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21" *)
  wire [21:0] man_fixing;
  (* src = "src/fpu_FADDSUB.sv:36.17-36.28" *)
  (* unused_bits = "11 12 13 14 15 16 17 18 19 20 21" *)
  wire [21:0] man_smaller;
  (* src = "src/fpu_FADDSUB.sv:67.16-67.28" *)
  wire [21:0] pre_norm_man;
  (* src = "src/fpu_FADDSUB.sv:17.10-17.15" *)
  wire signA;
  (* src = "src/fpu_FADDSUB.sv:188.9-188.18" *)
  wire signA_reg;
  (* src = "src/fpu_FADDSUB.sv:18.10-18.15" *)
  wire signB;
  (* src = "src/fpu_FADDSUB.sv:188.20-188.29" *)
  wire signB_reg;
  (* src = "src/fpu_FADDSUB.sv:71.9-71.17" *)
  wire sign_reg;
  sky130_fd_sc_hd__clkinv_1 _0648_ (
    .A(a[11]),
    .Y(_0639_)
  );
  sky130_fd_sc_hd__clkinv_1 _0649_ (
    .A(pre_norm_man[15]),
    .Y(_0640_)
  );
  sky130_fd_sc_hd__nand2_1 _0650_ (
    .A(b[11]),
    .B(b[10]),
    .Y(_0641_)
  );
  sky130_fd_sc_hd__nor3_1 _0651_ (
    .A(b[12]),
    .B(b[13]),
    .C(b[14]),
    .Y(_0642_)
  );
  sky130_fd_sc_hd__or3_1 _0652_ (
    .A(b[11]),
    .B(b[10]),
    .C(_0642_),
    .X(_0643_)
  );
  sky130_fd_sc_hd__and2_0 _0653_ (
    .A(_0641_),
    .B(_0643_),
    .X(_0644_)
  );
  sky130_fd_sc_hd__nand2_1 _0654_ (
    .A(a[11]),
    .B(a[10]),
    .Y(_0645_)
  );
  sky130_fd_sc_hd__nor3_1 _0655_ (
    .A(a[12]),
    .B(a[13]),
    .C(a[14]),
    .Y(_0646_)
  );
  sky130_fd_sc_hd__or3_1 _0656_ (
    .A(a[11]),
    .B(a[10]),
    .C(_0646_),
    .X(_0647_)
  );
  sky130_fd_sc_hd__nand2_1 _0657_ (
    .A(_0645_),
    .B(_0647_),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__xnor2_1 _0658_ (
    .A(_0644_),
    .B(_0001_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__nor3b_1 _0659_ (
    .A(a[11]),
    .B(a[10]),
    .C_N(_0646_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__a21oi_1 _0660_ (
    .A1(_0639_),
    .A2(_0646_),
    .B1(a[10]),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__nor3b_1 _0661_ (
    .A(b[11]),
    .B(b[10]),
    .C_N(_0642_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__nor2_1 _0662_ (
    .A(b[10]),
    .B(_0005_),
    .Y(_0006_)
  );
  sky130_fd_sc_hd__nor3_1 _0663_ (
    .A(a[10]),
    .B(_0003_),
    .C(_0006_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__nor3_1 _0664_ (
    .A(b[10]),
    .B(_0004_),
    .C(_0005_),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__nor2_1 _0665_ (
    .A(_0007_),
    .B(_0008_),
    .Y(_0009_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0666_ (
    .A(_0007_),
    .SLEEP(_0008_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0667_ (
    .A(_0002_),
    .SLEEP(_0010_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__nand3_1 _0668_ (
    .A(a[11]),
    .B(a[10]),
    .C(a[12]),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0669_ (
    .A(a[13]),
    .SLEEP(_0012_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__xor2_1 _0670_ (
    .A(a[13]),
    .B(_0012_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__nand3_1 _0671_ (
    .A(b[11]),
    .B(b[10]),
    .C(b[12]),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0672_ (
    .A(b[13]),
    .SLEEP(_0015_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__xor2_1 _0673_ (
    .A(b[13]),
    .B(_0015_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__clkinv_1 _0674_ (
    .A(_0017_),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__xor2_1 _0675_ (
    .A(_0014_),
    .B(_0017_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__xor2_1 _0676_ (
    .A(a[12]),
    .B(_0645_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__xor2_1 _0677_ (
    .A(b[12]),
    .B(_0641_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__clkinv_1 _0678_ (
    .A(_0021_),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__maj3_1 _0679_ (
    .A(_0644_),
    .B(_0001_),
    .C(_0008_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__xnor2_1 _0680_ (
    .A(_0020_),
    .B(_0021_),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__maj3_1 _0681_ (
    .A(_0020_),
    .B(_0022_),
    .C(_0023_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__xnor2_1 _0682_ (
    .A(_0019_),
    .B(_0025_),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0683_ (
    .A(b[14]),
    .SLEEP(_0016_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__nor2_1 _0684_ (
    .A(a[14]),
    .B(_0013_),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0685_ (
    .A(a[14]),
    .SLEEP(_0013_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__nand2_1 _0686_ (
    .A(_0027_),
    .B(_0028_),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__maj3_1 _0687_ (
    .A(_0014_),
    .B(_0018_),
    .C(_0025_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__nand2_1 _0688_ (
    .A(b[14]),
    .B(_0016_),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__nand2_1 _0689_ (
    .A(_0027_),
    .B(_0032_),
    .Y(_0033_)
  );
  sky130_fd_sc_hd__nand2_1 _0690_ (
    .A(a[14]),
    .B(_0013_),
    .Y(_0034_)
  );
  sky130_fd_sc_hd__nand2_1 _0691_ (
    .A(_0029_),
    .B(_0034_),
    .Y(_0035_)
  );
  sky130_fd_sc_hd__xor2_1 _0692_ (
    .A(_0033_),
    .B(_0035_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__o21ai_0 _0693_ (
    .A1(_0027_),
    .A2(_0028_),
    .B1(_0034_),
    .Y(_0037_)
  );
  sky130_fd_sc_hd__nand2_1 _0694_ (
    .A(_0032_),
    .B(_0037_),
    .Y(_0038_)
  );
  sky130_fd_sc_hd__o21ai_0 _0695_ (
    .A1(_0031_),
    .A2(_0036_),
    .B1(_0038_),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__and2_0 _0696_ (
    .A(_0030_),
    .B(_0039_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__nand2_1 _0697_ (
    .A(_0030_),
    .B(_0039_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__a21boi_0 _0698_ (
    .A1(_0030_),
    .A2(_0039_),
    .B1_N(_0011_),
    .Y(_0042_)
  );
  sky130_fd_sc_hd__xnor2_1 _0699_ (
    .A(_0023_),
    .B(_0024_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__nor2_1 _0700_ (
    .A(_0011_),
    .B(_0043_),
    .Y(_0044_)
  );
  sky130_fd_sc_hd__nor2_1 _0701_ (
    .A(_0040_),
    .B(_0044_),
    .Y(_0045_)
  );
  sky130_fd_sc_hd__xnor2_1 _0702_ (
    .A(_0026_),
    .B(_0045_),
    .Y(_0046_)
  );
  sky130_fd_sc_hd__xnor2_1 _0703_ (
    .A(_0042_),
    .B(_0043_),
    .Y(_0047_)
  );
  sky130_fd_sc_hd__xor2_1 _0704_ (
    .A(_0042_),
    .B(_0043_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__nand2_1 _0705_ (
    .A(_0046_),
    .B(_0048_),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__nand3_1 _0706_ (
    .A(_0011_),
    .B(_0046_),
    .C(_0048_),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__xor2_1 _0707_ (
    .A(_0002_),
    .B(_0008_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__nand2_1 _0708_ (
    .A(_0010_),
    .B(_0051_),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__a22oi_1 _0709_ (
    .A1(_0040_),
    .A2(_0051_),
    .B1(_0052_),
    .B2(_0042_),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__a21o_1 _0710_ (
    .A1(_0010_),
    .A2(_0053_),
    .B1(_0050_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__mux2i_1 _0711_ (
    .A0(b[7]),
    .A1(a[7]),
    .S(_0041_),
    .Y(_0055_)
  );
  sky130_fd_sc_hd__nand2_1 _0712_ (
    .A(b[8]),
    .B(_0040_),
    .Y(_0056_)
  );
  sky130_fd_sc_hd__nand2_1 _0713_ (
    .A(a[8]),
    .B(_0041_),
    .Y(_0057_)
  );
  sky130_fd_sc_hd__mux2i_1 _0714_ (
    .A0(b[8]),
    .A1(a[8]),
    .S(_0041_),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__mux2i_1 _0715_ (
    .A0(_0055_),
    .A1(_0058_),
    .S(_0010_),
    .Y(_0059_)
  );
  sky130_fd_sc_hd__mux2i_1 _0716_ (
    .A0(b[9]),
    .A1(a[9]),
    .S(_0041_),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__a21oi_1 _0717_ (
    .A1(_0003_),
    .A2(_0041_),
    .B1(_0005_),
    .Y(_0061_)
  );
  sky130_fd_sc_hd__a21o_1 _0718_ (
    .A1(_0003_),
    .A2(_0041_),
    .B1(_0005_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__mux2i_1 _0719_ (
    .A0(_0060_),
    .A1(_0062_),
    .S(_0010_),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__mux2i_1 _0720_ (
    .A0(_0063_),
    .A1(_0059_),
    .S(_0053_),
    .Y(_0064_)
  );
  sky130_fd_sc_hd__mux2i_1 _0721_ (
    .A0(b[3]),
    .A1(a[3]),
    .S(_0041_),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__mux2i_1 _0722_ (
    .A0(b[4]),
    .A1(a[4]),
    .S(_0041_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__mux2i_1 _0723_ (
    .A0(_0065_),
    .A1(_0066_),
    .S(_0010_),
    .Y(_0067_)
  );
  sky130_fd_sc_hd__mux2i_1 _0724_ (
    .A0(b[5]),
    .A1(a[5]),
    .S(_0041_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__mux2i_1 _0725_ (
    .A0(b[6]),
    .A1(a[6]),
    .S(_0041_),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__mux2i_1 _0726_ (
    .A0(_0068_),
    .A1(_0069_),
    .S(_0010_),
    .Y(_0070_)
  );
  sky130_fd_sc_hd__mux2i_1 _0727_ (
    .A0(_0070_),
    .A1(_0067_),
    .S(_0053_),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__mux2i_1 _0728_ (
    .A0(_0064_),
    .A1(_0071_),
    .S(_0047_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__mux4_2 _0729_ (
    .A0(b[8]),
    .A1(a[8]),
    .A2(b[9]),
    .A3(a[9]),
    .S0(_0041_),
    .S1(_0010_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__nand2_1 _0730_ (
    .A(_0053_),
    .B(_0073_),
    .Y(_0074_)
  );
  sky130_fd_sc_hd__o31ai_1 _0731_ (
    .A1(_0010_),
    .A2(_0053_),
    .A3(_0062_),
    .B1(_0074_),
    .Y(_0075_)
  );
  sky130_fd_sc_hd__mux4_2 _0732_ (
    .A0(b[4]),
    .A1(a[4]),
    .A2(b[5]),
    .A3(a[5]),
    .S0(_0041_),
    .S1(_0010_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__mux4_2 _0733_ (
    .A0(b[6]),
    .A1(a[6]),
    .A2(b[7]),
    .A3(a[7]),
    .S0(_0041_),
    .S1(_0010_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__mux2i_1 _0734_ (
    .A0(_0077_),
    .A1(_0076_),
    .S(_0053_),
    .Y(_0078_)
  );
  sky130_fd_sc_hd__nor2_1 _0735_ (
    .A(_0048_),
    .B(_0078_),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__a21o_1 _0736_ (
    .A1(_0048_),
    .A2(_0075_),
    .B1(_0079_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__mux2i_1 _0737_ (
    .A0(_0073_),
    .A1(_0077_),
    .S(_0053_),
    .Y(_0081_)
  );
  sky130_fd_sc_hd__mux2i_1 _0738_ (
    .A0(b[2]),
    .A1(a[2]),
    .S(_0041_),
    .Y(_0082_)
  );
  sky130_fd_sc_hd__mux2i_1 _0739_ (
    .A0(_0065_),
    .A1(_0082_),
    .S(_0009_),
    .Y(_0083_)
  );
  sky130_fd_sc_hd__mux2i_1 _0740_ (
    .A0(_0076_),
    .A1(_0083_),
    .S(_0053_),
    .Y(_0084_)
  );
  sky130_fd_sc_hd__mux2i_1 _0741_ (
    .A0(_0081_),
    .A1(_0084_),
    .S(_0047_),
    .Y(_0085_)
  );
  sky130_fd_sc_hd__mux2i_1 _0742_ (
    .A0(_0059_),
    .A1(_0070_),
    .S(_0053_),
    .Y(_0086_)
  );
  sky130_fd_sc_hd__mux2i_1 _0743_ (
    .A0(b[1]),
    .A1(a[1]),
    .S(_0041_),
    .Y(_0087_)
  );
  sky130_fd_sc_hd__mux2i_1 _0744_ (
    .A0(_0082_),
    .A1(_0087_),
    .S(_0009_),
    .Y(_0088_)
  );
  sky130_fd_sc_hd__mux2i_1 _0745_ (
    .A0(_0067_),
    .A1(_0088_),
    .S(_0053_),
    .Y(_0089_)
  );
  sky130_fd_sc_hd__mux2i_1 _0746_ (
    .A0(_0086_),
    .A1(_0089_),
    .S(_0047_),
    .Y(_0090_)
  );
  sky130_fd_sc_hd__o41a_1 _0747_ (
    .A1(_0072_),
    .A2(_0080_),
    .A3(_0085_),
    .A4(_0090_),
    .B1(_0054_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__and2_0 _0748_ (
    .A(_0053_),
    .B(_0063_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__nand2_1 _0749_ (
    .A(_0048_),
    .B(_0092_),
    .Y(_0093_)
  );
  sky130_fd_sc_hd__o21ai_0 _0750_ (
    .A1(_0048_),
    .A2(_0086_),
    .B1(_0093_),
    .Y(_0094_)
  );
  sky130_fd_sc_hd__xor2_1 _0751_ (
    .A(_0031_),
    .B(_0036_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__a21oi_1 _0752_ (
    .A1(_0026_),
    .A2(_0044_),
    .B1(_0040_),
    .Y(_0096_)
  );
  sky130_fd_sc_hd__xnor2_1 _0753_ (
    .A(_0095_),
    .B(_0096_),
    .Y(_0097_)
  );
  sky130_fd_sc_hd__and2_0 _0754_ (
    .A(_0046_),
    .B(_0097_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__o21ai_0 _0755_ (
    .A1(_0091_),
    .A2(_0094_),
    .B1(_0098_),
    .Y(_0099_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0756_ (
    .A(_0097_),
    .SLEEP(_0046_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__nand2_1 _0757_ (
    .A(b[0]),
    .B(_0040_),
    .Y(_0101_)
  );
  sky130_fd_sc_hd__nand2_1 _0758_ (
    .A(a[0]),
    .B(_0041_),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__mux2i_1 _0759_ (
    .A0(b[0]),
    .A1(a[0]),
    .S(_0041_),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__nand2_1 _0760_ (
    .A(_0101_),
    .B(_0102_),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__nor2_1 _0761_ (
    .A(_0048_),
    .B(_0053_),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__nand3_1 _0762_ (
    .A(_0010_),
    .B(_0104_),
    .C(_0105_),
    .Y(_0106_)
  );
  sky130_fd_sc_hd__o21ai_0 _0763_ (
    .A1(_0047_),
    .A2(_0089_),
    .B1(_0106_),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__nand2b_1 _0764_ (
    .A_N(_0053_),
    .B(_0083_),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__nand2b_1 _0765_ (
    .A_N(_0053_),
    .B(_0088_),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__mux2i_1 _0766_ (
    .A0(_0087_),
    .A1(_0103_),
    .S(_0009_),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__a21oi_1 _0767_ (
    .A1(_0010_),
    .A2(_0104_),
    .B1(_0110_),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__nand3_1 _0768_ (
    .A(_0108_),
    .B(_0109_),
    .C(_0111_),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__and3_1 _0769_ (
    .A(_0048_),
    .B(_0054_),
    .C(_0112_),
    .X(_0113_)
  );
  sky130_fd_sc_hd__o21ai_0 _0770_ (
    .A1(_0107_),
    .A2(_0113_),
    .B1(_0100_),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__a31oi_1 _0771_ (
    .A1(_0010_),
    .A2(_0053_),
    .A3(_0104_),
    .B1(_0048_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__a22oi_1 _0772_ (
    .A1(_0048_),
    .A2(_0071_),
    .B1(_0109_),
    .B2(_0115_),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__nand2_1 _0773_ (
    .A(_0105_),
    .B(_0110_),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__o21ai_0 _0774_ (
    .A1(_0047_),
    .A2(_0084_),
    .B1(_0117_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__nand2_1 _0775_ (
    .A(_0053_),
    .B(_0110_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__and2_0 _0776_ (
    .A(_0048_),
    .B(_0078_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__a31oi_1 _0777_ (
    .A1(_0047_),
    .A2(_0108_),
    .A3(_0119_),
    .B1(_0120_),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__nand2_1 _0778_ (
    .A(_0054_),
    .B(_0097_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__and4_1 _0779_ (
    .A(_0065_),
    .B(_0066_),
    .C(_0068_),
    .D(_0082_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__o41ai_1 _0780_ (
    .A1(_0107_),
    .A2(_0116_),
    .A3(_0118_),
    .A4(_0121_),
    .B1(_0046_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__a21o_1 _0781_ (
    .A1(_0122_),
    .A2(_0123_),
    .B1(_0124_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__and4_1 _0782_ (
    .A(_0056_),
    .B(_0057_),
    .C(_0060_),
    .D(_0062_),
    .X(_0126_)
  );
  sky130_fd_sc_hd__nand4_1 _0783_ (
    .A(_0055_),
    .B(_0069_),
    .C(_0123_),
    .D(_0126_),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__nand2_1 _0784_ (
    .A(_0049_),
    .B(_0097_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__a21oi_1 _0785_ (
    .A1(_0050_),
    .A2(_0097_),
    .B1(_0087_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__a221oi_1 _0786_ (
    .A1(_0122_),
    .A2(_0127_),
    .B1(_0128_),
    .B2(_0104_),
    .C1(_0129_),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__and4_1 _0787_ (
    .A(_0099_),
    .B(_0114_),
    .C(_0125_),
    .D(_0130_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__clkinv_1 _0788_ (
    .A(_0131_),
    .Y(addsub_man[0])
  );
  sky130_fd_sc_hd__nand2_1 _0789_ (
    .A(A0),
    .B(B0),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__nor4_1 _0790_ (
    .A(nanA),
    .B(nanB),
    .C(infinA),
    .D(infinB),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__nor2b_1 _0791_ (
    .A(_0132_),
    .B_N(_0133_),
    .Y(_0134_)
  );
  sky130_fd_sc_hd__nor3_1 _0792_ (
    .A(pre_norm_man[21]),
    .B(pre_norm_man[20]),
    .C(pre_norm_man[19]),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__nor4_1 _0793_ (
    .A(pre_norm_man[21]),
    .B(pre_norm_man[20]),
    .C(pre_norm_man[19]),
    .D(pre_norm_man[18]),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__nand2_1 _0794_ (
    .A(pre_norm_man[17]),
    .B(_0135_),
    .Y(_0137_)
  );
  sky130_fd_sc_hd__nor2_1 _0795_ (
    .A(pre_norm_man[18]),
    .B(_0137_),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__nor3b_1 _0796_ (
    .A(pre_norm_man[21]),
    .B(pre_norm_man[20]),
    .C_N(pre_norm_man[19]),
    .Y(_0139_)
  );
  sky130_fd_sc_hd__nor2_1 _0797_ (
    .A(_0138_),
    .B(_0139_),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__nor2_1 _0798_ (
    .A(pre_norm_man[13]),
    .B(pre_norm_man[12]),
    .Y(_0141_)
  );
  sky130_fd_sc_hd__nor2_1 _0799_ (
    .A(pre_norm_man[14]),
    .B(pre_norm_man[15]),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__or4_1 _0800_ (
    .A(pre_norm_man[14]),
    .B(pre_norm_man[15]),
    .C(pre_norm_man[13]),
    .D(pre_norm_man[12]),
    .X(_0143_)
  );
  sky130_fd_sc_hd__nor3b_1 _0801_ (
    .A(pre_norm_man[17]),
    .B(pre_norm_man[16]),
    .C_N(_0136_),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__nand2_1 _0802_ (
    .A(pre_norm_man[11]),
    .B(_0144_),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__nor2_1 _0803_ (
    .A(_0143_),
    .B(_0145_),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__nor2_1 _0804_ (
    .A(pre_norm_man[11]),
    .B(_0143_),
    .Y(_0147_)
  );
  sky130_fd_sc_hd__and2_0 _0805_ (
    .A(pre_norm_man[9]),
    .B(_0144_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__nand3_1 _0806_ (
    .A(pre_norm_man[9]),
    .B(_0144_),
    .C(_0147_),
    .Y(_0149_)
  );
  sky130_fd_sc_hd__nor2_1 _0807_ (
    .A(pre_norm_man[10]),
    .B(_0149_),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__nor4_1 _0808_ (
    .A(_0138_),
    .B(_0139_),
    .C(_0146_),
    .D(_0150_),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__and3_1 _0809_ (
    .A(pre_norm_man[13]),
    .B(_0142_),
    .C(_0144_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__a21oi_1 _0810_ (
    .A1(pre_norm_man[15]),
    .A2(_0144_),
    .B1(_0152_),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__nor3_1 _0811_ (
    .A(pre_norm_man[14]),
    .B(pre_norm_man[11]),
    .C(pre_norm_man[8]),
    .Y(_0154_)
  );
  sky130_fd_sc_hd__nor2_1 _0812_ (
    .A(pre_norm_man[10]),
    .B(pre_norm_man[9]),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__nand3_1 _0813_ (
    .A(_0141_),
    .B(_0154_),
    .C(_0155_),
    .Y(_0156_)
  );
  sky130_fd_sc_hd__and2_0 _0814_ (
    .A(_0640_),
    .B(_0144_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__nand2_1 _0815_ (
    .A(_0640_),
    .B(_0144_),
    .Y(_0158_)
  );
  sky130_fd_sc_hd__nand2_1 _0816_ (
    .A(pre_norm_man[7]),
    .B(_0157_),
    .Y(_0159_)
  );
  sky130_fd_sc_hd__o211a_1 _0817_ (
    .A1(_0156_),
    .A2(_0159_),
    .B1(_0151_),
    .C1(_0153_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0818_ (
    .A(_0160_),
    .SLEEP(pre_norm_man[21]),
    .X(_0161_)
  );
  sky130_fd_sc_hd__nand2b_1 _0819_ (
    .A_N(pre_norm_man[21]),
    .B(_0160_),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__a21oi_1 _0820_ (
    .A1(_0030_),
    .A2(_0039_),
    .B1(_0018_),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__a21oi_1 _0821_ (
    .A1(_0014_),
    .A2(_0040_),
    .B1(_0163_),
    .Y(_0164_)
  );
  sky130_fd_sc_hd__a21o_1 _0822_ (
    .A1(_0014_),
    .A2(_0040_),
    .B1(_0163_),
    .X(_0165_)
  );
  sky130_fd_sc_hd__nand2_1 _0823_ (
    .A(_0140_),
    .B(_0153_),
    .Y(_0166_)
  );
  sky130_fd_sc_hd__nand2_1 _0824_ (
    .A(_0164_),
    .B(_0166_),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__a21oi_1 _0825_ (
    .A1(_0030_),
    .A2(_0039_),
    .B1(_0022_),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__a21oi_1 _0826_ (
    .A1(_0020_),
    .A2(_0040_),
    .B1(_0168_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__nand2b_1 _0827_ (
    .A_N(_0151_),
    .B(_0169_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__nand3_1 _0828_ (
    .A(_0001_),
    .B(_0030_),
    .C(_0039_),
    .Y(_0171_)
  );
  sky130_fd_sc_hd__o21ai_0 _0829_ (
    .A1(_0644_),
    .A2(_0040_),
    .B1(_0171_),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__o21a_1 _0830_ (
    .A1(_0644_),
    .A2(_0040_),
    .B1(_0171_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__or4_1 _0831_ (
    .A(_0138_),
    .B(_0150_),
    .C(_0152_),
    .D(_0160_),
    .X(_0174_)
  );
  sky130_fd_sc_hd__mux2i_1 _0832_ (
    .A0(_0004_),
    .A1(_0006_),
    .S(_0041_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__maj3_1 _0833_ (
    .A(_0172_),
    .B(_0174_),
    .C(_0175_),
    .X(_0176_)
  );
  sky130_fd_sc_hd__xor2_1 _0834_ (
    .A(_0151_),
    .B(_0169_),
    .X(_0177_)
  );
  sky130_fd_sc_hd__o21a_1 _0835_ (
    .A1(_0176_),
    .A2(_0177_),
    .B1(_0170_),
    .X(_0178_)
  );
  sky130_fd_sc_hd__xnor2_1 _0836_ (
    .A(_0164_),
    .B(_0166_),
    .Y(_0179_)
  );
  sky130_fd_sc_hd__o21a_1 _0837_ (
    .A1(_0178_),
    .A2(_0179_),
    .B1(_0167_),
    .X(_0180_)
  );
  sky130_fd_sc_hd__nor2_1 _0838_ (
    .A(_0035_),
    .B(_0041_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__a31oi_1 _0839_ (
    .A1(_0027_),
    .A2(_0032_),
    .A3(_0041_),
    .B1(_0181_),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__o21bai_1 _0840_ (
    .A1(_0033_),
    .A2(_0040_),
    .B1_N(_0181_),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__nor2_1 _0841_ (
    .A(_0160_),
    .B(_0182_),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0842_ (
    .A(_0027_),
    .SLEEP(_0029_),
    .X(_0185_)
  );
  sky130_fd_sc_hd__and2_0 _0843_ (
    .A(_0160_),
    .B(_0182_),
    .X(_0186_)
  );
  sky130_fd_sc_hd__nor2_1 _0844_ (
    .A(_0185_),
    .B(_0186_),
    .Y(_0187_)
  );
  sky130_fd_sc_hd__nor2_1 _0845_ (
    .A(_0161_),
    .B(_0185_),
    .Y(_0188_)
  );
  sky130_fd_sc_hd__o22ai_1 _0846_ (
    .A1(_0180_),
    .A2(_0187_),
    .B1(_0188_),
    .B2(_0184_),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__nor3_1 _0847_ (
    .A(pre_norm_man[7]),
    .B(_0156_),
    .C(_0158_),
    .Y(_0190_)
  );
  sky130_fd_sc_hd__or3_1 _0848_ (
    .A(pre_norm_man[7]),
    .B(_0156_),
    .C(_0158_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__nand3b_1 _0849_ (
    .A_N(pre_norm_man[13]),
    .B(pre_norm_man[12]),
    .C(_0142_),
    .Y(_0192_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0850_ (
    .A(_0144_),
    .SLEEP(_0192_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__nand2_1 _0851_ (
    .A(_0165_),
    .B(_0193_),
    .Y(_0194_)
  );
  sky130_fd_sc_hd__o21ai_0 _0852_ (
    .A1(_0182_),
    .A2(_0194_),
    .B1(_0191_),
    .Y(_0195_)
  );
  sky130_fd_sc_hd__nand2_1 _0853_ (
    .A(pre_norm_man[10]),
    .B(_0144_),
    .Y(_0196_)
  );
  sky130_fd_sc_hd__nor3_1 _0854_ (
    .A(pre_norm_man[11]),
    .B(_0143_),
    .C(_0196_),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__nor2_1 _0855_ (
    .A(_0165_),
    .B(_0197_),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__and3_1 _0856_ (
    .A(pre_norm_man[14]),
    .B(_0640_),
    .C(_0144_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__nand2_1 _0857_ (
    .A(pre_norm_man[14]),
    .B(_0157_),
    .Y(_0200_)
  );
  sky130_fd_sc_hd__maj3_1 _0858_ (
    .A(_0169_),
    .B(_0173_),
    .C(_0200_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__xnor2_1 _0859_ (
    .A(_0164_),
    .B(_0197_),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__a21oi_1 _0860_ (
    .A1(_0201_),
    .A2(_0202_),
    .B1(_0198_),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__and2_0 _0861_ (
    .A(pre_norm_man[18]),
    .B(_0135_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__nor3_1 _0862_ (
    .A(_0197_),
    .B(_0199_),
    .C(_0204_),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__or3_1 _0863_ (
    .A(_0197_),
    .B(_0199_),
    .C(_0204_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__a21oi_1 _0864_ (
    .A1(_0201_),
    .A2(_0202_),
    .B1(_0205_),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__a31oi_1 _0865_ (
    .A1(_0183_),
    .A2(_0203_),
    .A3(_0206_),
    .B1(_0195_),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__and3b_1 _0866_ (
    .A_N(pre_norm_man[17]),
    .B(pre_norm_man[16]),
    .C(_0136_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__nand3_1 _0867_ (
    .A(pre_norm_man[8]),
    .B(_0136_),
    .C(_0155_),
    .Y(_0210_)
  );
  sky130_fd_sc_hd__nor4b_1 _0868_ (
    .A(pre_norm_man[17]),
    .B(_0210_),
    .C(pre_norm_man[16]),
    .D_N(_0147_),
    .Y(_0211_)
  );
  sky130_fd_sc_hd__nor2_1 _0869_ (
    .A(_0209_),
    .B(_0211_),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0870_ (
    .A(_0209_),
    .SLEEP(_0211_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__xnor2_1 _0871_ (
    .A(_0164_),
    .B(_0211_),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__a21oi_1 _0872_ (
    .A1(_0169_),
    .A2(_0214_),
    .B1(_0212_),
    .Y(_0215_)
  );
  sky130_fd_sc_hd__o211ai_1 _0873_ (
    .A1(_0165_),
    .A2(_0211_),
    .B1(_0215_),
    .C1(_0183_),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _0874_ (
    .A1_N(_0169_),
    .A2_N(_0214_),
    .B1(_0211_),
    .B2(_0165_),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__or3_1 _0875_ (
    .A(_0182_),
    .B(_0212_),
    .C(_0217_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__nand3_1 _0876_ (
    .A(_0183_),
    .B(_0203_),
    .C(_0206_),
    .Y(_0219_)
  );
  sky130_fd_sc_hd__nor4_1 _0877_ (
    .A(_0162_),
    .B(_0193_),
    .C(_0206_),
    .D(_0213_),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__nor2_1 _0878_ (
    .A(_0193_),
    .B(_0220_),
    .Y(_0221_)
  );
  sky130_fd_sc_hd__o21ai_0 _0879_ (
    .A1(_0185_),
    .A2(_0221_),
    .B1(_0218_),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__a21oi_1 _0880_ (
    .A1(_0205_),
    .A2(_0212_),
    .B1(_0185_),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__nor4b_1 _0881_ (
    .A(_0195_),
    .B(_0222_),
    .C(_0223_),
    .D_N(_0189_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0882_ (
    .A1(_0162_),
    .A2(_0185_),
    .B1(_0189_),
    .C1(_0208_),
    .D1(_0218_),
    .Y(_0225_)
  );
  sky130_fd_sc_hd__nor2_1 _0883_ (
    .A(_0184_),
    .B(_0186_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__xor2_1 _0884_ (
    .A(_0180_),
    .B(_0226_),
    .X(_0227_)
  );
  sky130_fd_sc_hd__a21oi_1 _0885_ (
    .A1(_0164_),
    .A2(_0193_),
    .B1(_0220_),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__o21a_1 _0886_ (
    .A1(_0203_),
    .A2(_0205_),
    .B1(_0228_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__nor2_1 _0887_ (
    .A(_0183_),
    .B(_0229_),
    .Y(_0230_)
  );
  sky130_fd_sc_hd__nand3_1 _0888_ (
    .A(_0182_),
    .B(_0213_),
    .C(_0217_),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__nand3_1 _0889_ (
    .A(_0208_),
    .B(_0216_),
    .C(_0231_),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__a211oi_1 _0890_ (
    .A1(_0162_),
    .A2(_0227_),
    .B1(_0230_),
    .C1(_0232_),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__nor2b_1 _0891_ (
    .A(_0225_),
    .B_N(_0233_),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__o211ai_1 _0892_ (
    .A1(_0176_),
    .A2(_0177_),
    .B1(_0179_),
    .C1(_0170_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__o211ai_1 _0893_ (
    .A1(_0178_),
    .A2(_0179_),
    .B1(_0235_),
    .C1(_0162_),
    .Y(_0236_)
  );
  sky130_fd_sc_hd__o21ai_0 _0894_ (
    .A1(_0201_),
    .A2(_0202_),
    .B1(_0207_),
    .Y(_0237_)
  );
  sky130_fd_sc_hd__xnor2_1 _0895_ (
    .A(_0169_),
    .B(_0214_),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__nand2_1 _0896_ (
    .A(_0164_),
    .B(_0220_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__o211a_1 _0897_ (
    .A1(_0212_),
    .A2(_0238_),
    .B1(_0239_),
    .C1(_0194_),
    .X(_0240_)
  );
  sky130_fd_sc_hd__a31oi_1 _0898_ (
    .A1(_0236_),
    .A2(_0237_),
    .A3(_0240_),
    .B1(_0190_),
    .Y(_0241_)
  );
  sky130_fd_sc_hd__a31o_1 _0899_ (
    .A1(_0236_),
    .A2(_0237_),
    .A3(_0240_),
    .B1(_0190_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__xor2_1 _0900_ (
    .A(_0176_),
    .B(_0177_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__xnor3_1 _0901_ (
    .A(_0169_),
    .B(_0172_),
    .C(_0199_),
    .X(_0244_)
  );
  sky130_fd_sc_hd__nor2_1 _0902_ (
    .A(_0205_),
    .B(_0244_),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__nor2_1 _0903_ (
    .A(_0169_),
    .B(_0213_),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__a21oi_1 _0904_ (
    .A1(_0169_),
    .A2(_0221_),
    .B1(_0246_),
    .Y(_0247_)
  );
  sky130_fd_sc_hd__a211oi_1 _0905_ (
    .A1(_0162_),
    .A2(_0243_),
    .B1(_0245_),
    .C1(_0247_),
    .Y(_0248_)
  );
  sky130_fd_sc_hd__or3_1 _0906_ (
    .A(_0193_),
    .B(_0213_),
    .C(_0220_),
    .X(_0249_)
  );
  sky130_fd_sc_hd__mux2i_1 _0907_ (
    .A0(_0206_),
    .A1(_0249_),
    .S(_0173_),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__xnor3_1 _0908_ (
    .A(_0173_),
    .B(_0174_),
    .C(_0175_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__o21ai_0 _0909_ (
    .A1(_0161_),
    .A2(_0251_),
    .B1(_0250_),
    .Y(_0252_)
  );
  sky130_fd_sc_hd__nand2_1 _0910_ (
    .A(_0191_),
    .B(_0252_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__xnor2_1 _0911_ (
    .A(_0162_),
    .B(_0175_),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__xnor2_1 _0912_ (
    .A(_0161_),
    .B(_0175_),
    .Y(_0255_)
  );
  sky130_fd_sc_hd__nand3_1 _0913_ (
    .A(_0191_),
    .B(_0252_),
    .C(_0254_),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__nor2_1 _0914_ (
    .A(_0248_),
    .B(_0256_),
    .Y(_0257_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0915_ (
    .A(_0190_),
    .SLEEP(_0248_),
    .X(_0258_)
  );
  sky130_fd_sc_hd__clkinv_1 _0916_ (
    .A(_0258_),
    .Y(_0259_)
  );
  sky130_fd_sc_hd__o21a_1 _0917_ (
    .A1(_0190_),
    .A2(_0248_),
    .B1(_0256_),
    .X(_0260_)
  );
  sky130_fd_sc_hd__and2_0 _0918_ (
    .A(_0242_),
    .B(_0260_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__o21a_1 _0919_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0225_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__o21ai_0 _0920_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0225_),
    .Y(_0263_)
  );
  sky130_fd_sc_hd__nand2_1 _0921_ (
    .A(_0191_),
    .B(_0255_),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__nor2_1 _0922_ (
    .A(_0253_),
    .B(_0254_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__nand2_1 _0923_ (
    .A(_0248_),
    .B(_0265_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__nor3_1 _0924_ (
    .A(_0233_),
    .B(_0241_),
    .C(_0266_),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__nor2_1 _0925_ (
    .A(_0263_),
    .B(_0267_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0926_ (
    .A(_0263_),
    .SLEEP(_0267_),
    .X(_0269_)
  );
  sky130_fd_sc_hd__xnor2_1 _0927_ (
    .A(_0242_),
    .B(_0260_),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__and2_0 _0928_ (
    .A(_0268_),
    .B(_0270_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__nand2_1 _0929_ (
    .A(_0268_),
    .B(_0270_),
    .Y(_0272_)
  );
  sky130_fd_sc_hd__nor2_1 _0930_ (
    .A(_0252_),
    .B(_0264_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__nand2_1 _0931_ (
    .A(pre_norm_man[21]),
    .B(pre_norm_man[20]),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__nor2_1 _0932_ (
    .A(pre_norm_man[18]),
    .B(pre_norm_man[16]),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__nor2_1 _0933_ (
    .A(_0137_),
    .B(_0275_),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__o211ai_1 _0934_ (
    .A1(pre_norm_man[15]),
    .A2(pre_norm_man[13]),
    .B1(_0144_),
    .C1(pre_norm_man[14]),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__a22oi_1 _0935_ (
    .A1(pre_norm_man[10]),
    .A2(_0146_),
    .B1(_0152_),
    .B2(pre_norm_man[12]),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__a32oi_1 _0936_ (
    .A1(pre_norm_man[10]),
    .A2(_0147_),
    .A3(_0148_),
    .B1(_0211_),
    .B2(pre_norm_man[7]),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__a221oi_1 _0937_ (
    .A1(pre_norm_man[18]),
    .A2(_0139_),
    .B1(_0209_),
    .B2(pre_norm_man[15]),
    .C1(_0276_),
    .Y(_0280_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0938_ (
    .A1(_0145_),
    .A2(_0192_),
    .B1(_0274_),
    .C1(_0277_),
    .D1(_0280_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__a21oi_1 _0939_ (
    .A1(pre_norm_man[8]),
    .A2(_0150_),
    .B1(_0281_),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__nand3_1 _0940_ (
    .A(_0278_),
    .B(_0279_),
    .C(_0282_),
    .Y(_0283_)
  );
  sky130_fd_sc_hd__a21oi_1 _0941_ (
    .A1(pre_norm_man[19]),
    .A2(_0220_),
    .B1(_0283_),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__a21o_1 _0942_ (
    .A1(pre_norm_man[13]),
    .A2(_0144_),
    .B1(_0138_),
    .X(_0285_)
  );
  sky130_fd_sc_hd__nand2_1 _0943_ (
    .A(pre_norm_man[11]),
    .B(_0152_),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0944_ (
    .A(pre_norm_man[17]),
    .SLEEP(pre_norm_man[20]),
    .X(_0287_)
  );
  sky130_fd_sc_hd__o21a_1 _0945_ (
    .A1(pre_norm_man[21]),
    .A2(_0287_),
    .B1(pre_norm_man[19]),
    .X(_0288_)
  );
  sky130_fd_sc_hd__a222oi_1 _0946_ (
    .A1(pre_norm_man[7]),
    .A2(_0150_),
    .B1(_0199_),
    .B2(pre_norm_man[12]),
    .C1(pre_norm_man[15]),
    .C2(_0285_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__a21oi_1 _0947_ (
    .A1(pre_norm_man[14]),
    .A2(_0209_),
    .B1(_0288_),
    .Y(_0290_)
  );
  sky130_fd_sc_hd__a22oi_1 _0948_ (
    .A1(pre_norm_man[8]),
    .A2(_0197_),
    .B1(_0204_),
    .B2(pre_norm_man[16]),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__o211a_1 _0949_ (
    .A1(_0192_),
    .A2(_0196_),
    .B1(_0290_),
    .C1(_0291_),
    .X(_0292_)
  );
  sky130_fd_sc_hd__nand3_1 _0950_ (
    .A(_0286_),
    .B(_0289_),
    .C(_0292_),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__a221oi_1 _0951_ (
    .A1(pre_norm_man[9]),
    .A2(_0146_),
    .B1(_0220_),
    .B2(pre_norm_man[18]),
    .C1(_0293_),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__mux2i_1 _0952_ (
    .A0(_0294_),
    .A1(_0284_),
    .S(_0264_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0953_ (
    .A(_0273_),
    .SLEEP(_0295_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0954_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0296_),
    .C1(_0260_),
    .D1(_0225_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__o22ai_1 _0955_ (
    .A1(_0268_),
    .A2(_0294_),
    .B1(_0297_),
    .B2(_0272_),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__nor2_1 _0956_ (
    .A(_0257_),
    .B(_0260_),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0957_ (
    .A(_0257_),
    .SLEEP(_0260_),
    .X(_0300_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0958_ (
    .A(_0256_),
    .SLEEP(_0273_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__o21ai_0 _0959_ (
    .A1(_0252_),
    .A2(_0264_),
    .B1(_0256_),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__a21oi_1 _0960_ (
    .A1(_0255_),
    .A2(_0284_),
    .B1(_0190_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__o211ai_1 _0961_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0303_),
    .C1(_0225_),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__nand2_1 _0962_ (
    .A(pre_norm_man[17]),
    .B(_0220_),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__nand2_1 _0963_ (
    .A(pre_norm_man[10]),
    .B(_0152_),
    .Y(_0306_)
  );
  sky130_fd_sc_hd__nand2_1 _0964_ (
    .A(pre_norm_man[8]),
    .B(_0146_),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__a32oi_1 _0965_ (
    .A1(pre_norm_man[15]),
    .A2(pre_norm_man[12]),
    .A3(_0144_),
    .B1(_0199_),
    .B2(pre_norm_man[11]),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__a22oi_1 _0966_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[18]),
    .B1(pre_norm_man[7]),
    .B2(_0197_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__a222oi_1 _0967_ (
    .A1(pre_norm_man[14]),
    .A2(_0138_),
    .B1(_0204_),
    .B2(pre_norm_man[15]),
    .C1(_0209_),
    .C2(pre_norm_man[13]),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__nand3_1 _0968_ (
    .A(_0307_),
    .B(_0309_),
    .C(_0310_),
    .Y(_0311_)
  );
  sky130_fd_sc_hd__a221oi_1 _0969_ (
    .A1(pre_norm_man[16]),
    .A2(_0139_),
    .B1(_0193_),
    .B2(pre_norm_man[9]),
    .C1(_0311_),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__nand4_1 _0970_ (
    .A(_0305_),
    .B(_0306_),
    .C(_0308_),
    .D(_0312_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__nor2_1 _0971_ (
    .A(_0264_),
    .B(_0313_),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__a21oi_1 _0972_ (
    .A1(_0264_),
    .A2(_0294_),
    .B1(_0314_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__o211ai_1 _0973_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0315_),
    .C1(_0225_),
    .Y(_0316_)
  );
  sky130_fd_sc_hd__mux2i_1 _0974_ (
    .A0(_0304_),
    .A1(_0316_),
    .S(_0301_),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__nand3_1 _0975_ (
    .A(_0271_),
    .B(_0300_),
    .C(_0317_),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__nand2_1 _0976_ (
    .A(_0269_),
    .B(_0313_),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__nand2_1 _0977_ (
    .A(_0318_),
    .B(_0319_),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__a21oi_1 _0978_ (
    .A1(pre_norm_man[11]),
    .A2(_0144_),
    .B1(_0139_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__nand2_1 _0979_ (
    .A(pre_norm_man[14]),
    .B(_0204_),
    .Y(_0322_)
  );
  sky130_fd_sc_hd__a222oi_1 _0980_ (
    .A1(pre_norm_man[9]),
    .A2(_0152_),
    .B1(_0193_),
    .B2(pre_norm_man[8]),
    .C1(_0209_),
    .C2(pre_norm_man[12]),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__a222oi_1 _0981_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[17]),
    .B1(pre_norm_man[7]),
    .B2(_0146_),
    .C1(_0199_),
    .C2(pre_norm_man[10]),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0982_ (
    .A1(_0640_),
    .A2(_0321_),
    .B1(_0322_),
    .C1(_0323_),
    .D1(_0324_),
    .Y(_0325_)
  );
  sky130_fd_sc_hd__a221o_1 _0983_ (
    .A1(pre_norm_man[13]),
    .A2(_0138_),
    .B1(_0220_),
    .B2(pre_norm_man[16]),
    .C1(_0325_),
    .X(_0326_)
  );
  sky130_fd_sc_hd__mux2i_1 _0984_ (
    .A0(_0326_),
    .A1(_0313_),
    .S(_0264_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__nor2_1 _0985_ (
    .A(_0295_),
    .B(_0301_),
    .Y(_0328_)
  );
  sky130_fd_sc_hd__a21oi_1 _0986_ (
    .A1(_0301_),
    .A2(_0327_),
    .B1(_0328_),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__and2_0 _0987_ (
    .A(_0262_),
    .B(_0329_),
    .X(_0330_)
  );
  sky130_fd_sc_hd__nor2_1 _0988_ (
    .A(_0299_),
    .B(_0330_),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__nand2_1 _0989_ (
    .A(_0262_),
    .B(_0265_),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__a21oi_1 _0990_ (
    .A1(_0299_),
    .A2(_0332_),
    .B1(_0331_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__a22o_1 _0991_ (
    .A1(_0269_),
    .A2(_0326_),
    .B1(_0333_),
    .B2(_0271_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__a21o_1 _0992_ (
    .A1(pre_norm_man[10]),
    .A2(_0144_),
    .B1(_0220_),
    .X(_0335_)
  );
  sky130_fd_sc_hd__a222oi_1 _0993_ (
    .A1(pre_norm_man[13]),
    .A2(_0204_),
    .B1(_0209_),
    .B2(pre_norm_man[11]),
    .C1(pre_norm_man[8]),
    .C2(_0152_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__a22oi_1 _0994_ (
    .A1(pre_norm_man[14]),
    .A2(_0139_),
    .B1(_0199_),
    .B2(pre_norm_man[9]),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__a222oi_1 _0995_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[16]),
    .B1(pre_norm_man[12]),
    .B2(_0138_),
    .C1(_0193_),
    .C2(pre_norm_man[7]),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__nand3_1 _0996_ (
    .A(_0336_),
    .B(_0337_),
    .C(_0338_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__a21oi_1 _0997_ (
    .A1(pre_norm_man[15]),
    .A2(_0335_),
    .B1(_0339_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__nand2_1 _0998_ (
    .A(_0264_),
    .B(_0326_),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__o21ai_0 _0999_ (
    .A1(_0264_),
    .A2(_0340_),
    .B1(_0341_),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__o211ai_1 _1000_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0342_),
    .C1(_0225_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__mux2i_1 _1001_ (
    .A0(_0316_),
    .A1(_0343_),
    .S(_0301_),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__nor2_1 _1002_ (
    .A(_0299_),
    .B(_0344_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__a31oi_1 _1003_ (
    .A1(_0262_),
    .A2(_0301_),
    .A3(_0303_),
    .B1(_0300_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__o32a_1 _1004_ (
    .A1(_0272_),
    .A2(_0345_),
    .A3(_0346_),
    .B1(_0340_),
    .B2(_0268_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__o21bai_1 _1005_ (
    .A1(_0330_),
    .A2(_0344_),
    .B1_N(_0270_),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__nand2_1 _1006_ (
    .A(pre_norm_man[14]),
    .B(_0220_),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__nand2_1 _1007_ (
    .A(pre_norm_man[11]),
    .B(_0138_),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__a222oi_1 _1008_ (
    .A1(pre_norm_man[13]),
    .A2(_0139_),
    .B1(_0204_),
    .B2(pre_norm_man[12]),
    .C1(_0209_),
    .C2(pre_norm_man[10]),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__nand2_1 _1009_ (
    .A(_0350_),
    .B(_0351_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__o21ai_0 _1010_ (
    .A1(pre_norm_man[21]),
    .A2(_0148_),
    .B1(pre_norm_man[15]),
    .Y(_0353_)
  );
  sky130_fd_sc_hd__a221oi_1 _1011_ (
    .A1(pre_norm_man[7]),
    .A2(_0152_),
    .B1(_0199_),
    .B2(pre_norm_man[8]),
    .C1(_0352_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__nand3_1 _1012_ (
    .A(_0349_),
    .B(_0353_),
    .C(_0354_),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__nand2_1 _1013_ (
    .A(pre_norm_man[13]),
    .B(_0220_),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__nand2b_1 _1014_ (
    .A_N(pre_norm_man[21]),
    .B(_0159_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__nand3_1 _1015_ (
    .A(pre_norm_man[15]),
    .B(pre_norm_man[8]),
    .C(_0144_),
    .Y(_0358_)
  );
  sky130_fd_sc_hd__nand2_1 _1016_ (
    .A(pre_norm_man[10]),
    .B(_0138_),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__a222oi_1 _1017_ (
    .A1(pre_norm_man[12]),
    .A2(_0139_),
    .B1(_0204_),
    .B2(pre_norm_man[11]),
    .C1(_0209_),
    .C2(pre_norm_man[9]),
    .Y(_0360_)
  );
  sky130_fd_sc_hd__nand3_1 _1018_ (
    .A(_0358_),
    .B(_0359_),
    .C(_0360_),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__a21oi_1 _1019_ (
    .A1(pre_norm_man[14]),
    .A2(_0357_),
    .B1(_0361_),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__nand2_1 _1020_ (
    .A(_0356_),
    .B(_0362_),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__mux2_1 _1021_ (
    .A0(_0363_),
    .A1(_0355_),
    .S(_0264_),
    .X(_0364_)
  );
  sky130_fd_sc_hd__o211ai_1 _1022_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0364_),
    .C1(_0225_),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__nand2_1 _1023_ (
    .A(pre_norm_man[8]),
    .B(_0209_),
    .Y(_0366_)
  );
  sky130_fd_sc_hd__a222oi_1 _1024_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[13]),
    .B1(pre_norm_man[11]),
    .B2(_0139_),
    .C1(_0204_),
    .C2(pre_norm_man[10]),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__a32oi_1 _1025_ (
    .A1(pre_norm_man[15]),
    .A2(pre_norm_man[7]),
    .A3(_0144_),
    .B1(_0138_),
    .B2(pre_norm_man[9]),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__nand3_1 _1026_ (
    .A(_0366_),
    .B(_0367_),
    .C(_0368_),
    .Y(_0369_)
  );
  sky130_fd_sc_hd__a21oi_1 _1027_ (
    .A1(pre_norm_man[12]),
    .A2(_0220_),
    .B1(_0369_),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__nand2_1 _1028_ (
    .A(pre_norm_man[7]),
    .B(_0209_),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__nand2_1 _1029_ (
    .A(pre_norm_man[8]),
    .B(_0138_),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__a222oi_1 _1030_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[12]),
    .B1(pre_norm_man[10]),
    .B2(_0139_),
    .C1(_0204_),
    .C2(pre_norm_man[9]),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__nand3_1 _1031_ (
    .A(_0371_),
    .B(_0372_),
    .C(_0373_),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__a21oi_1 _1032_ (
    .A1(pre_norm_man[11]),
    .A2(_0220_),
    .B1(_0374_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__mux2i_1 _1033_ (
    .A0(_0375_),
    .A1(_0370_),
    .S(_0264_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__o211ai_1 _1034_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0376_),
    .C1(_0225_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__nor2_1 _1035_ (
    .A(_0302_),
    .B(_0377_),
    .Y(_0378_)
  );
  sky130_fd_sc_hd__nor2_1 _1036_ (
    .A(_0301_),
    .B(_0365_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__o2111ai_1 _1037_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0302_),
    .C1(_0364_),
    .D1(_0225_),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__nand2_1 _1038_ (
    .A(_0264_),
    .B(_0340_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__o21ai_0 _1039_ (
    .A1(_0264_),
    .A2(_0355_),
    .B1(_0381_),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__nor2_1 _1040_ (
    .A(_0301_),
    .B(_0382_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__nor2_1 _1041_ (
    .A(_0264_),
    .B(_0370_),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__a21oi_1 _1042_ (
    .A1(_0264_),
    .A2(_0363_),
    .B1(_0384_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__nor2_1 _1043_ (
    .A(_0302_),
    .B(_0385_),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__o221ai_1 _1044_ (
    .A1(_0233_),
    .A2(_0261_),
    .B1(_0383_),
    .B2(_0386_),
    .C1(_0225_),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__o2111ai_1 _1045_ (
    .A1(_0302_),
    .A2(_0377_),
    .B1(_0380_),
    .C1(_0387_),
    .D1(_0241_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__mux2i_1 _1046_ (
    .A0(_0327_),
    .A1(_0382_),
    .S(_0301_),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__nand2_1 _1047_ (
    .A(_0299_),
    .B(_0389_),
    .Y(_0390_)
  );
  sky130_fd_sc_hd__nand2_1 _1048_ (
    .A(_0302_),
    .B(_0385_),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__nand2_1 _1049_ (
    .A(pre_norm_man[10]),
    .B(_0220_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__nand2_1 _1050_ (
    .A(pre_norm_man[7]),
    .B(_0138_),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__a222oi_1 _1051_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[11]),
    .B1(pre_norm_man[9]),
    .B2(_0139_),
    .C1(_0204_),
    .C2(pre_norm_man[8]),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__nand3_1 _1052_ (
    .A(_0392_),
    .B(_0393_),
    .C(_0394_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__nand2_1 _1053_ (
    .A(_0264_),
    .B(_0375_),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__o21ai_0 _1054_ (
    .A1(_0264_),
    .A2(_0395_),
    .B1(_0396_),
    .Y(_0397_)
  );
  sky130_fd_sc_hd__nand2_1 _1055_ (
    .A(_0301_),
    .B(_0397_),
    .Y(_0398_)
  );
  sky130_fd_sc_hd__nand2_1 _1056_ (
    .A(_0391_),
    .B(_0398_),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__o221ai_1 _1057_ (
    .A1(_0242_),
    .A2(_0297_),
    .B1(_0399_),
    .B2(_0263_),
    .C1(_0390_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__nand2_1 _1058_ (
    .A(pre_norm_man[9]),
    .B(_0220_),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__a222oi_1 _1059_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[10]),
    .B1(pre_norm_man[8]),
    .B2(_0139_),
    .C1(_0204_),
    .C2(pre_norm_man[7]),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__nand2_1 _1060_ (
    .A(_0401_),
    .B(_0402_),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__mux2i_1 _1061_ (
    .A0(_0403_),
    .A1(_0395_),
    .S(_0264_),
    .Y(_0404_)
  );
  sky130_fd_sc_hd__a21oi_1 _1062_ (
    .A1(_0397_),
    .A2(_0404_),
    .B1(_0301_),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__o21ai_0 _1063_ (
    .A1(pre_norm_man[8]),
    .A2(pre_norm_man[7]),
    .B1(_0220_),
    .Y(_0406_)
  );
  sky130_fd_sc_hd__o31ai_1 _1064_ (
    .A1(pre_norm_man[9]),
    .A2(pre_norm_man[8]),
    .A3(pre_norm_man[7]),
    .B1(pre_norm_man[21]),
    .Y(_0407_)
  );
  sky130_fd_sc_hd__nand2_1 _1065_ (
    .A(pre_norm_man[7]),
    .B(_0139_),
    .Y(_0408_)
  );
  sky130_fd_sc_hd__nand3_1 _1066_ (
    .A(_0406_),
    .B(_0407_),
    .C(_0408_),
    .Y(_0409_)
  );
  sky130_fd_sc_hd__a211o_1 _1067_ (
    .A1(_0264_),
    .A2(_0403_),
    .B1(_0405_),
    .C1(_0409_),
    .X(_0410_)
  );
  sky130_fd_sc_hd__a211oi_1 _1068_ (
    .A1(_0299_),
    .A2(_0388_),
    .B1(_0400_),
    .C1(_0410_),
    .Y(_0411_)
  );
  sky130_fd_sc_hd__nand3b_1 _1069_ (
    .A_N(_0270_),
    .B(_0300_),
    .C(_0317_),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__mux2i_1 _1070_ (
    .A0(_0343_),
    .A1(_0365_),
    .S(_0301_),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__mux2i_1 _1071_ (
    .A0(_0377_),
    .A1(_0404_),
    .S(_0301_),
    .Y(_0414_)
  );
  sky130_fd_sc_hd__a21oi_1 _1072_ (
    .A1(_0299_),
    .A2(_0413_),
    .B1(_0414_),
    .Y(_0415_)
  );
  sky130_fd_sc_hd__a221oi_1 _1073_ (
    .A1(_0348_),
    .A2(_0411_),
    .B1(_0412_),
    .B2(_0415_),
    .C1(_0269_),
    .Y(_0416_)
  );
  sky130_fd_sc_hd__o21ai_0 _1074_ (
    .A1(_0395_),
    .A2(_0409_),
    .B1(_0403_),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__nor2_1 _1075_ (
    .A(_0268_),
    .B(_0417_),
    .Y(_0418_)
  );
  sky130_fd_sc_hd__nor2_1 _1076_ (
    .A(_0269_),
    .B(_0400_),
    .Y(_0419_)
  );
  sky130_fd_sc_hd__nor2_1 _1077_ (
    .A(_0268_),
    .B(_0395_),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__nor2_1 _1078_ (
    .A(_0419_),
    .B(_0420_),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__o21ai_0 _1079_ (
    .A1(_0416_),
    .A2(_0418_),
    .B1(_0421_),
    .Y(_0422_)
  );
  sky130_fd_sc_hd__o31ai_1 _1080_ (
    .A1(_0299_),
    .A2(_0302_),
    .A3(_0304_),
    .B1(_0268_),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__nand2_1 _1081_ (
    .A(_0272_),
    .B(_0423_),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__o21ai_0 _1082_ (
    .A1(_0378_),
    .A2(_0379_),
    .B1(_0300_),
    .Y(_0425_)
  );
  sky130_fd_sc_hd__nand2_1 _1083_ (
    .A(_0299_),
    .B(_0344_),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__a32oi_1 _1084_ (
    .A1(_0424_),
    .A2(_0425_),
    .A3(_0426_),
    .B1(_0375_),
    .B2(_0269_),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__nor2b_1 _1085_ (
    .A(_0422_),
    .B_N(_0427_),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__o211ai_1 _1086_ (
    .A1(_0270_),
    .A2(_0332_),
    .B1(_0387_),
    .C1(_0300_),
    .Y(_0429_)
  );
  sky130_fd_sc_hd__o21ai_0 _1087_ (
    .A1(_0300_),
    .A2(_0329_),
    .B1(_0429_),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__mux2i_1 _1088_ (
    .A0(_0370_),
    .A1(_0430_),
    .S(_0268_),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__nand3b_1 _1089_ (
    .A_N(_0422_),
    .B(_0427_),
    .C(_0431_),
    .Y(_0432_)
  );
  sky130_fd_sc_hd__nand2_1 _1090_ (
    .A(_0300_),
    .B(_0413_),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__nand2_1 _1091_ (
    .A(_0299_),
    .B(_0317_),
    .Y(_0434_)
  );
  sky130_fd_sc_hd__nor2_1 _1092_ (
    .A(_0268_),
    .B(_0363_),
    .Y(_0435_)
  );
  sky130_fd_sc_hd__a31oi_1 _1093_ (
    .A1(_0268_),
    .A2(_0433_),
    .A3(_0434_),
    .B1(_0435_),
    .Y(_0436_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1094_ (
    .A(_0436_),
    .SLEEP(_0432_),
    .X(_0437_)
  );
  sky130_fd_sc_hd__nand4_1 _1095_ (
    .A(_0256_),
    .B(_0259_),
    .C(_0262_),
    .D(_0296_),
    .Y(_0438_)
  );
  sky130_fd_sc_hd__nand2_1 _1096_ (
    .A(_0300_),
    .B(_0389_),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__a21oi_1 _1097_ (
    .A1(_0438_),
    .A2(_0439_),
    .B1(_0269_),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__a21oi_1 _1098_ (
    .A1(_0269_),
    .A2(_0355_),
    .B1(_0440_),
    .Y(_0441_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1099_ (
    .A(_0437_),
    .SLEEP(_0441_),
    .X(_0442_)
  );
  sky130_fd_sc_hd__nor4b_1 _1100_ (
    .A(_0347_),
    .B(_0441_),
    .C(_0432_),
    .D_N(_0436_),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__nand2_1 _1101_ (
    .A(_0334_),
    .B(_0443_),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__a21oi_1 _1102_ (
    .A1(_0318_),
    .A2(_0319_),
    .B1(_0444_),
    .Y(_0445_)
  );
  sky130_fd_sc_hd__and4_1 _1103_ (
    .A(_0298_),
    .B(_0320_),
    .C(_0334_),
    .D(_0443_),
    .X(_0446_)
  );
  sky130_fd_sc_hd__nand4_1 _1104_ (
    .A(_0298_),
    .B(_0320_),
    .C(_0334_),
    .D(_0443_),
    .Y(_0447_)
  );
  sky130_fd_sc_hd__o21ai_0 _1105_ (
    .A1(_0268_),
    .A2(_0284_),
    .B1(_0272_),
    .Y(_0448_)
  );
  sky130_fd_sc_hd__nand2_1 _1106_ (
    .A(_0423_),
    .B(_0448_),
    .Y(_0449_)
  );
  sky130_fd_sc_hd__and2_0 _1107_ (
    .A(_0423_),
    .B(_0448_),
    .X(_0450_)
  );
  sky130_fd_sc_hd__nor2_1 _1108_ (
    .A(_0447_),
    .B(_0449_),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__and4_1 _1109_ (
    .A(_0241_),
    .B(_0257_),
    .C(_0446_),
    .D(_0450_),
    .X(_0452_)
  );
  sky130_fd_sc_hd__a41oi_1 _1110_ (
    .A1(_0241_),
    .A2(_0257_),
    .A3(_0446_),
    .A4(_0450_),
    .B1(_0234_),
    .Y(_0453_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1111_ (
    .A(_0234_),
    .SLEEP(_0452_),
    .X(_0454_)
  );
  sky130_fd_sc_hd__a31oi_1 _1112_ (
    .A1(_0257_),
    .A2(_0446_),
    .A3(_0450_),
    .B1(_0241_),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__nor3_1 _1113_ (
    .A(_0268_),
    .B(_0452_),
    .C(_0455_),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__or3_1 _1114_ (
    .A(_0264_),
    .B(_0447_),
    .C(_0449_),
    .X(_0457_)
  );
  sky130_fd_sc_hd__o21ai_0 _1115_ (
    .A1(_0447_),
    .A2(_0449_),
    .B1(_0264_),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__nand2_1 _1116_ (
    .A(_0457_),
    .B(_0458_),
    .Y(_0459_)
  );
  sky130_fd_sc_hd__nand3_1 _1117_ (
    .A(_0269_),
    .B(_0457_),
    .C(_0458_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__nand3_1 _1118_ (
    .A(_0301_),
    .B(_0446_),
    .C(_0450_),
    .Y(_0461_)
  );
  sky130_fd_sc_hd__o21ai_0 _1119_ (
    .A1(_0253_),
    .A2(_0451_),
    .B1(_0461_),
    .Y(_0462_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1120_ (
    .A(_0460_),
    .SLEEP(_0462_),
    .X(_0463_)
  );
  sky130_fd_sc_hd__a21oi_1 _1121_ (
    .A1(_0446_),
    .A2(_0450_),
    .B1(_0259_),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__a211oi_1 _1122_ (
    .A1(_0300_),
    .A2(_0451_),
    .B1(_0464_),
    .C1(_0268_),
    .Y(_0465_)
  );
  sky130_fd_sc_hd__or3_1 _1123_ (
    .A(_0460_),
    .B(_0462_),
    .C(_0465_),
    .X(_0466_)
  );
  sky130_fd_sc_hd__or4_1 _1124_ (
    .A(_0456_),
    .B(_0460_),
    .C(_0462_),
    .D(_0465_),
    .X(_0467_)
  );
  sky130_fd_sc_hd__o41ai_1 _1125_ (
    .A1(_0456_),
    .A2(_0460_),
    .A3(_0462_),
    .A4(_0465_),
    .B1(_0454_),
    .Y(_0468_)
  );
  sky130_fd_sc_hd__a32oi_1 _1126_ (
    .A1(_0219_),
    .A2(_0224_),
    .A3(_0453_),
    .B1(_0452_),
    .B2(_0234_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__and2_0 _1127_ (
    .A(_0133_),
    .B(_0469_),
    .X(_0470_)
  );
  sky130_fd_sc_hd__a21oi_1 _1128_ (
    .A1(_0468_),
    .A2(_0470_),
    .B1(_0134_),
    .Y(ans[14])
  );
  sky130_fd_sc_hd__o31ai_1 _1129_ (
    .A1(_0460_),
    .A2(_0462_),
    .A3(_0465_),
    .B1(_0456_),
    .Y(_0471_)
  );
  sky130_fd_sc_hd__a31oi_1 _1130_ (
    .A1(_0467_),
    .A2(_0470_),
    .A3(_0471_),
    .B1(_0134_),
    .Y(ans[13])
  );
  sky130_fd_sc_hd__o21ai_0 _1131_ (
    .A1(_0460_),
    .A2(_0462_),
    .B1(_0465_),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__a31oi_1 _1132_ (
    .A1(_0466_),
    .A2(_0470_),
    .A3(_0472_),
    .B1(_0134_),
    .Y(ans[12])
  );
  sky130_fd_sc_hd__nand3_1 _1133_ (
    .A(_0269_),
    .B(_0459_),
    .C(_0462_),
    .Y(_0473_)
  );
  sky130_fd_sc_hd__a31oi_1 _1134_ (
    .A1(_0463_),
    .A2(_0470_),
    .A3(_0473_),
    .B1(_0134_),
    .Y(ans[11])
  );
  sky130_fd_sc_hd__nand2_1 _1135_ (
    .A(_0268_),
    .B(_0451_),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__a31oi_1 _1136_ (
    .A1(_0460_),
    .A2(_0470_),
    .A3(_0474_),
    .B1(_0134_),
    .Y(ans[10])
  );
  sky130_fd_sc_hd__a211oi_1 _1137_ (
    .A1(infinA),
    .A2(infinB),
    .B1(nanA),
    .C1(nanB),
    .Y(_0475_)
  );
  sky130_fd_sc_hd__xnor2_1 _1138_ (
    .A(_0446_),
    .B(_0449_),
    .Y(_0476_)
  );
  sky130_fd_sc_hd__nand3_1 _1139_ (
    .A(_0132_),
    .B(_0469_),
    .C(_0476_),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__o31ai_1 _1140_ (
    .A1(infinA),
    .A2(infinB),
    .A3(_0477_),
    .B1(_0475_),
    .Y(ans[9])
  );
  sky130_fd_sc_hd__nand3_1 _1141_ (
    .A(_0132_),
    .B(_0133_),
    .C(_0469_),
    .Y(_0478_)
  );
  sky130_fd_sc_hd__nor2_1 _1142_ (
    .A(_0298_),
    .B(_0445_),
    .Y(_0479_)
  );
  sky130_fd_sc_hd__nor3_1 _1143_ (
    .A(_0446_),
    .B(_0478_),
    .C(_0479_),
    .Y(ans[8])
  );
  sky130_fd_sc_hd__a21oi_1 _1144_ (
    .A1(_0334_),
    .A2(_0443_),
    .B1(_0320_),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__nor3_1 _1145_ (
    .A(_0445_),
    .B(_0478_),
    .C(_0480_),
    .Y(ans[7])
  );
  sky130_fd_sc_hd__nor2_1 _1146_ (
    .A(_0334_),
    .B(_0443_),
    .Y(_0481_)
  );
  sky130_fd_sc_hd__nor3b_1 _1147_ (
    .A(_0478_),
    .B(_0481_),
    .C_N(_0444_),
    .Y(ans[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1148_ (
    .A(_0347_),
    .SLEEP(_0442_),
    .X(_0482_)
  );
  sky130_fd_sc_hd__nor3_1 _1149_ (
    .A(_0443_),
    .B(_0478_),
    .C(_0482_),
    .Y(ans[5])
  );
  sky130_fd_sc_hd__xor2_1 _1150_ (
    .A(_0437_),
    .B(_0441_),
    .X(_0483_)
  );
  sky130_fd_sc_hd__nor2_1 _1151_ (
    .A(_0478_),
    .B(_0483_),
    .Y(ans[4])
  );
  sky130_fd_sc_hd__a21oi_1 _1152_ (
    .A1(_0428_),
    .A2(_0431_),
    .B1(_0436_),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__nor3_1 _1153_ (
    .A(_0437_),
    .B(_0478_),
    .C(_0484_),
    .Y(ans[3])
  );
  sky130_fd_sc_hd__xnor2_1 _1154_ (
    .A(_0428_),
    .B(_0431_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__nor2_1 _1155_ (
    .A(_0478_),
    .B(_0485_),
    .Y(ans[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1156_ (
    .A(_0422_),
    .SLEEP(_0427_),
    .X(_0486_)
  );
  sky130_fd_sc_hd__nor3_1 _1157_ (
    .A(_0428_),
    .B(_0478_),
    .C(_0486_),
    .Y(ans[1])
  );
  sky130_fd_sc_hd__nor3_1 _1158_ (
    .A(_0416_),
    .B(_0418_),
    .C(_0421_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__nor3b_1 _1159_ (
    .A(_0478_),
    .B(_0487_),
    .C_N(_0422_),
    .Y(ans[0])
  );
  sky130_fd_sc_hd__xor2_1 _1160_ (
    .A(b[15]),
    .B(sub),
    .X(signB)
  );
  sky130_fd_sc_hd__nand2_1 _1161_ (
    .A(_0003_),
    .B(_0040_),
    .Y(_0488_)
  );
  sky130_fd_sc_hd__and3_1 _1162_ (
    .A(_0009_),
    .B(_0053_),
    .C(_0061_),
    .X(_0489_)
  );
  sky130_fd_sc_hd__and3_1 _1163_ (
    .A(_0047_),
    .B(_0100_),
    .C(_0489_),
    .X(_0490_)
  );
  sky130_fd_sc_hd__clkinv_1 _1164_ (
    .A(_0490_),
    .Y(_0491_)
  );
  sky130_fd_sc_hd__and3_1 _1165_ (
    .A(_0047_),
    .B(_0092_),
    .C(_0100_),
    .X(_0492_)
  );
  sky130_fd_sc_hd__mux2i_1 _1166_ (
    .A0(b[9]),
    .A1(a[9]),
    .S(_0040_),
    .Y(_0493_)
  );
  sky130_fd_sc_hd__nand2b_1 _1167_ (
    .A_N(_0492_),
    .B(_0493_),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1168_ (
    .A(_0492_),
    .SLEEP(_0493_),
    .X(_0495_)
  );
  sky130_fd_sc_hd__and3_1 _1169_ (
    .A(_0047_),
    .B(_0075_),
    .C(_0100_),
    .X(_0496_)
  );
  sky130_fd_sc_hd__mux2i_1 _1170_ (
    .A0(b[8]),
    .A1(a[8]),
    .S(_0040_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__clkinv_1 _1171_ (
    .A(_0497_),
    .Y(_0498_)
  );
  sky130_fd_sc_hd__nand2_1 _1172_ (
    .A(_0496_),
    .B(_0497_),
    .Y(_0499_)
  );
  sky130_fd_sc_hd__nor2_1 _1173_ (
    .A(_0496_),
    .B(_0497_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1174_ (
    .A(_0499_),
    .SLEEP(_0500_),
    .X(_0501_)
  );
  sky130_fd_sc_hd__nor2_1 _1175_ (
    .A(_0048_),
    .B(_0064_),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__and2_0 _1176_ (
    .A(_0100_),
    .B(_0502_),
    .X(_0503_)
  );
  sky130_fd_sc_hd__mux2i_1 _1177_ (
    .A0(b[7]),
    .A1(a[7]),
    .S(_0040_),
    .Y(_0504_)
  );
  sky130_fd_sc_hd__nand2b_1 _1178_ (
    .A_N(_0503_),
    .B(_0504_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1179_ (
    .A(_0503_),
    .SLEEP(_0504_),
    .X(_0506_)
  );
  sky130_fd_sc_hd__nand2_1 _1180_ (
    .A(_0048_),
    .B(_0489_),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__o21ai_0 _1181_ (
    .A1(_0048_),
    .A2(_0081_),
    .B1(_0507_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__nand2_1 _1182_ (
    .A(_0100_),
    .B(_0508_),
    .Y(_0509_)
  );
  sky130_fd_sc_hd__clkinv_1 _1183_ (
    .A(_0509_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__mux2i_1 _1184_ (
    .A0(b[6]),
    .A1(a[6]),
    .S(_0040_),
    .Y(_0511_)
  );
  sky130_fd_sc_hd__and2_0 _1185_ (
    .A(_0509_),
    .B(_0511_),
    .X(_0512_)
  );
  sky130_fd_sc_hd__nor2_1 _1186_ (
    .A(_0509_),
    .B(_0511_),
    .Y(_0513_)
  );
  sky130_fd_sc_hd__nand2_1 _1187_ (
    .A(_0094_),
    .B(_0100_),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__mux2i_1 _1188_ (
    .A0(b[5]),
    .A1(a[5]),
    .S(_0040_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__and2_0 _1189_ (
    .A(_0080_),
    .B(_0100_),
    .X(_0516_)
  );
  sky130_fd_sc_hd__mux2i_1 _1190_ (
    .A0(b[4]),
    .A1(a[4]),
    .S(_0040_),
    .Y(_0517_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1191_ (
    .A(_0516_),
    .SLEEP(_0517_),
    .X(_0518_)
  );
  sky130_fd_sc_hd__nand2_1 _1192_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0519_)
  );
  sky130_fd_sc_hd__nor2_1 _1193_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0520_)
  );
  sky130_fd_sc_hd__xnor2_1 _1194_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0521_)
  );
  sky130_fd_sc_hd__nand2_1 _1195_ (
    .A(_0072_),
    .B(_0100_),
    .Y(_0522_)
  );
  sky130_fd_sc_hd__mux2i_1 _1196_ (
    .A0(b[3]),
    .A1(a[3]),
    .S(_0040_),
    .Y(_0523_)
  );
  sky130_fd_sc_hd__and2_0 _1197_ (
    .A(_0522_),
    .B(_0523_),
    .X(_0524_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1198_ (
    .A(_0522_),
    .SLEEP(_0523_),
    .X(_0525_)
  );
  sky130_fd_sc_hd__a32oi_1 _1199_ (
    .A1(_0047_),
    .A2(_0098_),
    .A3(_0489_),
    .B1(_0100_),
    .B2(_0085_),
    .Y(_0526_)
  );
  sky130_fd_sc_hd__clkinv_1 _1200_ (
    .A(_0526_),
    .Y(_0527_)
  );
  sky130_fd_sc_hd__mux2i_1 _1201_ (
    .A0(b[2]),
    .A1(a[2]),
    .S(_0040_),
    .Y(_0528_)
  );
  sky130_fd_sc_hd__nand2_1 _1202_ (
    .A(_0526_),
    .B(_0528_),
    .Y(_0529_)
  );
  sky130_fd_sc_hd__nor2_1 _1203_ (
    .A(_0526_),
    .B(_0528_),
    .Y(_0530_)
  );
  sky130_fd_sc_hd__a32oi_1 _1204_ (
    .A1(_0047_),
    .A2(_0092_),
    .A3(_0098_),
    .B1(_0100_),
    .B2(_0090_),
    .Y(_0531_)
  );
  sky130_fd_sc_hd__clkinv_1 _1205_ (
    .A(_0531_),
    .Y(_0532_)
  );
  sky130_fd_sc_hd__mux2i_1 _1206_ (
    .A0(b[1]),
    .A1(a[1]),
    .S(_0040_),
    .Y(_0533_)
  );
  sky130_fd_sc_hd__nand2_1 _1207_ (
    .A(_0531_),
    .B(_0533_),
    .Y(_0534_)
  );
  sky130_fd_sc_hd__a32oi_1 _1208_ (
    .A1(_0047_),
    .A2(_0075_),
    .A3(_0098_),
    .B1(_0100_),
    .B2(_0121_),
    .Y(_0535_)
  );
  sky130_fd_sc_hd__mux2i_1 _1209_ (
    .A0(b[0]),
    .A1(a[0]),
    .S(_0040_),
    .Y(_0536_)
  );
  sky130_fd_sc_hd__o22ai_1 _1210_ (
    .A1(_0531_),
    .A2(_0533_),
    .B1(_0535_),
    .B2(_0536_),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__nand2_1 _1211_ (
    .A(_0534_),
    .B(_0537_),
    .Y(_0538_)
  );
  sky130_fd_sc_hd__a31oi_1 _1212_ (
    .A1(_0529_),
    .A2(_0534_),
    .A3(_0537_),
    .B1(_0530_),
    .Y(_0539_)
  );
  sky130_fd_sc_hd__o21ai_0 _1213_ (
    .A1(_0524_),
    .A2(_0539_),
    .B1(_0525_),
    .Y(_0540_)
  );
  sky130_fd_sc_hd__a21oi_1 _1214_ (
    .A1(_0521_),
    .A2(_0540_),
    .B1(_0518_),
    .Y(_0541_)
  );
  sky130_fd_sc_hd__maj3_1 _1215_ (
    .A(_0514_),
    .B(_0515_),
    .C(_0541_),
    .X(_0542_)
  );
  sky130_fd_sc_hd__o21bai_1 _1216_ (
    .A1(_0512_),
    .A2(_0542_),
    .B1_N(_0513_),
    .Y(_0543_)
  );
  sky130_fd_sc_hd__a21o_1 _1217_ (
    .A1(_0505_),
    .A2(_0543_),
    .B1(_0506_),
    .X(_0544_)
  );
  sky130_fd_sc_hd__maj3_1 _1218_ (
    .A(_0496_),
    .B(_0498_),
    .C(_0544_),
    .X(_0545_)
  );
  sky130_fd_sc_hd__a21o_1 _1219_ (
    .A1(_0494_),
    .A2(_0545_),
    .B1(_0495_),
    .X(_0546_)
  );
  sky130_fd_sc_hd__xor2_1 _1220_ (
    .A(a[15]),
    .B(signB),
    .X(_0547_)
  );
  sky130_fd_sc_hd__xnor2_1 _1221_ (
    .A(a[15]),
    .B(signB),
    .Y(_0548_)
  );
  sky130_fd_sc_hd__maj3_1 _1222_ (
    .A(_0488_),
    .B(_0490_),
    .C(_0546_),
    .X(_0549_)
  );
  sky130_fd_sc_hd__and2_0 _1223_ (
    .A(_0548_),
    .B(_0549_),
    .X(addsub_man[14])
  );
  sky130_fd_sc_hd__xor2_1 _1224_ (
    .A(_0488_),
    .B(_0490_),
    .X(_0550_)
  );
  sky130_fd_sc_hd__a21oi_1 _1225_ (
    .A1(_0094_),
    .A2(_0100_),
    .B1(_0515_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__xor2_1 _1226_ (
    .A(_0514_),
    .B(_0515_),
    .X(_0552_)
  );
  sky130_fd_sc_hd__clkinv_1 _1227_ (
    .A(_0552_),
    .Y(_0553_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1228_ (
    .A(_0535_),
    .SLEEP(_0536_),
    .X(_0554_)
  );
  sky130_fd_sc_hd__a22oi_1 _1229_ (
    .A1(_0100_),
    .A2(_0118_),
    .B1(_0508_),
    .B2(_0098_),
    .Y(_0555_)
  );
  sky130_fd_sc_hd__a22oi_1 _1230_ (
    .A1(_0100_),
    .A2(_0116_),
    .B1(_0502_),
    .B2(_0098_),
    .Y(_0556_)
  );
  sky130_fd_sc_hd__nand3_1 _1231_ (
    .A(_0131_),
    .B(_0555_),
    .C(_0556_),
    .Y(_0557_)
  );
  sky130_fd_sc_hd__xnor2_1 _1232_ (
    .A(_0535_),
    .B(_0536_),
    .Y(_0558_)
  );
  sky130_fd_sc_hd__nand4_1 _1233_ (
    .A(_0131_),
    .B(_0555_),
    .C(_0556_),
    .D(_0558_),
    .Y(_0559_)
  );
  sky130_fd_sc_hd__a41oi_1 _1234_ (
    .A1(_0131_),
    .A2(_0555_),
    .A3(_0556_),
    .A4(_0558_),
    .B1(_0554_),
    .Y(_0560_)
  );
  sky130_fd_sc_hd__xor2_1 _1235_ (
    .A(_0531_),
    .B(_0533_),
    .X(_0561_)
  );
  sky130_fd_sc_hd__maj3_1 _1236_ (
    .A(_0532_),
    .B(_0533_),
    .C(_0560_),
    .X(_0562_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1237_ (
    .A(_0529_),
    .SLEEP(_0530_),
    .X(_0563_)
  );
  sky130_fd_sc_hd__maj3_1 _1238_ (
    .A(_0527_),
    .B(_0528_),
    .C(_0562_),
    .X(_0564_)
  );
  sky130_fd_sc_hd__nand2b_1 _1239_ (
    .A_N(_0524_),
    .B(_0525_),
    .Y(_0565_)
  );
  sky130_fd_sc_hd__clkinv_1 _1240_ (
    .A(_0565_),
    .Y(_0566_)
  );
  sky130_fd_sc_hd__nor2_1 _1241_ (
    .A(_0564_),
    .B(_0566_),
    .Y(_0567_)
  );
  sky130_fd_sc_hd__a21oi_1 _1242_ (
    .A1(_0072_),
    .A2(_0100_),
    .B1(_0523_),
    .Y(_0568_)
  );
  sky130_fd_sc_hd__nor2_1 _1243_ (
    .A(_0520_),
    .B(_0568_),
    .Y(_0569_)
  );
  sky130_fd_sc_hd__o21ai_0 _1244_ (
    .A1(_0564_),
    .A2(_0566_),
    .B1(_0569_),
    .Y(_0570_)
  );
  sky130_fd_sc_hd__a31oi_1 _1245_ (
    .A1(_0519_),
    .A2(_0553_),
    .A3(_0570_),
    .B1(_0551_),
    .Y(_0571_)
  );
  sky130_fd_sc_hd__nor2_1 _1246_ (
    .A(_0512_),
    .B(_0513_),
    .Y(_0572_)
  );
  sky130_fd_sc_hd__maj3_1 _1247_ (
    .A(_0510_),
    .B(_0511_),
    .C(_0571_),
    .X(_0573_)
  );
  sky130_fd_sc_hd__xnor2_1 _1248_ (
    .A(_0503_),
    .B(_0504_),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__nor2_1 _1249_ (
    .A(_0573_),
    .B(_0574_),
    .Y(_0575_)
  );
  sky130_fd_sc_hd__nor2_1 _1250_ (
    .A(_0503_),
    .B(_0504_),
    .Y(_0576_)
  );
  sky130_fd_sc_hd__nor2_1 _1251_ (
    .A(_0500_),
    .B(_0576_),
    .Y(_0577_)
  );
  sky130_fd_sc_hd__o21ai_0 _1252_ (
    .A1(_0573_),
    .A2(_0574_),
    .B1(_0577_),
    .Y(_0578_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1253_ (
    .A(_0494_),
    .SLEEP(_0495_),
    .X(_0579_)
  );
  sky130_fd_sc_hd__clkinv_1 _1254_ (
    .A(_0579_),
    .Y(_0580_)
  );
  sky130_fd_sc_hd__nor2_1 _1255_ (
    .A(_0492_),
    .B(_0493_),
    .Y(_0581_)
  );
  sky130_fd_sc_hd__a31oi_1 _1256_ (
    .A1(_0499_),
    .A2(_0578_),
    .A3(_0580_),
    .B1(_0581_),
    .Y(_0582_)
  );
  sky130_fd_sc_hd__a21oi_1 _1257_ (
    .A1(_0488_),
    .A2(_0491_),
    .B1(_0548_),
    .Y(_0583_)
  );
  sky130_fd_sc_hd__o21a_1 _1258_ (
    .A1(_0550_),
    .A2(_0582_),
    .B1(_0583_),
    .X(_0584_)
  );
  sky130_fd_sc_hd__o21ai_0 _1259_ (
    .A1(_0535_),
    .A2(_0536_),
    .B1(_0548_),
    .Y(_0585_)
  );
  sky130_fd_sc_hd__o21ai_0 _1260_ (
    .A1(_0548_),
    .A2(_0560_),
    .B1(_0585_),
    .Y(_0586_)
  );
  sky130_fd_sc_hd__xnor2_1 _1261_ (
    .A(_0561_),
    .B(_0586_),
    .Y(_0587_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1262_ (
    .A(_0559_),
    .SLEEP(_0587_),
    .X(_0588_)
  );
  sky130_fd_sc_hd__nand2_1 _1263_ (
    .A(_0538_),
    .B(_0548_),
    .Y(_0589_)
  );
  sky130_fd_sc_hd__o21ai_0 _1264_ (
    .A1(_0548_),
    .A2(_0562_),
    .B1(_0589_),
    .Y(_0590_)
  );
  sky130_fd_sc_hd__xnor2_1 _1265_ (
    .A(_0563_),
    .B(_0590_),
    .Y(_0591_)
  );
  sky130_fd_sc_hd__nand2_1 _1266_ (
    .A(_0547_),
    .B(_0564_),
    .Y(_0592_)
  );
  sky130_fd_sc_hd__o21ai_0 _1267_ (
    .A1(_0539_),
    .A2(_0547_),
    .B1(_0592_),
    .Y(_0593_)
  );
  sky130_fd_sc_hd__xnor2_1 _1268_ (
    .A(_0565_),
    .B(_0593_),
    .Y(_0594_)
  );
  sky130_fd_sc_hd__or3_1 _1269_ (
    .A(_0588_),
    .B(_0591_),
    .C(_0594_),
    .X(_0595_)
  );
  sky130_fd_sc_hd__nor3_1 _1270_ (
    .A(_0548_),
    .B(_0567_),
    .C(_0568_),
    .Y(_0596_)
  );
  sky130_fd_sc_hd__a21oi_1 _1271_ (
    .A1(_0540_),
    .A2(_0548_),
    .B1(_0596_),
    .Y(_0597_)
  );
  sky130_fd_sc_hd__xnor2_1 _1272_ (
    .A(_0521_),
    .B(_0597_),
    .Y(_0598_)
  );
  sky130_fd_sc_hd__o21ai_0 _1273_ (
    .A1(_0595_),
    .A2(_0598_),
    .B1(_0584_),
    .Y(_0599_)
  );
  sky130_fd_sc_hd__nand3_1 _1274_ (
    .A(_0519_),
    .B(_0547_),
    .C(_0570_),
    .Y(_0600_)
  );
  sky130_fd_sc_hd__a21boi_0 _1275_ (
    .A1(_0541_),
    .A2(_0548_),
    .B1_N(_0600_),
    .Y(_0601_)
  );
  sky130_fd_sc_hd__xnor2_1 _1276_ (
    .A(_0552_),
    .B(_0601_),
    .Y(_0602_)
  );
  sky130_fd_sc_hd__xor2_1 _1277_ (
    .A(_0599_),
    .B(_0602_),
    .X(addsub_man[8])
  );
  sky130_fd_sc_hd__or3b_1 _1278_ (
    .A(_0595_),
    .B(_0598_),
    .C_N(_0602_),
    .X(_0603_)
  );
  sky130_fd_sc_hd__nand2_1 _1279_ (
    .A(_0584_),
    .B(_0603_),
    .Y(_0604_)
  );
  sky130_fd_sc_hd__nor2_1 _1280_ (
    .A(_0542_),
    .B(_0547_),
    .Y(_0605_)
  );
  sky130_fd_sc_hd__a21oi_1 _1281_ (
    .A1(_0547_),
    .A2(_0571_),
    .B1(_0605_),
    .Y(_0606_)
  );
  sky130_fd_sc_hd__xnor2_1 _1282_ (
    .A(_0572_),
    .B(_0606_),
    .Y(_0607_)
  );
  sky130_fd_sc_hd__xnor2_1 _1283_ (
    .A(_0604_),
    .B(_0607_),
    .Y(addsub_man[9])
  );
  sky130_fd_sc_hd__mux2i_1 _1284_ (
    .A0(_0543_),
    .A1(_0573_),
    .S(_0547_),
    .Y(_0608_)
  );
  sky130_fd_sc_hd__xnor2_1 _1285_ (
    .A(_0574_),
    .B(_0608_),
    .Y(_0609_)
  );
  sky130_fd_sc_hd__or3_1 _1286_ (
    .A(_0603_),
    .B(_0607_),
    .C(_0609_),
    .X(_0610_)
  );
  sky130_fd_sc_hd__nand2_1 _1287_ (
    .A(_0544_),
    .B(_0548_),
    .Y(_0611_)
  );
  sky130_fd_sc_hd__o31ai_1 _1288_ (
    .A1(_0548_),
    .A2(_0575_),
    .A3(_0576_),
    .B1(_0611_),
    .Y(_0612_)
  );
  sky130_fd_sc_hd__xnor2_1 _1289_ (
    .A(_0501_),
    .B(_0612_),
    .Y(_0613_)
  );
  sky130_fd_sc_hd__nor2_1 _1290_ (
    .A(_0610_),
    .B(_0613_),
    .Y(_0614_)
  );
  sky130_fd_sc_hd__o21ai_0 _1291_ (
    .A1(_0610_),
    .A2(_0613_),
    .B1(_0584_),
    .Y(_0615_)
  );
  sky130_fd_sc_hd__nor2_1 _1292_ (
    .A(_0545_),
    .B(_0547_),
    .Y(_0616_)
  );
  sky130_fd_sc_hd__a31oi_1 _1293_ (
    .A1(_0499_),
    .A2(_0547_),
    .A3(_0578_),
    .B1(_0616_),
    .Y(_0617_)
  );
  sky130_fd_sc_hd__xnor2_1 _1294_ (
    .A(_0579_),
    .B(_0617_),
    .Y(_0618_)
  );
  sky130_fd_sc_hd__xnor2_1 _1295_ (
    .A(_0580_),
    .B(_0617_),
    .Y(_0619_)
  );
  sky130_fd_sc_hd__xnor2_1 _1296_ (
    .A(_0615_),
    .B(_0619_),
    .Y(addsub_man[12])
  );
  sky130_fd_sc_hd__o31ai_1 _1297_ (
    .A1(_0610_),
    .A2(_0613_),
    .A3(_0619_),
    .B1(_0584_),
    .Y(_0620_)
  );
  sky130_fd_sc_hd__mux2_1 _1298_ (
    .A0(_0546_),
    .A1(_0582_),
    .S(_0547_),
    .X(_0621_)
  );
  sky130_fd_sc_hd__xnor2_1 _1299_ (
    .A(_0550_),
    .B(_0621_),
    .Y(_0622_)
  );
  sky130_fd_sc_hd__xor2_1 _1300_ (
    .A(_0620_),
    .B(_0622_),
    .X(addsub_man[13])
  );
  sky130_fd_sc_hd__o21ai_0 _1301_ (
    .A1(_0603_),
    .A2(_0607_),
    .B1(_0584_),
    .Y(_0623_)
  );
  sky130_fd_sc_hd__xnor2_1 _1302_ (
    .A(_0609_),
    .B(_0623_),
    .Y(addsub_man[10])
  );
  sky130_fd_sc_hd__nand2_1 _1303_ (
    .A(_0584_),
    .B(_0610_),
    .Y(_0624_)
  );
  sky130_fd_sc_hd__xnor2_1 _1304_ (
    .A(_0613_),
    .B(_0624_),
    .Y(addsub_man[11])
  );
  sky130_fd_sc_hd__o21ai_0 _1305_ (
    .A1(_0588_),
    .A2(_0591_),
    .B1(_0584_),
    .Y(_0625_)
  );
  sky130_fd_sc_hd__xnor2_1 _1306_ (
    .A(_0594_),
    .B(_0625_),
    .Y(addsub_man[6])
  );
  sky130_fd_sc_hd__nand2_1 _1307_ (
    .A(_0584_),
    .B(_0595_),
    .Y(_0626_)
  );
  sky130_fd_sc_hd__xnor2_1 _1308_ (
    .A(_0598_),
    .B(_0626_),
    .Y(addsub_man[7])
  );
  sky130_fd_sc_hd__nand2_1 _1309_ (
    .A(_0559_),
    .B(_0584_),
    .Y(_0627_)
  );
  sky130_fd_sc_hd__xnor2_1 _1310_ (
    .A(_0587_),
    .B(_0627_),
    .Y(addsub_man[4])
  );
  sky130_fd_sc_hd__nand2_1 _1311_ (
    .A(_0584_),
    .B(_0588_),
    .Y(_0628_)
  );
  sky130_fd_sc_hd__xnor2_1 _1312_ (
    .A(_0591_),
    .B(_0628_),
    .Y(addsub_man[5])
  );
  sky130_fd_sc_hd__a21oi_1 _1313_ (
    .A1(_0131_),
    .A2(_0555_),
    .B1(_0548_),
    .Y(_0629_)
  );
  sky130_fd_sc_hd__xnor2_1 _1314_ (
    .A(_0556_),
    .B(_0629_),
    .Y(addsub_man[2])
  );
  sky130_fd_sc_hd__nand2_1 _1315_ (
    .A(_0547_),
    .B(_0557_),
    .Y(_0630_)
  );
  sky130_fd_sc_hd__xor2_1 _1316_ (
    .A(_0558_),
    .B(_0630_),
    .X(addsub_man[3])
  );
  sky130_fd_sc_hd__nor2_1 _1317_ (
    .A(_0131_),
    .B(_0548_),
    .Y(_0631_)
  );
  sky130_fd_sc_hd__xnor2_1 _1318_ (
    .A(_0555_),
    .B(_0631_),
    .Y(addsub_man[1])
  );
  sky130_fd_sc_hd__and3_1 _1319_ (
    .A(A0),
    .B(B0),
    .C(signB_reg),
    .X(_0632_)
  );
  sky130_fd_sc_hd__o21ai_0 _1320_ (
    .A1(infinA),
    .A2(_0632_),
    .B1(signA_reg),
    .Y(_0633_)
  );
  sky130_fd_sc_hd__and3b_1 _1321_ (
    .A_N(infinB),
    .B(sign_reg),
    .C(_0132_),
    .X(_0634_)
  );
  sky130_fd_sc_hd__a21oi_1 _1322_ (
    .A1(infinB),
    .A2(signB_reg),
    .B1(_0634_),
    .Y(_0635_)
  );
  sky130_fd_sc_hd__o21ai_0 _1323_ (
    .A1(infinA),
    .A2(_0635_),
    .B1(_0633_),
    .Y(_0636_)
  );
  sky130_fd_sc_hd__and2_0 _1324_ (
    .A(_0475_),
    .B(_0636_),
    .X(ans[15])
  );
  sky130_fd_sc_hd__mux2i_1 _1325_ (
    .A0(a[15]),
    .A1(signB),
    .S(_0041_),
    .Y(_0637_)
  );
  sky130_fd_sc_hd__xor2_1 _1326_ (
    .A(_0584_),
    .B(_0637_),
    .X(_0638_)
  );
  sky130_fd_sc_hd__a41oi_1 _1327_ (
    .A1(_0547_),
    .A2(_0614_),
    .A3(_0618_),
    .A4(_0622_),
    .B1(_0638_),
    .Y(_0000_)
  );
  (* src = "src/fpu_FADDSUB.sv:190.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1328_ (
    .CLK(clk),
    .D(a[15]),
    .Q(signA_reg)
  );
  (* src = "src/fpu_FADDSUB.sv:190.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1329_ (
    .CLK(clk),
    .D(signB),
    .Q(signB_reg)
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1330_ (
    .CLK(clk),
    .D(_0000_),
    .Q(sign_reg)
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1331_ (
    .CLK(clk),
    .D(addsub_man[0]),
    .Q(pre_norm_man[7])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1332_ (
    .CLK(clk),
    .D(addsub_man[1]),
    .Q(pre_norm_man[8])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1333_ (
    .CLK(clk),
    .D(addsub_man[2]),
    .Q(pre_norm_man[9])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1334_ (
    .CLK(clk),
    .D(addsub_man[3]),
    .Q(pre_norm_man[10])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1335_ (
    .CLK(clk),
    .D(addsub_man[4]),
    .Q(pre_norm_man[11])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1336_ (
    .CLK(clk),
    .D(addsub_man[5]),
    .Q(pre_norm_man[12])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1337_ (
    .CLK(clk),
    .D(addsub_man[6]),
    .Q(pre_norm_man[13])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1338_ (
    .CLK(clk),
    .D(addsub_man[7]),
    .Q(pre_norm_man[14])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1339_ (
    .CLK(clk),
    .D(addsub_man[8]),
    .Q(pre_norm_man[15])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1340_ (
    .CLK(clk),
    .D(addsub_man[9]),
    .Q(pre_norm_man[16])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1341_ (
    .CLK(clk),
    .D(addsub_man[10]),
    .Q(pre_norm_man[17])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1342_ (
    .CLK(clk),
    .D(addsub_man[11]),
    .Q(pre_norm_man[18])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1343_ (
    .CLK(clk),
    .D(addsub_man[12]),
    .Q(pre_norm_man[19])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1344_ (
    .CLK(clk),
    .D(addsub_man[13]),
    .Q(pre_norm_man[20])
  );
  (* src = "src/fpu_FADDSUB.sv:74.5-78.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1345_ (
    .CLK(clk),
    .D(addsub_man[14]),
    .Q(pre_norm_man[21])
  );
  assign ans_corrected = ans;
  assign ans_calculated[15] = sign_reg;
  assign man_fixing[5:0] = 6'h00;
  assign pre_norm_man[6:0] = 7'h00;
  assign addsub_man_norm[0] = addsub_man[0];
  assign alu_smaller[0] = addsub_man[0];
  assign alu_bigger[2:0] = 3'h0;
  assign final_exp[6] = final_exp[5];
  assign man_smaller[10:0] = 11'h000;
  assign man_bigger = { alu_bigger[13:3], 11'h000 };
  assign corrected_expB[6] = corrected_expB[5];
  assign corrected_expA[6] = corrected_expA[5];
  assign init_manB[20:0] = { b[9:0], 11'h000 };
  assign init_manA[20:0] = { a[9:0], 11'h000 };
  assign init_expA = a[14:10];
  assign init_expB = b[14:10];
  assign signA = a[15];
endmodule
