/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* top =  1  *)
(* src = "src/fpu_FADDSUB.sv:3.1-224.10" *)
module addsub(a, b, clk, sub, ans);
  (* src = "src/fpu_FADDSUB.sv:4.24-4.25" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "src/fpu_FADDSUB.sv:4.26-4.27" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "src/fpu_FADDSUB.sv:5.17-5.20" *)
  input clk;
  wire clk;
  (* src = "src/fpu_FADDSUB.sv:6.17-6.20" *)
  input sub;
  wire sub;
  (* src = "src/fpu_FADDSUB.sv:7.25-7.28" *)
  output [15:0] ans;
  wire [15:0] ans;
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  wire _0000_;
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  wire _0001_;
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  wire _0002_;
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  wire _0003_;
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  wire _0004_;
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  (* src = "src/fpu_FADDSUB.sv:74.17-74.27" *)
  wire [14:0] addsub_man;
  (* src = "src/fpu_FADDSUB.sv:71.17-71.32" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [14:0] addsub_man_norm;
  (* src = "src/fpu_FADDSUB.sv:68.17-68.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13" *)
  wire [13:0] alu_bigger;
  (* src = "src/fpu_FADDSUB.sv:69.17-69.28" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13" *)
  wire [13:0] alu_smaller;
  (* src = "src/fpu_FADDSUB.sv:191.17-191.31" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [15:0] ans_calculated;
  (* src = "src/fpu_FADDSUB.sv:192.18-192.31" *)
  wire [15:0] ans_corrected;
  (* src = "src/fpu_FADDSUB.sv:38.16-38.30" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] corrected_expA;
  (* src = "src/fpu_FADDSUB.sv:39.16-39.30" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] corrected_expB;
  (* src = "src/fpu_FADDSUB.sv:64.16-64.25" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] final_exp;
  (* src = "src/fpu_FADDSUB.sv:17.21-17.27" *)
  wire infinA;
  (* src = "src/fpu_FADDSUB.sv:17.29-17.35" *)
  wire infinB;
  wire [4:0] init_expA;
  wire [4:0] init_expB;
  (* src = "src/fpu_FADDSUB.sv:35.17-35.26" *)
  (* unused_bits = "21" *)
  wire [21:0] init_manA;
  (* src = "src/fpu_FADDSUB.sv:36.17-36.26" *)
  (* unused_bits = "21" *)
  wire [21:0] init_manB;
  (* src = "src/fpu_FADDSUB.sv:45.17-45.27" *)
  (* unused_bits = "11 12 13 14 15 16 17 18 19 20 21" *)
  wire [21:0] man_bigger;
  (* src = "src/fpu_FADDSUB.sv:79.18-79.28" *)
  (* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21" *)
  wire [21:0] man_fixing;
  (* src = "src/fpu_FADDSUB.sv:47.17-47.28" *)
  (* unused_bits = "11 12 13 14 15 16 17 18 19 20 21" *)
  wire [21:0] man_smaller;
  (* src = "src/fpu_FADDSUB.sv:17.9-17.13" *)
  wire nanA;
  (* src = "src/fpu_FADDSUB.sv:17.15-17.19" *)
  wire nanB;
  (* src = "src/fpu_FADDSUB.sv:78.16-78.28" *)
  wire [21:0] pre_norm_man;
  (* src = "src/fpu_FADDSUB.sv:29.10-29.15" *)
  wire signA;
  (* src = "src/fpu_FADDSUB.sv:198.9-198.18" *)
  wire signA_reg;
  (* src = "src/fpu_FADDSUB.sv:29.30-29.35" *)
  wire signB;
  (* src = "src/fpu_FADDSUB.sv:198.20-198.29" *)
  wire signB_reg;
  (* src = "src/fpu_FADDSUB.sv:82.9-82.17" *)
  wire sign_reg;
  (* src = "src/fpu_FADDSUB.sv:66.10-66.18" *)
  wire subtract;
  (* src = "src/fpu_FADDSUB.sv:81.9-81.21" *)
  wire subtract_reg;
  (* src = "src/fpu_FADDSUB.sv:17.37-17.42" *)
  wire zeroA;
  (* src = "src/fpu_FADDSUB.sv:17.44-17.49" *)
  wire zeroB;
  sky130_fd_sc_hd__clkinv_1 _0632_ (
    .A(pre_norm_man[20]),
    .Y(_0631_)
  );
  sky130_fd_sc_hd__clkinv_1 _0633_ (
    .A(pre_norm_man[14]),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__nand2_1 _0634_ (
    .A(a[11]),
    .B(a[10]),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__nand3_1 _0635_ (
    .A(a[12]),
    .B(a[11]),
    .C(a[10]),
    .Y(_0009_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0636_ (
    .A(a[13]),
    .SLEEP(_0009_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__xor2_1 _0637_ (
    .A(a[13]),
    .B(_0009_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__nand2_1 _0638_ (
    .A(b[11]),
    .B(b[10]),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__and3_1 _0639_ (
    .A(b[11]),
    .B(b[10]),
    .C(b[12]),
    .X(_0013_)
  );
  sky130_fd_sc_hd__xnor2_1 _0640_ (
    .A(b[13]),
    .B(_0013_),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__clkinv_1 _0641_ (
    .A(_0014_),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__xor2_1 _0642_ (
    .A(_0011_),
    .B(_0014_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__xor2_1 _0643_ (
    .A(a[12]),
    .B(_0008_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__xor2_1 _0644_ (
    .A(b[12]),
    .B(_0012_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__clkinv_1 _0645_ (
    .A(_0018_),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__nor2_1 _0646_ (
    .A(b[11]),
    .B(b[10]),
    .Y(_0020_)
  );
  sky130_fd_sc_hd__nor3_1 _0647_ (
    .A(b[12]),
    .B(b[13]),
    .C(b[14]),
    .Y(_0021_)
  );
  sky130_fd_sc_hd__nand2b_1 _0648_ (
    .A_N(_0021_),
    .B(_0020_),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__and2_0 _0649_ (
    .A(_0012_),
    .B(_0022_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__nor2_1 _0650_ (
    .A(a[11]),
    .B(a[10]),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__nor3_1 _0651_ (
    .A(a[12]),
    .B(a[13]),
    .C(a[14]),
    .Y(_0025_)
  );
  sky130_fd_sc_hd__nand2b_1 _0652_ (
    .A_N(_0025_),
    .B(_0024_),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__nand2_1 _0653_ (
    .A(_0008_),
    .B(_0026_),
    .Y(_0027_)
  );
  sky130_fd_sc_hd__xnor2_1 _0654_ (
    .A(_0023_),
    .B(_0027_),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__nand2_1 _0655_ (
    .A(_0024_),
    .B(_0025_),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__a21oi_1 _0656_ (
    .A1(_0024_),
    .A2(_0025_),
    .B1(a[10]),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__nand2_1 _0657_ (
    .A(_0020_),
    .B(_0021_),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__a21oi_1 _0658_ (
    .A1(_0020_),
    .A2(_0021_),
    .B1(b[10]),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0659_ (
    .A(_0032_),
    .SLEEP(_0030_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__maj3_1 _0660_ (
    .A(_0023_),
    .B(_0027_),
    .C(_0033_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__xnor2_1 _0661_ (
    .A(_0017_),
    .B(_0018_),
    .Y(_0035_)
  );
  sky130_fd_sc_hd__maj3_1 _0662_ (
    .A(_0017_),
    .B(_0019_),
    .C(_0034_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__maj3_1 _0663_ (
    .A(_0011_),
    .B(_0015_),
    .C(_0036_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__a21o_1 _0664_ (
    .A1(b[13]),
    .A2(_0013_),
    .B1(b[14]),
    .X(_0038_)
  );
  sky130_fd_sc_hd__nand3_1 _0665_ (
    .A(b[13]),
    .B(b[14]),
    .C(_0013_),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__nand2_1 _0666_ (
    .A(_0038_),
    .B(_0039_),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__nor2_1 _0667_ (
    .A(a[14]),
    .B(_0010_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0668_ (
    .A(a[14]),
    .SLEEP(_0010_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__nand2_1 _0669_ (
    .A(a[14]),
    .B(_0010_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__nand2_1 _0670_ (
    .A(_0042_),
    .B(_0043_),
    .Y(_0044_)
  );
  sky130_fd_sc_hd__xor2_1 _0671_ (
    .A(_0040_),
    .B(_0044_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__xor2_1 _0672_ (
    .A(_0037_),
    .B(_0045_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__nand2_1 _0673_ (
    .A(_0038_),
    .B(_0041_),
    .Y(_0047_)
  );
  sky130_fd_sc_hd__o21ai_0 _0674_ (
    .A1(_0038_),
    .A2(_0041_),
    .B1(_0043_),
    .Y(_0048_)
  );
  sky130_fd_sc_hd__nand2_1 _0675_ (
    .A(_0039_),
    .B(_0048_),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__o21ai_0 _0676_ (
    .A1(_0037_),
    .A2(_0045_),
    .B1(_0049_),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__and2_0 _0677_ (
    .A(_0047_),
    .B(_0050_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__nand2_1 _0678_ (
    .A(_0047_),
    .B(_0050_),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__xnor2_1 _0679_ (
    .A(_0016_),
    .B(_0036_),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__xor2_1 _0680_ (
    .A(_0030_),
    .B(_0032_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0681_ (
    .A(_0028_),
    .SLEEP(_0054_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__a21boi_0 _0682_ (
    .A1(_0047_),
    .A2(_0050_),
    .B1_N(_0055_),
    .Y(_0056_)
  );
  sky130_fd_sc_hd__xnor2_1 _0683_ (
    .A(_0034_),
    .B(_0035_),
    .Y(_0057_)
  );
  sky130_fd_sc_hd__nor2_1 _0684_ (
    .A(_0055_),
    .B(_0057_),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__nor2_1 _0685_ (
    .A(_0051_),
    .B(_0058_),
    .Y(_0059_)
  );
  sky130_fd_sc_hd__a21oi_1 _0686_ (
    .A1(_0053_),
    .A2(_0058_),
    .B1(_0051_),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__xnor2_1 _0687_ (
    .A(_0046_),
    .B(_0060_),
    .Y(_0061_)
  );
  sky130_fd_sc_hd__xor2_1 _0688_ (
    .A(_0053_),
    .B(_0059_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__and2_0 _0689_ (
    .A(_0061_),
    .B(_0062_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__nand2_1 _0690_ (
    .A(_0061_),
    .B(_0062_),
    .Y(_0064_)
  );
  sky130_fd_sc_hd__xor2_1 _0691_ (
    .A(_0056_),
    .B(_0057_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__xnor2_1 _0692_ (
    .A(_0028_),
    .B(_0033_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__nand2b_1 _0693_ (
    .A_N(_0066_),
    .B(_0054_),
    .Y(_0067_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _0694_ (
    .A1_N(_0052_),
    .A2_N(_0066_),
    .B1(_0067_),
    .B2(_0056_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__clkinv_1 _0695_ (
    .A(_0068_),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__mux2i_1 _0696_ (
    .A0(b[0]),
    .A1(a[0]),
    .S(_0052_),
    .Y(_0070_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0697_ (
    .A(_0054_),
    .SLEEP(_0070_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__mux2i_1 _0698_ (
    .A0(b[1]),
    .A1(a[1]),
    .S(_0052_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__mux2i_1 _0699_ (
    .A0(b[2]),
    .A1(a[2]),
    .S(_0052_),
    .Y(_0073_)
  );
  sky130_fd_sc_hd__mux2i_1 _0700_ (
    .A0(_0072_),
    .A1(_0073_),
    .S(_0054_),
    .Y(_0074_)
  );
  sky130_fd_sc_hd__mux2i_1 _0701_ (
    .A0(b[3]),
    .A1(a[3]),
    .S(_0052_),
    .Y(_0075_)
  );
  sky130_fd_sc_hd__mux2i_1 _0702_ (
    .A0(b[4]),
    .A1(a[4]),
    .S(_0052_),
    .Y(_0076_)
  );
  sky130_fd_sc_hd__mux2i_1 _0703_ (
    .A0(_0075_),
    .A1(_0076_),
    .S(_0054_),
    .Y(_0077_)
  );
  sky130_fd_sc_hd__mux2i_1 _0704_ (
    .A0(_0074_),
    .A1(_0077_),
    .S(_0069_),
    .Y(_0078_)
  );
  sky130_fd_sc_hd__a21oi_1 _0705_ (
    .A1(_0069_),
    .A2(_0071_),
    .B1(_0065_),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__a21oi_1 _0706_ (
    .A1(_0065_),
    .A2(_0078_),
    .B1(_0079_),
    .Y(_0080_)
  );
  sky130_fd_sc_hd__nand2b_1 _0707_ (
    .A_N(_0062_),
    .B(_0065_),
    .Y(_0081_)
  );
  sky130_fd_sc_hd__nand3b_1 _0708_ (
    .A_N(_0062_),
    .B(_0065_),
    .C(_0055_),
    .Y(_0082_)
  );
  sky130_fd_sc_hd__nand2_1 _0709_ (
    .A(_0054_),
    .B(_0068_),
    .Y(_0083_)
  );
  sky130_fd_sc_hd__nand4b_1 _0710_ (
    .A_N(_0062_),
    .B(_0065_),
    .C(_0083_),
    .D(_0055_),
    .Y(_0084_)
  );
  sky130_fd_sc_hd__mux2i_1 _0711_ (
    .A0(_0073_),
    .A1(_0075_),
    .S(_0054_),
    .Y(_0085_)
  );
  sky130_fd_sc_hd__nand2_1 _0712_ (
    .A(_0069_),
    .B(_0074_),
    .Y(_0086_)
  );
  sky130_fd_sc_hd__mux2i_1 _0713_ (
    .A0(_0070_),
    .A1(_0072_),
    .S(_0054_),
    .Y(_0087_)
  );
  sky130_fd_sc_hd__a21oi_1 _0714_ (
    .A1(_0069_),
    .A2(_0085_),
    .B1(_0087_),
    .Y(_0088_)
  );
  sky130_fd_sc_hd__mux2i_1 _0715_ (
    .A0(_0085_),
    .A1(_0087_),
    .S(_0068_),
    .Y(_0089_)
  );
  sky130_fd_sc_hd__nand3b_1 _0716_ (
    .A_N(_0071_),
    .B(_0086_),
    .C(_0088_),
    .Y(_0090_)
  );
  sky130_fd_sc_hd__a31oi_1 _0717_ (
    .A1(_0065_),
    .A2(_0084_),
    .A3(_0090_),
    .B1(_0080_),
    .Y(_0091_)
  );
  sky130_fd_sc_hd__nand2_1 _0718_ (
    .A(_0061_),
    .B(_0084_),
    .Y(_0092_)
  );
  sky130_fd_sc_hd__mux2i_1 _0719_ (
    .A0(b[5]),
    .A1(a[5]),
    .S(_0052_),
    .Y(_0093_)
  );
  sky130_fd_sc_hd__and4_1 _0720_ (
    .A(_0073_),
    .B(_0075_),
    .C(_0076_),
    .D(_0093_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__mux2i_1 _0721_ (
    .A0(b[6]),
    .A1(a[6]),
    .S(_0052_),
    .Y(_0095_)
  );
  sky130_fd_sc_hd__mux2i_1 _0722_ (
    .A0(b[7]),
    .A1(a[7]),
    .S(_0052_),
    .Y(_0096_)
  );
  sky130_fd_sc_hd__o21ai_0 _0723_ (
    .A1(_0029_),
    .A2(_0051_),
    .B1(_0031_),
    .Y(_0097_)
  );
  sky130_fd_sc_hd__and3_1 _0724_ (
    .A(_0095_),
    .B(_0096_),
    .C(_0097_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__mux2i_1 _0725_ (
    .A0(b[8]),
    .A1(a[8]),
    .S(_0052_),
    .Y(_0099_)
  );
  sky130_fd_sc_hd__mux2i_1 _0726_ (
    .A0(b[9]),
    .A1(a[9]),
    .S(_0052_),
    .Y(_0100_)
  );
  sky130_fd_sc_hd__nand4_1 _0727_ (
    .A(_0094_),
    .B(_0098_),
    .C(_0099_),
    .D(_0100_),
    .Y(_0101_)
  );
  sky130_fd_sc_hd__a21oi_1 _0728_ (
    .A1(_0061_),
    .A2(_0081_),
    .B1(_0070_),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__a21oi_1 _0729_ (
    .A1(_0061_),
    .A2(_0082_),
    .B1(_0072_),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__a211oi_1 _0730_ (
    .A1(_0092_),
    .A2(_0101_),
    .B1(_0102_),
    .C1(_0103_),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__o21ai_0 _0731_ (
    .A1(_0064_),
    .A2(_0091_),
    .B1(_0104_),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__mux2i_1 _0732_ (
    .A0(_0093_),
    .A1(_0095_),
    .S(_0054_),
    .Y(_0106_)
  );
  sky130_fd_sc_hd__mux2i_1 _0733_ (
    .A0(_0077_),
    .A1(_0106_),
    .S(_0069_),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__mux2i_1 _0734_ (
    .A0(_0096_),
    .A1(_0099_),
    .S(_0054_),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__mux2i_1 _0735_ (
    .A0(_0100_),
    .A1(_0097_),
    .S(_0054_),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__mux2i_1 _0736_ (
    .A0(_0108_),
    .A1(_0109_),
    .S(_0069_),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__mux2i_1 _0737_ (
    .A0(_0107_),
    .A1(_0110_),
    .S(_0065_),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__mux2i_1 _0738_ (
    .A0(_0076_),
    .A1(_0093_),
    .S(_0054_),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__mux2i_1 _0739_ (
    .A0(_0085_),
    .A1(_0112_),
    .S(_0069_),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__mux2i_1 _0740_ (
    .A0(_0095_),
    .A1(_0096_),
    .S(_0054_),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__mux2i_1 _0741_ (
    .A0(_0099_),
    .A1(_0100_),
    .S(_0054_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__mux2i_1 _0742_ (
    .A0(_0114_),
    .A1(_0115_),
    .S(_0069_),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__mux2i_1 _0743_ (
    .A0(_0113_),
    .A1(_0116_),
    .S(_0065_),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__mux2i_1 _0744_ (
    .A0(_0106_),
    .A1(_0108_),
    .S(_0069_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__mux2i_1 _0745_ (
    .A0(_0078_),
    .A1(_0118_),
    .S(_0065_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__mux2i_1 _0746_ (
    .A0(_0112_),
    .A1(_0114_),
    .S(_0069_),
    .Y(_0120_)
  );
  sky130_fd_sc_hd__nor2_1 _0747_ (
    .A(_0054_),
    .B(_0097_),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__nor3_1 _0748_ (
    .A(_0054_),
    .B(_0068_),
    .C(_0097_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__a21oi_1 _0749_ (
    .A1(_0068_),
    .A2(_0115_),
    .B1(_0122_),
    .Y(_0123_)
  );
  sky130_fd_sc_hd__mux2i_1 _0750_ (
    .A0(_0120_),
    .A1(_0123_),
    .S(_0065_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__o41a_1 _0751_ (
    .A1(_0111_),
    .A2(_0117_),
    .A3(_0119_),
    .A4(_0124_),
    .B1(_0084_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__nand2_1 _0752_ (
    .A(_0068_),
    .B(_0109_),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__nand3_1 _0753_ (
    .A(_0065_),
    .B(_0068_),
    .C(_0109_),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__o21ai_0 _0754_ (
    .A1(_0065_),
    .A2(_0118_),
    .B1(_0127_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__a21oi_1 _0755_ (
    .A1(_0068_),
    .A2(_0071_),
    .B1(_0065_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__a22oi_1 _0756_ (
    .A1(_0065_),
    .A2(_0107_),
    .B1(_0129_),
    .B2(_0086_),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__a21oi_1 _0757_ (
    .A1(_0069_),
    .A2(_0087_),
    .B1(_0065_),
    .Y(_0131_)
  );
  sky130_fd_sc_hd__a21oi_1 _0758_ (
    .A1(_0065_),
    .A2(_0113_),
    .B1(_0131_),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__mux2i_1 _0759_ (
    .A0(_0089_),
    .A1(_0120_),
    .S(_0065_),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__or4_1 _0760_ (
    .A(_0080_),
    .B(_0130_),
    .C(_0132_),
    .D(_0133_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__a21oi_1 _0761_ (
    .A1(_0092_),
    .A2(_0094_),
    .B1(_0062_),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0762_ (
    .A(_0061_),
    .SLEEP(_0062_),
    .X(_0136_)
  );
  sky130_fd_sc_hd__o21a_1 _0763_ (
    .A1(_0125_),
    .A2(_0128_),
    .B1(_0136_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__a211o_1 _0764_ (
    .A1(_0134_),
    .A2(_0135_),
    .B1(_0137_),
    .C1(_0105_),
    .X(addsub_man[0])
  );
  sky130_fd_sc_hd__nand2_1 _0765_ (
    .A(zeroA),
    .B(zeroB),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__nor2_1 _0766_ (
    .A(nanA),
    .B(nanB),
    .Y(_0139_)
  );
  sky130_fd_sc_hd__nor2_1 _0767_ (
    .A(infinA),
    .B(infinB),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__nand2_1 _0768_ (
    .A(_0139_),
    .B(_0140_),
    .Y(_0141_)
  );
  sky130_fd_sc_hd__nor2_1 _0769_ (
    .A(_0138_),
    .B(_0141_),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__nor3_1 _0770_ (
    .A(pre_norm_man[20]),
    .B(pre_norm_man[21]),
    .C(pre_norm_man[19]),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__nor4_1 _0771_ (
    .A(pre_norm_man[20]),
    .B(pre_norm_man[21]),
    .C(pre_norm_man[19]),
    .D(pre_norm_man[17]),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__nor2_1 _0772_ (
    .A(pre_norm_man[18]),
    .B(pre_norm_man[16]),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__and2_0 _0773_ (
    .A(_0144_),
    .B(_0145_),
    .X(_0146_)
  );
  sky130_fd_sc_hd__and3b_1 _0774_ (
    .A_N(pre_norm_man[15]),
    .B(_0144_),
    .C(_0145_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__or4_1 _0775_ (
    .A(pre_norm_man[13]),
    .B(pre_norm_man[12]),
    .C(pre_norm_man[14]),
    .D(pre_norm_man[11]),
    .X(_0148_)
  );
  sky130_fd_sc_hd__nor4_1 _0776_ (
    .A(pre_norm_man[9]),
    .B(pre_norm_man[10]),
    .C(pre_norm_man[8]),
    .D(_0148_),
    .Y(_0149_)
  );
  sky130_fd_sc_hd__nand2_1 _0777_ (
    .A(_0147_),
    .B(_0149_),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__nor2_1 _0778_ (
    .A(pre_norm_man[7]),
    .B(_0150_),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0779_ (
    .A(pre_norm_man[7]),
    .SLEEP(_0150_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__a21oi_1 _0780_ (
    .A1(_0047_),
    .A2(_0050_),
    .B1(_0015_),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__a21oi_1 _0781_ (
    .A1(_0011_),
    .A2(_0051_),
    .B1(_0153_),
    .Y(_0154_)
  );
  sky130_fd_sc_hd__a21o_1 _0782_ (
    .A1(_0011_),
    .A2(_0051_),
    .B1(_0153_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__nor2_1 _0783_ (
    .A(pre_norm_man[15]),
    .B(pre_norm_man[14]),
    .Y(_0156_)
  );
  sky130_fd_sc_hd__nand2_1 _0784_ (
    .A(pre_norm_man[13]),
    .B(_0146_),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__nor3_1 _0785_ (
    .A(pre_norm_man[15]),
    .B(pre_norm_man[14]),
    .C(_0157_),
    .Y(_0158_)
  );
  sky130_fd_sc_hd__and3_1 _0786_ (
    .A(pre_norm_man[15]),
    .B(_0144_),
    .C(_0145_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0787_ (
    .A(_0158_),
    .SLEEP(_0159_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__nand2_1 _0788_ (
    .A(pre_norm_man[17]),
    .B(_0143_),
    .Y(_0161_)
  );
  sky130_fd_sc_hd__nor2_1 _0789_ (
    .A(pre_norm_man[18]),
    .B(_0161_),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__nor3b_1 _0790_ (
    .A(pre_norm_man[20]),
    .B(pre_norm_man[21]),
    .C_N(pre_norm_man[19]),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__or3_1 _0791_ (
    .A(_0160_),
    .B(_0162_),
    .C(_0163_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__nor2_1 _0792_ (
    .A(_0154_),
    .B(_0164_),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__nand2_1 _0793_ (
    .A(_0154_),
    .B(_0164_),
    .Y(_0166_)
  );
  sky130_fd_sc_hd__nor2b_1 _0794_ (
    .A(_0165_),
    .B_N(_0166_),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__a21oi_1 _0795_ (
    .A1(_0047_),
    .A2(_0050_),
    .B1(_0019_),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__a21oi_1 _0796_ (
    .A1(_0017_),
    .A2(_0051_),
    .B1(_0168_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__clkinv_1 _0797_ (
    .A(_0169_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0798_ (
    .A(_0147_),
    .SLEEP(_0148_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__nand2_1 _0799_ (
    .A(pre_norm_man[9]),
    .B(_0171_),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__nor2_1 _0800_ (
    .A(pre_norm_man[10]),
    .B(_0172_),
    .Y(_0173_)
  );
  sky130_fd_sc_hd__nand2_1 _0801_ (
    .A(pre_norm_man[11]),
    .B(_0156_),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__nor4b_1 _0802_ (
    .A(pre_norm_man[13]),
    .B(_0174_),
    .C(pre_norm_man[12]),
    .D_N(_0146_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nor3_1 _0803_ (
    .A(_0162_),
    .B(_0163_),
    .C(_0175_),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__o21a_1 _0804_ (
    .A1(pre_norm_man[10]),
    .A2(_0172_),
    .B1(_0176_),
    .X(_0177_)
  );
  sky130_fd_sc_hd__nand3_1 _0805_ (
    .A(_0027_),
    .B(_0047_),
    .C(_0050_),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__o21ai_0 _0806_ (
    .A1(_0023_),
    .A2(_0051_),
    .B1(_0178_),
    .Y(_0179_)
  );
  sky130_fd_sc_hd__o21a_1 _0807_ (
    .A1(_0023_),
    .A2(_0051_),
    .B1(_0178_),
    .X(_0180_)
  );
  sky130_fd_sc_hd__nand3_1 _0808_ (
    .A(pre_norm_man[7]),
    .B(_0147_),
    .C(_0149_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__and3b_1 _0809_ (
    .A_N(_0160_),
    .B(_0177_),
    .C(_0181_),
    .X(_0182_)
  );
  sky130_fd_sc_hd__nor4_1 _0810_ (
    .A(_0158_),
    .B(_0162_),
    .C(_0173_),
    .D(_0182_),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__clkinv_1 _0811_ (
    .A(_0183_),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__mux2i_1 _0812_ (
    .A0(_0030_),
    .A1(_0032_),
    .S(_0052_),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__maj3_1 _0813_ (
    .A(_0179_),
    .B(_0184_),
    .C(_0185_),
    .X(_0186_)
  );
  sky130_fd_sc_hd__xor2_1 _0814_ (
    .A(_0169_),
    .B(_0177_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__maj3_1 _0815_ (
    .A(_0170_),
    .B(_0177_),
    .C(_0186_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0816_ (
    .A(_0182_),
    .SLEEP(pre_norm_man[21]),
    .X(_0189_)
  );
  sky130_fd_sc_hd__nand2b_1 _0817_ (
    .A_N(pre_norm_man[21]),
    .B(_0182_),
    .Y(_0190_)
  );
  sky130_fd_sc_hd__xnor2_1 _0818_ (
    .A(_0167_),
    .B(_0188_),
    .Y(_0191_)
  );
  sky130_fd_sc_hd__and2_0 _0819_ (
    .A(pre_norm_man[14]),
    .B(_0147_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__nand2_1 _0820_ (
    .A(pre_norm_man[14]),
    .B(_0147_),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__xnor2_1 _0821_ (
    .A(_0169_),
    .B(_0192_),
    .Y(_0194_)
  );
  sky130_fd_sc_hd__and2_0 _0822_ (
    .A(_0180_),
    .B(_0194_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__maj3_1 _0823_ (
    .A(_0169_),
    .B(_0180_),
    .C(_0193_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__and2_0 _0824_ (
    .A(pre_norm_man[10]),
    .B(_0171_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__nand2_1 _0825_ (
    .A(pre_norm_man[10]),
    .B(_0171_),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__xnor2_1 _0826_ (
    .A(_0154_),
    .B(_0197_),
    .Y(_0199_)
  );
  sky130_fd_sc_hd__and2_0 _0827_ (
    .A(pre_norm_man[18]),
    .B(_0143_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__nor3_1 _0828_ (
    .A(_0192_),
    .B(_0197_),
    .C(_0200_),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__or3_1 _0829_ (
    .A(_0192_),
    .B(_0197_),
    .C(_0200_),
    .X(_0202_)
  );
  sky130_fd_sc_hd__o21ai_0 _0830_ (
    .A1(_0196_),
    .A2(_0199_),
    .B1(_0202_),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__a21oi_1 _0831_ (
    .A1(_0196_),
    .A2(_0199_),
    .B1(_0203_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__and2_0 _0832_ (
    .A(pre_norm_man[8]),
    .B(_0171_),
    .X(_0205_)
  );
  sky130_fd_sc_hd__nor3b_1 _0833_ (
    .A(pre_norm_man[9]),
    .B(pre_norm_man[10]),
    .C_N(_0205_),
    .Y(_0206_)
  );
  sky130_fd_sc_hd__clkinv_1 _0834_ (
    .A(_0206_),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__nand2_1 _0835_ (
    .A(pre_norm_man[16]),
    .B(_0144_),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__nor2_1 _0836_ (
    .A(pre_norm_man[18]),
    .B(_0208_),
    .Y(_0209_)
  );
  sky130_fd_sc_hd__o21ai_0 _0837_ (
    .A1(pre_norm_man[18]),
    .A2(_0208_),
    .B1(_0207_),
    .Y(_0210_)
  );
  sky130_fd_sc_hd__xnor3_1 _0838_ (
    .A(_0154_),
    .B(_0169_),
    .C(_0206_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__nand2_1 _0839_ (
    .A(_0210_),
    .B(_0211_),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__nand2_1 _0840_ (
    .A(pre_norm_man[12]),
    .B(_0146_),
    .Y(_0213_)
  );
  sky130_fd_sc_hd__nor4_1 _0841_ (
    .A(pre_norm_man[15]),
    .B(pre_norm_man[13]),
    .C(pre_norm_man[14]),
    .D(_0213_),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__nand2_1 _0842_ (
    .A(_0189_),
    .B(_0201_),
    .Y(_0215_)
  );
  sky130_fd_sc_hd__nor3_1 _0843_ (
    .A(_0210_),
    .B(_0214_),
    .C(_0215_),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__nand2_1 _0844_ (
    .A(_0154_),
    .B(_0216_),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__nand2_1 _0845_ (
    .A(_0155_),
    .B(_0214_),
    .Y(_0218_)
  );
  sky130_fd_sc_hd__nand3_1 _0846_ (
    .A(_0212_),
    .B(_0217_),
    .C(_0218_),
    .Y(_0219_)
  );
  sky130_fd_sc_hd__a211oi_1 _0847_ (
    .A1(_0190_),
    .A2(_0191_),
    .B1(_0204_),
    .C1(_0219_),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0848_ (
    .A(_0151_),
    .SLEEP(_0220_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__clkinv_1 _0849_ (
    .A(_0221_),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__xnor2_1 _0850_ (
    .A(_0186_),
    .B(_0187_),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__o21ai_0 _0851_ (
    .A1(_0180_),
    .A2(_0194_),
    .B1(_0202_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__nor2_1 _0852_ (
    .A(_0214_),
    .B(_0216_),
    .Y(_0225_)
  );
  sky130_fd_sc_hd__o21ai_0 _0853_ (
    .A1(_0214_),
    .A2(_0216_),
    .B1(_0169_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__a21boi_0 _0854_ (
    .A1(_0170_),
    .A2(_0210_),
    .B1_N(_0226_),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__o221ai_1 _0855_ (
    .A1(_0189_),
    .A2(_0223_),
    .B1(_0224_),
    .B2(_0195_),
    .C1(_0227_),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__nor2_1 _0856_ (
    .A(_0179_),
    .B(_0215_),
    .Y(_0229_)
  );
  sky130_fd_sc_hd__xnor3_1 _0857_ (
    .A(_0179_),
    .B(_0184_),
    .C(_0185_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__a221oi_1 _0858_ (
    .A1(_0179_),
    .A2(_0202_),
    .B1(_0230_),
    .B2(_0190_),
    .C1(_0229_),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__nor2_1 _0859_ (
    .A(_0151_),
    .B(_0231_),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__xnor2_1 _0860_ (
    .A(_0185_),
    .B(_0190_),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__xnor2_1 _0861_ (
    .A(_0185_),
    .B(_0189_),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__nor3_1 _0862_ (
    .A(_0151_),
    .B(_0231_),
    .C(_0234_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__and2_0 _0863_ (
    .A(_0228_),
    .B(_0235_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__nor2_1 _0864_ (
    .A(_0038_),
    .B(_0042_),
    .Y(_0237_)
  );
  sky130_fd_sc_hd__nor2_1 _0865_ (
    .A(_0044_),
    .B(_0052_),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__a31oi_1 _0866_ (
    .A1(_0038_),
    .A2(_0039_),
    .A3(_0052_),
    .B1(_0238_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__o21bai_1 _0867_ (
    .A1(_0040_),
    .A2(_0051_),
    .B1_N(_0238_),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__nand2_1 _0868_ (
    .A(_0182_),
    .B(_0239_),
    .Y(_0241_)
  );
  sky130_fd_sc_hd__nand2_1 _0869_ (
    .A(_0237_),
    .B(_0241_),
    .Y(_0242_)
  );
  sky130_fd_sc_hd__o21ai_0 _0870_ (
    .A1(_0165_),
    .A2(_0188_),
    .B1(_0166_),
    .Y(_0243_)
  );
  sky130_fd_sc_hd__nor2_1 _0871_ (
    .A(_0182_),
    .B(_0239_),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__o21ai_0 _0872_ (
    .A1(_0237_),
    .A2(_0244_),
    .B1(_0190_),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__a21oi_1 _0873_ (
    .A1(_0242_),
    .A2(_0243_),
    .B1(_0245_),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__maj3_1 _0874_ (
    .A(_0154_),
    .B(_0169_),
    .C(_0207_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__nand2_1 _0875_ (
    .A(_0210_),
    .B(_0240_),
    .Y(_0248_)
  );
  sky130_fd_sc_hd__a31oi_1 _0876_ (
    .A1(_0155_),
    .A2(_0214_),
    .A3(_0240_),
    .B1(_0151_),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__nand2_1 _0877_ (
    .A(_0189_),
    .B(_0237_),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__o211ai_1 _0878_ (
    .A1(_0247_),
    .A2(_0248_),
    .B1(_0249_),
    .C1(_0250_),
    .Y(_0251_)
  );
  sky130_fd_sc_hd__maj3_1 _0879_ (
    .A(_0154_),
    .B(_0196_),
    .C(_0198_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__nor3_1 _0880_ (
    .A(_0201_),
    .B(_0239_),
    .C(_0252_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__or3_1 _0881_ (
    .A(_0246_),
    .B(_0251_),
    .C(_0253_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0882_ (
    .A(_0241_),
    .SLEEP(_0244_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__xnor2_1 _0883_ (
    .A(_0243_),
    .B(_0255_),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__o21ai_0 _0884_ (
    .A1(_0154_),
    .A2(_0216_),
    .B1(_0239_),
    .Y(_0257_)
  );
  sky130_fd_sc_hd__o21ai_0 _0885_ (
    .A1(_0225_),
    .A2(_0257_),
    .B1(_0249_),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__and3_1 _0886_ (
    .A(_0202_),
    .B(_0239_),
    .C(_0252_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__xnor2_1 _0887_ (
    .A(_0239_),
    .B(_0247_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__a211o_1 _0888_ (
    .A1(_0210_),
    .A2(_0260_),
    .B1(_0259_),
    .C1(_0253_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__a211oi_1 _0889_ (
    .A1(_0190_),
    .A2(_0256_),
    .B1(_0258_),
    .C1(_0261_),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__nand2_1 _0890_ (
    .A(_0152_),
    .B(_0228_),
    .Y(_0263_)
  );
  sky130_fd_sc_hd__a21oi_1 _0891_ (
    .A1(_0152_),
    .A2(_0228_),
    .B1(_0235_),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__o21a_1 _0892_ (
    .A1(_0151_),
    .A2(_0220_),
    .B1(_0264_),
    .X(_0265_)
  );
  sky130_fd_sc_hd__o21ai_0 _0893_ (
    .A1(_0262_),
    .A2(_0265_),
    .B1(_0254_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__nor2_1 _0894_ (
    .A(_0151_),
    .B(_0233_),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__nand2_1 _0895_ (
    .A(_0152_),
    .B(_0234_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__nand2_1 _0896_ (
    .A(_0232_),
    .B(_0234_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__nand4_1 _0897_ (
    .A(_0220_),
    .B(_0232_),
    .C(_0234_),
    .D(_0263_),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__nor2_1 _0898_ (
    .A(_0262_),
    .B(_0270_),
    .Y(_0271_)
  );
  sky130_fd_sc_hd__nor2_1 _0899_ (
    .A(_0266_),
    .B(_0271_),
    .Y(_0272_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0900_ (
    .A(_0266_),
    .SLEEP(_0271_),
    .X(_0273_)
  );
  sky130_fd_sc_hd__o21ai_0 _0901_ (
    .A1(_0205_),
    .A2(_0214_),
    .B1(pre_norm_man[10]),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0902_ (
    .A(pre_norm_man[7]),
    .SLEEP(pre_norm_man[10]),
    .X(_0275_)
  );
  sky130_fd_sc_hd__a21oi_1 _0903_ (
    .A1(_0007_),
    .A2(pre_norm_man[11]),
    .B1(pre_norm_man[15]),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__nor2_1 _0904_ (
    .A(_0157_),
    .B(_0276_),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__a21o_1 _0905_ (
    .A1(_0631_),
    .A2(pre_norm_man[17]),
    .B1(pre_norm_man[21]),
    .X(_0278_)
  );
  sky130_fd_sc_hd__a222oi_1 _0906_ (
    .A1(pre_norm_man[15]),
    .A2(_0162_),
    .B1(_0175_),
    .B2(pre_norm_man[9]),
    .C1(_0278_),
    .C2(pre_norm_man[19]),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__a22oi_1 _0907_ (
    .A1(pre_norm_man[16]),
    .A2(_0200_),
    .B1(_0209_),
    .B2(pre_norm_man[14]),
    .Y(_0280_)
  );
  sky130_fd_sc_hd__a21oi_1 _0908_ (
    .A1(pre_norm_man[12]),
    .A2(_0192_),
    .B1(_0277_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__nand4_1 _0909_ (
    .A(_0274_),
    .B(_0279_),
    .C(_0280_),
    .D(_0281_),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__a221o_1 _0910_ (
    .A1(pre_norm_man[7]),
    .A2(_0173_),
    .B1(_0216_),
    .B2(pre_norm_man[18]),
    .C1(_0282_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__xnor2_1 _0911_ (
    .A(_0221_),
    .B(_0264_),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__clkinv_1 _0912_ (
    .A(_0284_),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__nor2_1 _0913_ (
    .A(_0273_),
    .B(_0285_),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__nand2_1 _0914_ (
    .A(_0272_),
    .B(_0284_),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__nand2_1 _0915_ (
    .A(_0231_),
    .B(_0267_),
    .Y(_0288_)
  );
  sky130_fd_sc_hd__a21oi_1 _0916_ (
    .A1(pre_norm_man[9]),
    .A2(_0171_),
    .B1(_0175_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0917_ (
    .A(pre_norm_man[10]),
    .SLEEP(_0289_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__o21ai_0 _0918_ (
    .A1(pre_norm_man[9]),
    .A2(_0275_),
    .B1(_0205_),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__o211ai_1 _0919_ (
    .A1(pre_norm_man[15]),
    .A2(pre_norm_man[13]),
    .B1(pre_norm_man[14]),
    .C1(_0146_),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__nand2_1 _0920_ (
    .A(pre_norm_man[12]),
    .B(_0158_),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__a22oi_1 _0921_ (
    .A1(pre_norm_man[20]),
    .A2(pre_norm_man[21]),
    .B1(pre_norm_man[18]),
    .B2(_0163_),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__o21ai_0 _0922_ (
    .A1(_0145_),
    .A2(_0161_),
    .B1(_0294_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__a221oi_1 _0923_ (
    .A1(pre_norm_man[15]),
    .A2(_0209_),
    .B1(_0214_),
    .B2(pre_norm_man[11]),
    .C1(_0295_),
    .Y(_0296_)
  );
  sky130_fd_sc_hd__nand4_1 _0924_ (
    .A(_0291_),
    .B(_0292_),
    .C(_0293_),
    .D(_0296_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__a211o_1 _0925_ (
    .A1(pre_norm_man[19]),
    .A2(_0216_),
    .B1(_0290_),
    .C1(_0297_),
    .X(_0298_)
  );
  sky130_fd_sc_hd__mux2i_1 _0926_ (
    .A0(_0283_),
    .A1(_0298_),
    .S(_0268_),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__a21oi_1 _0927_ (
    .A1(_0288_),
    .A2(_0299_),
    .B1(_0235_),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0928_ (
    .A1(_0262_),
    .A2(_0265_),
    .B1(_0300_),
    .C1(_0263_),
    .D1(_0254_),
    .Y(_0301_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _0929_ (
    .A1_N(_0273_),
    .A2_N(_0283_),
    .B1(_0287_),
    .B2(_0301_),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__nor2_1 _0930_ (
    .A(_0236_),
    .B(_0264_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0931_ (
    .A(_0236_),
    .SLEEP(_0264_),
    .X(_0304_)
  );
  sky130_fd_sc_hd__a21oi_1 _0932_ (
    .A1(_0231_),
    .A2(_0267_),
    .B1(_0235_),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__clkinv_1 _0933_ (
    .A(_0305_),
    .Y(_0306_)
  );
  sky130_fd_sc_hd__o21ai_0 _0934_ (
    .A1(_0233_),
    .A2(_0298_),
    .B1(_0152_),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__nor2_1 _0935_ (
    .A(_0266_),
    .B(_0307_),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__nand2_1 _0936_ (
    .A(_0268_),
    .B(_0283_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__a22oi_1 _0937_ (
    .A1(pre_norm_man[10]),
    .A2(_0158_),
    .B1(_0197_),
    .B2(pre_norm_man[7]),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__nand2_1 _0938_ (
    .A(pre_norm_man[14]),
    .B(_0162_),
    .Y(_0311_)
  );
  sky130_fd_sc_hd__a222oi_1 _0939_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[18]),
    .B1(pre_norm_man[16]),
    .B2(_0163_),
    .C1(_0209_),
    .C2(pre_norm_man[13]),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__nand2_1 _0940_ (
    .A(_0311_),
    .B(_0312_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__a21oi_1 _0941_ (
    .A1(pre_norm_man[8]),
    .A2(_0175_),
    .B1(_0313_),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__nand2b_1 _0942_ (
    .A_N(_0200_),
    .B(_0213_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__a222oi_1 _0943_ (
    .A1(pre_norm_man[11]),
    .A2(_0192_),
    .B1(_0214_),
    .B2(pre_norm_man[9]),
    .C1(_0315_),
    .C2(pre_norm_man[15]),
    .Y(_0316_)
  );
  sky130_fd_sc_hd__nand3_1 _0944_ (
    .A(_0310_),
    .B(_0314_),
    .C(_0316_),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__a21oi_1 _0945_ (
    .A1(pre_norm_man[17]),
    .A2(_0216_),
    .B1(_0317_),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__o21ai_0 _0946_ (
    .A1(_0268_),
    .A2(_0318_),
    .B1(_0309_),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__o211ai_1 _0947_ (
    .A1(_0262_),
    .A2(_0265_),
    .B1(_0319_),
    .C1(_0254_),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__nand2_1 _0948_ (
    .A(_0305_),
    .B(_0320_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__o21ai_0 _0949_ (
    .A1(_0305_),
    .A2(_0308_),
    .B1(_0321_),
    .Y(_0322_)
  );
  sky130_fd_sc_hd__o32a_1 _0950_ (
    .A1(_0287_),
    .A2(_0303_),
    .A3(_0322_),
    .B1(_0318_),
    .B2(_0272_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__nand2_1 _0951_ (
    .A(pre_norm_man[12]),
    .B(_0209_),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__nand2_1 _0952_ (
    .A(pre_norm_man[21]),
    .B(pre_norm_man[17]),
    .Y(_0325_)
  );
  sky130_fd_sc_hd__a222oi_1 _0953_ (
    .A1(pre_norm_man[13]),
    .A2(_0162_),
    .B1(_0200_),
    .B2(pre_norm_man[14]),
    .C1(_0163_),
    .C2(pre_norm_man[15]),
    .Y(_0326_)
  );
  sky130_fd_sc_hd__nand3_1 _0954_ (
    .A(_0324_),
    .B(_0325_),
    .C(_0326_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__a221oi_1 _0955_ (
    .A1(pre_norm_man[11]),
    .A2(_0159_),
    .B1(_0175_),
    .B2(pre_norm_man[7]),
    .C1(_0327_),
    .Y(_0328_)
  );
  sky130_fd_sc_hd__a222oi_1 _0956_ (
    .A1(pre_norm_man[9]),
    .A2(_0158_),
    .B1(_0192_),
    .B2(pre_norm_man[10]),
    .C1(_0214_),
    .C2(pre_norm_man[8]),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__nand2_1 _0957_ (
    .A(_0328_),
    .B(_0329_),
    .Y(_0330_)
  );
  sky130_fd_sc_hd__a21oi_1 _0958_ (
    .A1(pre_norm_man[16]),
    .A2(_0216_),
    .B1(_0330_),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__nor2_1 _0959_ (
    .A(_0272_),
    .B(_0331_),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__nor2_1 _0960_ (
    .A(_0299_),
    .B(_0305_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__mux2i_1 _0961_ (
    .A0(_0318_),
    .A1(_0331_),
    .S(_0267_),
    .Y(_0334_)
  );
  sky130_fd_sc_hd__a21oi_1 _0962_ (
    .A1(_0305_),
    .A2(_0334_),
    .B1(_0333_),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0963_ (
    .A(_0266_),
    .SLEEP(_0335_),
    .X(_0336_)
  );
  sky130_fd_sc_hd__nand2_1 _0964_ (
    .A(_0304_),
    .B(_0336_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__o21ai_0 _0965_ (
    .A1(_0266_),
    .A2(_0269_),
    .B1(_0303_),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__a31oi_1 _0966_ (
    .A1(_0286_),
    .A2(_0337_),
    .A3(_0338_),
    .B1(_0332_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__clkinv_1 _0967_ (
    .A(_0339_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__a222oi_1 _0968_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[16]),
    .B1(pre_norm_man[13]),
    .B2(_0200_),
    .C1(_0209_),
    .C2(pre_norm_man[11]),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__a222oi_1 _0969_ (
    .A1(pre_norm_man[12]),
    .A2(_0162_),
    .B1(_0163_),
    .B2(pre_norm_man[14]),
    .C1(pre_norm_man[10]),
    .C2(_0159_),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__a222oi_1 _0970_ (
    .A1(pre_norm_man[8]),
    .A2(_0158_),
    .B1(_0214_),
    .B2(pre_norm_man[7]),
    .C1(_0192_),
    .C2(pre_norm_man[9]),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__nand3_1 _0971_ (
    .A(_0341_),
    .B(_0342_),
    .C(_0343_),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__a21o_1 _0972_ (
    .A1(pre_norm_man[15]),
    .A2(_0216_),
    .B1(_0344_),
    .X(_0345_)
  );
  sky130_fd_sc_hd__nor2_1 _0973_ (
    .A(_0268_),
    .B(_0345_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__a21oi_1 _0974_ (
    .A1(_0268_),
    .A2(_0331_),
    .B1(_0346_),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__o211ai_1 _0975_ (
    .A1(_0262_),
    .A2(_0265_),
    .B1(_0347_),
    .C1(_0254_),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__mux2_1 _0976_ (
    .A0(_0320_),
    .A1(_0348_),
    .S(_0305_),
    .X(_0349_)
  );
  sky130_fd_sc_hd__nand2_1 _0977_ (
    .A(_0305_),
    .B(_0308_),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__nand2_1 _0978_ (
    .A(_0303_),
    .B(_0350_),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__a21oi_1 _0979_ (
    .A1(_0304_),
    .A2(_0349_),
    .B1(_0287_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__a22oi_1 _0980_ (
    .A1(_0273_),
    .A2(_0345_),
    .B1(_0351_),
    .B2(_0352_),
    .Y(_0353_)
  );
  sky130_fd_sc_hd__nand2_1 _0981_ (
    .A(pre_norm_man[10]),
    .B(_0216_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__nand2_1 _0982_ (
    .A(pre_norm_man[7]),
    .B(_0162_),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__a222oi_1 _0983_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[11]),
    .B1(pre_norm_man[9]),
    .B2(_0163_),
    .C1(_0200_),
    .C2(pre_norm_man[8]),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__nand3_1 _0984_ (
    .A(_0354_),
    .B(_0355_),
    .C(_0356_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__nor2_1 _0985_ (
    .A(_0268_),
    .B(_0357_),
    .Y(_0358_)
  );
  sky130_fd_sc_hd__nand2_1 _0986_ (
    .A(pre_norm_man[11]),
    .B(_0216_),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__a222oi_1 _0987_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[12]),
    .B1(pre_norm_man[10]),
    .B2(_0163_),
    .C1(_0200_),
    .C2(pre_norm_man[9]),
    .Y(_0360_)
  );
  sky130_fd_sc_hd__a22oi_1 _0988_ (
    .A1(pre_norm_man[8]),
    .A2(_0162_),
    .B1(_0209_),
    .B2(pre_norm_man[7]),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__nand3_1 _0989_ (
    .A(_0359_),
    .B(_0360_),
    .C(_0361_),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__clkinv_1 _0990_ (
    .A(_0362_),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__a21oi_1 _0991_ (
    .A1(_0268_),
    .A2(_0363_),
    .B1(_0358_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__o211ai_1 _0992_ (
    .A1(_0262_),
    .A2(_0265_),
    .B1(_0364_),
    .C1(_0254_),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__a22oi_1 _0993_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[15]),
    .B1(pre_norm_man[7]),
    .B2(_0158_),
    .Y(_0366_)
  );
  sky130_fd_sc_hd__a22oi_1 _0994_ (
    .A1(pre_norm_man[13]),
    .A2(_0163_),
    .B1(_0209_),
    .B2(pre_norm_man[10]),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__a222oi_1 _0995_ (
    .A1(pre_norm_man[11]),
    .A2(_0162_),
    .B1(_0192_),
    .B2(pre_norm_man[8]),
    .C1(_0200_),
    .C2(pre_norm_man[12]),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__nand3_1 _0996_ (
    .A(_0366_),
    .B(_0367_),
    .C(_0368_),
    .Y(_0369_)
  );
  sky130_fd_sc_hd__a221o_1 _0997_ (
    .A1(pre_norm_man[9]),
    .A2(_0159_),
    .B1(_0216_),
    .B2(pre_norm_man[14]),
    .C1(_0369_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__mux2_1 _0998_ (
    .A0(_0345_),
    .A1(_0370_),
    .S(_0267_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__mux2_1 _0999_ (
    .A0(_0334_),
    .A1(_0371_),
    .S(_0305_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__nand2_1 _1000_ (
    .A(pre_norm_man[13]),
    .B(_0216_),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__a21oi_1 _1001_ (
    .A1(pre_norm_man[7]),
    .A2(_0147_),
    .B1(pre_norm_man[21]),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__a222oi_1 _1002_ (
    .A1(pre_norm_man[11]),
    .A2(_0200_),
    .B1(_0209_),
    .B2(pre_norm_man[9]),
    .C1(pre_norm_man[10]),
    .C2(_0162_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__o21ai_0 _1003_ (
    .A1(_0007_),
    .A2(_0374_),
    .B1(_0375_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__a221oi_1 _1004_ (
    .A1(pre_norm_man[8]),
    .A2(_0159_),
    .B1(_0163_),
    .B2(pre_norm_man[12]),
    .C1(_0376_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__nand2_1 _1005_ (
    .A(_0373_),
    .B(_0377_),
    .Y(_0378_)
  );
  sky130_fd_sc_hd__nand2_1 _1006_ (
    .A(pre_norm_man[11]),
    .B(_0163_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__a22oi_1 _1007_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[13]),
    .B1(pre_norm_man[10]),
    .B2(_0200_),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__a222oi_1 _1008_ (
    .A1(pre_norm_man[9]),
    .A2(_0162_),
    .B1(_0209_),
    .B2(pre_norm_man[8]),
    .C1(pre_norm_man[7]),
    .C2(_0159_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__nand3_1 _1009_ (
    .A(_0379_),
    .B(_0380_),
    .C(_0381_),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__a21oi_1 _1010_ (
    .A1(pre_norm_man[12]),
    .A2(_0216_),
    .B1(_0382_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__nand2_1 _1011_ (
    .A(_0268_),
    .B(_0378_),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__o21ai_0 _1012_ (
    .A1(_0268_),
    .A2(_0383_),
    .B1(_0384_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__a22oi_1 _1013_ (
    .A1(_0303_),
    .A2(_0372_),
    .B1(_0385_),
    .B2(_0306_),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__o221ai_1 _1014_ (
    .A1(_0221_),
    .A2(_0301_),
    .B1(_0306_),
    .B2(_0365_),
    .C1(_0386_),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__mux2_1 _1015_ (
    .A0(_0357_),
    .A1(_0387_),
    .S(_0272_),
    .X(_0388_)
  );
  sky130_fd_sc_hd__mux2_1 _1016_ (
    .A0(_0370_),
    .A1(_0378_),
    .S(_0267_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__o211ai_1 _1017_ (
    .A1(_0262_),
    .A2(_0265_),
    .B1(_0389_),
    .C1(_0254_),
    .Y(_0390_)
  );
  sky130_fd_sc_hd__nor2_1 _1018_ (
    .A(_0268_),
    .B(_0362_),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__a21oi_1 _1019_ (
    .A1(_0268_),
    .A2(_0383_),
    .B1(_0391_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__o211ai_1 _1020_ (
    .A1(_0262_),
    .A2(_0265_),
    .B1(_0392_),
    .C1(_0254_),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__mux2i_1 _1021_ (
    .A0(_0390_),
    .A1(_0393_),
    .S(_0305_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__mux2i_1 _1022_ (
    .A0(_0371_),
    .A1(_0385_),
    .S(_0305_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__nor2_1 _1023_ (
    .A(_0266_),
    .B(_0395_),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__o31a_1 _1024_ (
    .A1(_0221_),
    .A2(_0394_),
    .A3(_0396_),
    .B1(_0303_),
    .X(_0397_)
  );
  sky130_fd_sc_hd__a21oi_1 _1025_ (
    .A1(_0336_),
    .A2(_0349_),
    .B1(_0284_),
    .Y(_0398_)
  );
  sky130_fd_sc_hd__nand2_1 _1026_ (
    .A(pre_norm_man[8]),
    .B(_0163_),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__a222oi_1 _1027_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[10]),
    .B1(pre_norm_man[7]),
    .B2(_0200_),
    .C1(_0216_),
    .C2(pre_norm_man[9]),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__nand2_1 _1028_ (
    .A(_0399_),
    .B(_0400_),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__mux2i_1 _1029_ (
    .A0(_0357_),
    .A1(_0401_),
    .S(_0267_),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__a21oi_1 _1030_ (
    .A1(_0365_),
    .A2(_0402_),
    .B1(_0305_),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__a22o_1 _1031_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[8]),
    .B1(pre_norm_man[7]),
    .B2(_0216_),
    .X(_0404_)
  );
  sky130_fd_sc_hd__a222oi_1 _1032_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[9]),
    .B1(pre_norm_man[7]),
    .B2(_0163_),
    .C1(_0216_),
    .C2(pre_norm_man[8]),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__a21oi_1 _1033_ (
    .A1(_0399_),
    .A2(_0400_),
    .B1(_0267_),
    .Y(_0406_)
  );
  sky130_fd_sc_hd__nor3b_1 _1034_ (
    .A(_0404_),
    .B(_0406_),
    .C_N(_0405_),
    .Y(_0407_)
  );
  sky130_fd_sc_hd__or3b_1 _1035_ (
    .A(_0266_),
    .B(_0403_),
    .C_N(_0407_),
    .X(_0408_)
  );
  sky130_fd_sc_hd__o31a_1 _1036_ (
    .A1(_0397_),
    .A2(_0398_),
    .A3(_0408_),
    .B1(_0272_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__a21oi_1 _1037_ (
    .A1(pre_norm_man[21]),
    .A2(pre_norm_man[7]),
    .B1(_0404_),
    .Y(_0410_)
  );
  sky130_fd_sc_hd__o21ai_0 _1038_ (
    .A1(_0272_),
    .A2(_0405_),
    .B1(_0410_),
    .Y(_0411_)
  );
  sky130_fd_sc_hd__o22a_1 _1039_ (
    .A1(_0272_),
    .A2(_0401_),
    .B1(_0411_),
    .B2(_0388_),
    .X(_0412_)
  );
  sky130_fd_sc_hd__o2111ai_1 _1040_ (
    .A1(_0305_),
    .A2(_0308_),
    .B1(_0321_),
    .C1(_0304_),
    .D1(_0285_),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__mux2i_1 _1041_ (
    .A0(_0348_),
    .A1(_0390_),
    .S(_0305_),
    .Y(_0414_)
  );
  sky130_fd_sc_hd__nor2_1 _1042_ (
    .A(_0305_),
    .B(_0393_),
    .Y(_0415_)
  );
  sky130_fd_sc_hd__nor2_1 _1043_ (
    .A(_0306_),
    .B(_0402_),
    .Y(_0416_)
  );
  sky130_fd_sc_hd__a2111oi_0 _1044_ (
    .A1(_0303_),
    .A2(_0414_),
    .B1(_0415_),
    .C1(_0416_),
    .D1(_0273_),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__nand2_1 _1045_ (
    .A(_0413_),
    .B(_0417_),
    .Y(_0418_)
  );
  sky130_fd_sc_hd__o21a_1 _1046_ (
    .A1(_0409_),
    .A2(_0412_),
    .B1(_0418_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__o211a_1 _1047_ (
    .A1(_0409_),
    .A2(_0412_),
    .B1(_0418_),
    .C1(_0388_),
    .X(_0420_)
  );
  sky130_fd_sc_hd__a31oi_1 _1048_ (
    .A1(_0304_),
    .A2(_0305_),
    .A3(_0308_),
    .B1(_0273_),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__nand2_1 _1049_ (
    .A(_0304_),
    .B(_0394_),
    .Y(_0422_)
  );
  sky130_fd_sc_hd__o221ai_1 _1050_ (
    .A1(_0304_),
    .A2(_0349_),
    .B1(_0421_),
    .B2(_0286_),
    .C1(_0422_),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__a21boi_0 _1051_ (
    .A1(_0273_),
    .A2(_0363_),
    .B1_N(_0423_),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__nor3_1 _1052_ (
    .A(_0266_),
    .B(_0269_),
    .C(_0284_),
    .Y(_0425_)
  );
  sky130_fd_sc_hd__nand2_1 _1053_ (
    .A(_0303_),
    .B(_0335_),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__o311ai_0 _1054_ (
    .A1(_0303_),
    .A2(_0396_),
    .A3(_0425_),
    .B1(_0426_),
    .C1(_0272_),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__o21ai_0 _1055_ (
    .A1(_0272_),
    .A2(_0383_),
    .B1(_0427_),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__and3_1 _1056_ (
    .A(_0420_),
    .B(_0424_),
    .C(_0428_),
    .X(_0429_)
  );
  sky130_fd_sc_hd__nor2_1 _1057_ (
    .A(_0303_),
    .B(_0414_),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__a211oi_1 _1058_ (
    .A1(_0303_),
    .A2(_0322_),
    .B1(_0430_),
    .C1(_0273_),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__a21oi_1 _1059_ (
    .A1(_0273_),
    .A2(_0378_),
    .B1(_0431_),
    .Y(_0432_)
  );
  sky130_fd_sc_hd__clkinv_1 _1060_ (
    .A(_0432_),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__nand2_1 _1061_ (
    .A(_0429_),
    .B(_0433_),
    .Y(_0434_)
  );
  sky130_fd_sc_hd__and2_0 _1062_ (
    .A(_0304_),
    .B(_0372_),
    .X(_0435_)
  );
  sky130_fd_sc_hd__a211o_1 _1063_ (
    .A1(_0300_),
    .A2(_0303_),
    .B1(_0435_),
    .C1(_0273_),
    .X(_0436_)
  );
  sky130_fd_sc_hd__o21ai_0 _1064_ (
    .A1(_0272_),
    .A2(_0370_),
    .B1(_0436_),
    .Y(_0437_)
  );
  sky130_fd_sc_hd__nor2_1 _1065_ (
    .A(_0434_),
    .B(_0437_),
    .Y(_0438_)
  );
  sky130_fd_sc_hd__nor4b_1 _1066_ (
    .A(_0353_),
    .B(_0437_),
    .C(_0432_),
    .D_N(_0429_),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__nand2_1 _1067_ (
    .A(_0340_),
    .B(_0439_),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__nor2_1 _1068_ (
    .A(_0323_),
    .B(_0440_),
    .Y(_0441_)
  );
  sky130_fd_sc_hd__nand4b_1 _1069_ (
    .A_N(_0323_),
    .B(_0439_),
    .C(_0340_),
    .D(_0302_),
    .Y(_0442_)
  );
  sky130_fd_sc_hd__nor2_1 _1070_ (
    .A(_0287_),
    .B(_0421_),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__a21oi_1 _1071_ (
    .A1(_0273_),
    .A2(_0298_),
    .B1(_0443_),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__nor2_1 _1072_ (
    .A(_0442_),
    .B(_0444_),
    .Y(_0445_)
  );
  sky130_fd_sc_hd__nor3_1 _1073_ (
    .A(_0272_),
    .B(_0442_),
    .C(_0444_),
    .Y(_0446_)
  );
  sky130_fd_sc_hd__nand2_1 _1074_ (
    .A(_0236_),
    .B(_0446_),
    .Y(_0447_)
  );
  sky130_fd_sc_hd__and3_1 _1075_ (
    .A(_0222_),
    .B(_0236_),
    .C(_0446_),
    .X(_0448_)
  );
  sky130_fd_sc_hd__nor2b_1 _1076_ (
    .A(_0254_),
    .B_N(_0262_),
    .Y(_0449_)
  );
  sky130_fd_sc_hd__o21ai_0 _1077_ (
    .A1(_0442_),
    .A2(_0444_),
    .B1(_0273_),
    .Y(_0450_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _1078_ (
    .A1_N(_0306_),
    .A2_N(_0446_),
    .B1(_0450_),
    .B2(_0232_),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__nand2_1 _1079_ (
    .A(_0268_),
    .B(_0450_),
    .Y(_0452_)
  );
  sky130_fd_sc_hd__o21ai_0 _1080_ (
    .A1(_0268_),
    .A2(_0446_),
    .B1(_0452_),
    .Y(_0453_)
  );
  sky130_fd_sc_hd__nand2_1 _1081_ (
    .A(_0451_),
    .B(_0453_),
    .Y(_0454_)
  );
  sky130_fd_sc_hd__nor2_1 _1082_ (
    .A(_0263_),
    .B(_0450_),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__a21oi_1 _1083_ (
    .A1(_0303_),
    .A2(_0446_),
    .B1(_0455_),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__nand2_1 _1084_ (
    .A(_0222_),
    .B(_0266_),
    .Y(_0457_)
  );
  sky130_fd_sc_hd__a21o_1 _1085_ (
    .A1(_0447_),
    .A2(_0457_),
    .B1(_0448_),
    .X(_0458_)
  );
  sky130_fd_sc_hd__nand4_1 _1086_ (
    .A(_0451_),
    .B(_0453_),
    .C(_0456_),
    .D(_0458_),
    .Y(_0459_)
  );
  sky130_fd_sc_hd__o21ai_0 _1087_ (
    .A1(_0448_),
    .A2(_0449_),
    .B1(_0459_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__a311oi_1 _1088_ (
    .A1(_0222_),
    .A2(_0236_),
    .A3(_0446_),
    .B1(_0262_),
    .C1(_0254_),
    .Y(_0461_)
  );
  sky130_fd_sc_hd__a21oi_1 _1089_ (
    .A1(_0448_),
    .A2(_0449_),
    .B1(_0461_),
    .Y(_0462_)
  );
  sky130_fd_sc_hd__nor2b_1 _1090_ (
    .A(_0141_),
    .B_N(_0462_),
    .Y(_0463_)
  );
  sky130_fd_sc_hd__a21oi_1 _1091_ (
    .A1(_0460_),
    .A2(_0463_),
    .B1(_0142_),
    .Y(ans[14])
  );
  sky130_fd_sc_hd__a31o_1 _1092_ (
    .A1(_0451_),
    .A2(_0453_),
    .A3(_0456_),
    .B1(_0458_),
    .X(_0464_)
  );
  sky130_fd_sc_hd__a31oi_1 _1093_ (
    .A1(_0459_),
    .A2(_0463_),
    .A3(_0464_),
    .B1(_0142_),
    .Y(ans[13])
  );
  sky130_fd_sc_hd__xnor2_1 _1094_ (
    .A(_0454_),
    .B(_0456_),
    .Y(_0465_)
  );
  sky130_fd_sc_hd__a21oi_1 _1095_ (
    .A1(_0463_),
    .A2(_0465_),
    .B1(_0142_),
    .Y(ans[12])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1096_ (
    .A(_0451_),
    .SLEEP(_0453_),
    .X(_0466_)
  );
  sky130_fd_sc_hd__a31oi_1 _1097_ (
    .A1(_0454_),
    .A2(_0463_),
    .A3(_0466_),
    .B1(_0142_),
    .Y(ans[11])
  );
  sky130_fd_sc_hd__o21ai_0 _1098_ (
    .A1(_0273_),
    .A2(_0445_),
    .B1(_0453_),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__a21oi_1 _1099_ (
    .A1(_0463_),
    .A2(_0467_),
    .B1(_0142_),
    .Y(ans[10])
  );
  sky130_fd_sc_hd__a311oi_1 _1100_ (
    .A1(infinA),
    .A2(infinB),
    .A3(subtract_reg),
    .B1(nanB),
    .C1(nanA),
    .Y(_0468_)
  );
  sky130_fd_sc_hd__nand2_1 _1101_ (
    .A(_0442_),
    .B(_0444_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__nand4_1 _1102_ (
    .A(_0138_),
    .B(_0140_),
    .C(_0462_),
    .D(_0469_),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__o21ai_0 _1103_ (
    .A1(_0445_),
    .A2(_0470_),
    .B1(_0468_),
    .Y(ans[9])
  );
  sky130_fd_sc_hd__nand2_1 _1104_ (
    .A(_0138_),
    .B(_0463_),
    .Y(_0471_)
  );
  sky130_fd_sc_hd__xnor2_1 _1105_ (
    .A(_0302_),
    .B(_0441_),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__nor2_1 _1106_ (
    .A(_0471_),
    .B(_0472_),
    .Y(ans[8])
  );
  sky130_fd_sc_hd__nand2_1 _1107_ (
    .A(_0323_),
    .B(_0440_),
    .Y(_0473_)
  );
  sky130_fd_sc_hd__nor3b_1 _1108_ (
    .A(_0441_),
    .B(_0471_),
    .C_N(_0473_),
    .Y(ans[7])
  );
  sky130_fd_sc_hd__nor2_1 _1109_ (
    .A(_0340_),
    .B(_0439_),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__nor3b_1 _1110_ (
    .A(_0471_),
    .B(_0474_),
    .C_N(_0440_),
    .Y(ans[6])
  );
  sky130_fd_sc_hd__xor2_1 _1111_ (
    .A(_0353_),
    .B(_0438_),
    .X(_0475_)
  );
  sky130_fd_sc_hd__nor2_1 _1112_ (
    .A(_0471_),
    .B(_0475_),
    .Y(ans[5])
  );
  sky130_fd_sc_hd__and2_0 _1113_ (
    .A(_0434_),
    .B(_0437_),
    .X(_0476_)
  );
  sky130_fd_sc_hd__nor3_1 _1114_ (
    .A(_0438_),
    .B(_0471_),
    .C(_0476_),
    .Y(ans[4])
  );
  sky130_fd_sc_hd__xnor2_1 _1115_ (
    .A(_0429_),
    .B(_0433_),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__nor2_1 _1116_ (
    .A(_0471_),
    .B(_0477_),
    .Y(ans[3])
  );
  sky130_fd_sc_hd__a21oi_1 _1117_ (
    .A1(_0420_),
    .A2(_0424_),
    .B1(_0428_),
    .Y(_0478_)
  );
  sky130_fd_sc_hd__nor3_1 _1118_ (
    .A(_0429_),
    .B(_0471_),
    .C(_0478_),
    .Y(ans[2])
  );
  sky130_fd_sc_hd__xnor2_1 _1119_ (
    .A(_0420_),
    .B(_0424_),
    .Y(_0479_)
  );
  sky130_fd_sc_hd__nor2_1 _1120_ (
    .A(_0471_),
    .B(_0479_),
    .Y(ans[1])
  );
  sky130_fd_sc_hd__nor2_1 _1121_ (
    .A(_0388_),
    .B(_0419_),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__nor3_1 _1122_ (
    .A(_0420_),
    .B(_0471_),
    .C(_0480_),
    .Y(ans[0])
  );
  sky130_fd_sc_hd__xor2_1 _1123_ (
    .A(b[15]),
    .B(sub),
    .X(signB)
  );
  sky130_fd_sc_hd__xnor2_1 _1124_ (
    .A(a[15]),
    .B(signB),
    .Y(_0481_)
  );
  sky130_fd_sc_hd__clkinv_1 _1125_ (
    .A(_0481_),
    .Y(subtract)
  );
  sky130_fd_sc_hd__nor4_1 _1126_ (
    .A(_0054_),
    .B(_0065_),
    .C(_0069_),
    .D(_0097_),
    .Y(_0482_)
  );
  sky130_fd_sc_hd__nand2_1 _1127_ (
    .A(_0063_),
    .B(_0482_),
    .Y(_0483_)
  );
  sky130_fd_sc_hd__o211ai_1 _1128_ (
    .A1(_0029_),
    .A2(_0052_),
    .B1(_0063_),
    .C1(_0482_),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__nor2_1 _1129_ (
    .A(_0065_),
    .B(_0126_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__nor3_1 _1130_ (
    .A(_0064_),
    .B(_0065_),
    .C(_0126_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__nand2_1 _1131_ (
    .A(_0063_),
    .B(_0485_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__mux2i_1 _1132_ (
    .A0(b[9]),
    .A1(a[9]),
    .S(_0051_),
    .Y(_0488_)
  );
  sky130_fd_sc_hd__nand2_1 _1133_ (
    .A(_0487_),
    .B(_0488_),
    .Y(_0489_)
  );
  sky130_fd_sc_hd__nor2_1 _1134_ (
    .A(_0487_),
    .B(_0488_),
    .Y(_0490_)
  );
  sky130_fd_sc_hd__nor2_1 _1135_ (
    .A(_0065_),
    .B(_0123_),
    .Y(_0491_)
  );
  sky130_fd_sc_hd__nor3_1 _1136_ (
    .A(_0064_),
    .B(_0065_),
    .C(_0123_),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__mux2i_1 _1137_ (
    .A0(b[8]),
    .A1(a[8]),
    .S(_0051_),
    .Y(_0493_)
  );
  sky130_fd_sc_hd__clkinv_1 _1138_ (
    .A(_0493_),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__nor2_1 _1139_ (
    .A(_0065_),
    .B(_0110_),
    .Y(_0495_)
  );
  sky130_fd_sc_hd__nor3_1 _1140_ (
    .A(_0064_),
    .B(_0065_),
    .C(_0110_),
    .Y(_0496_)
  );
  sky130_fd_sc_hd__mux2i_1 _1141_ (
    .A0(b[7]),
    .A1(a[7]),
    .S(_0051_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1142_ (
    .A(_0497_),
    .SLEEP(_0496_),
    .X(_0498_)
  );
  sky130_fd_sc_hd__nand2b_1 _1143_ (
    .A_N(_0497_),
    .B(_0496_),
    .Y(_0499_)
  );
  sky130_fd_sc_hd__nor2_1 _1144_ (
    .A(_0065_),
    .B(_0116_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__a31o_1 _1145_ (
    .A1(_0065_),
    .A2(_0068_),
    .A3(_0121_),
    .B1(_0500_),
    .X(_0501_)
  );
  sky130_fd_sc_hd__and2_0 _1146_ (
    .A(_0063_),
    .B(_0501_),
    .X(_0502_)
  );
  sky130_fd_sc_hd__clkinv_1 _1147_ (
    .A(_0502_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__mux2i_1 _1148_ (
    .A0(b[6]),
    .A1(a[6]),
    .S(_0051_),
    .Y(_0504_)
  );
  sky130_fd_sc_hd__nand2_1 _1149_ (
    .A(_0063_),
    .B(_0128_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__clkinv_1 _1150_ (
    .A(_0505_),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__mux2i_1 _1151_ (
    .A0(b[5]),
    .A1(a[5]),
    .S(_0051_),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__nand2_1 _1152_ (
    .A(_0063_),
    .B(_0124_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__clkinv_1 _1153_ (
    .A(_0508_),
    .Y(_0509_)
  );
  sky130_fd_sc_hd__mux2i_1 _1154_ (
    .A0(b[4]),
    .A1(a[4]),
    .S(_0051_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__nand2_1 _1155_ (
    .A(_0508_),
    .B(_0510_),
    .Y(_0511_)
  );
  sky130_fd_sc_hd__nor2_1 _1156_ (
    .A(_0508_),
    .B(_0510_),
    .Y(_0512_)
  );
  sky130_fd_sc_hd__nand2_1 _1157_ (
    .A(_0063_),
    .B(_0111_),
    .Y(_0513_)
  );
  sky130_fd_sc_hd__clkinv_1 _1158_ (
    .A(_0513_),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__mux2i_1 _1159_ (
    .A0(b[3]),
    .A1(a[3]),
    .S(_0051_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__a22oi_1 _1160_ (
    .A1(_0063_),
    .A2(_0117_),
    .B1(_0136_),
    .B2(_0482_),
    .Y(_0516_)
  );
  sky130_fd_sc_hd__clkinv_1 _1161_ (
    .A(_0516_),
    .Y(_0517_)
  );
  sky130_fd_sc_hd__mux2i_1 _1162_ (
    .A0(b[2]),
    .A1(a[2]),
    .S(_0051_),
    .Y(_0518_)
  );
  sky130_fd_sc_hd__a22oi_1 _1163_ (
    .A1(_0063_),
    .A2(_0119_),
    .B1(_0136_),
    .B2(_0485_),
    .Y(_0519_)
  );
  sky130_fd_sc_hd__mux2i_1 _1164_ (
    .A0(b[1]),
    .A1(a[1]),
    .S(_0051_),
    .Y(_0520_)
  );
  sky130_fd_sc_hd__nand2_1 _1165_ (
    .A(_0519_),
    .B(_0520_),
    .Y(_0521_)
  );
  sky130_fd_sc_hd__nor2_1 _1166_ (
    .A(_0519_),
    .B(_0520_),
    .Y(_0522_)
  );
  sky130_fd_sc_hd__a22oi_1 _1167_ (
    .A1(_0063_),
    .A2(_0133_),
    .B1(_0136_),
    .B2(_0491_),
    .Y(_0523_)
  );
  sky130_fd_sc_hd__mux2i_1 _1168_ (
    .A0(b[0]),
    .A1(a[0]),
    .S(_0051_),
    .Y(_0524_)
  );
  sky130_fd_sc_hd__nor2_1 _1169_ (
    .A(_0523_),
    .B(_0524_),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__a21oi_1 _1170_ (
    .A1(_0521_),
    .A2(_0525_),
    .B1(_0522_),
    .Y(_0526_)
  );
  sky130_fd_sc_hd__maj3_1 _1171_ (
    .A(_0516_),
    .B(_0518_),
    .C(_0526_),
    .X(_0527_)
  );
  sky130_fd_sc_hd__o21a_1 _1172_ (
    .A1(_0513_),
    .A2(_0515_),
    .B1(_0527_),
    .X(_0528_)
  );
  sky130_fd_sc_hd__a21oi_1 _1173_ (
    .A1(_0513_),
    .A2(_0515_),
    .B1(_0528_),
    .Y(_0529_)
  );
  sky130_fd_sc_hd__a21oi_1 _1174_ (
    .A1(_0511_),
    .A2(_0529_),
    .B1(_0512_),
    .Y(_0530_)
  );
  sky130_fd_sc_hd__maj3_1 _1175_ (
    .A(_0505_),
    .B(_0507_),
    .C(_0530_),
    .X(_0531_)
  );
  sky130_fd_sc_hd__maj3_1 _1176_ (
    .A(_0503_),
    .B(_0504_),
    .C(_0531_),
    .X(_0532_)
  );
  sky130_fd_sc_hd__o21ai_0 _1177_ (
    .A1(_0498_),
    .A2(_0532_),
    .B1(_0499_),
    .Y(_0533_)
  );
  sky130_fd_sc_hd__maj3_1 _1178_ (
    .A(_0492_),
    .B(_0494_),
    .C(_0533_),
    .X(_0534_)
  );
  sky130_fd_sc_hd__a21oi_1 _1179_ (
    .A1(_0489_),
    .A2(_0534_),
    .B1(_0490_),
    .Y(_0535_)
  );
  sky130_fd_sc_hd__nand4_1 _1180_ (
    .A(_0024_),
    .B(_0025_),
    .C(_0051_),
    .D(_0483_),
    .Y(_0536_)
  );
  sky130_fd_sc_hd__nand2_1 _1181_ (
    .A(_0481_),
    .B(_0536_),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__a21oi_1 _1182_ (
    .A1(_0484_),
    .A2(_0535_),
    .B1(_0537_),
    .Y(addsub_man[14])
  );
  sky130_fd_sc_hd__xnor2_1 _1183_ (
    .A(_0492_),
    .B(_0494_),
    .Y(_0538_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1184_ (
    .A(_0519_),
    .SLEEP(_0520_),
    .X(_0539_)
  );
  sky130_fd_sc_hd__nand2b_1 _1185_ (
    .A_N(_0524_),
    .B(_0523_),
    .Y(_0540_)
  );
  sky130_fd_sc_hd__a22o_1 _1186_ (
    .A1(_0063_),
    .A2(_0132_),
    .B1(_0136_),
    .B2(_0501_),
    .X(_0541_)
  );
  sky130_fd_sc_hd__nor2_1 _1187_ (
    .A(addsub_man[0]),
    .B(_0541_),
    .Y(_0542_)
  );
  sky130_fd_sc_hd__a22oi_1 _1188_ (
    .A1(_0063_),
    .A2(_0130_),
    .B1(_0136_),
    .B2(_0495_),
    .Y(_0543_)
  );
  sky130_fd_sc_hd__clkinv_1 _1189_ (
    .A(_0543_),
    .Y(_0544_)
  );
  sky130_fd_sc_hd__xnor2_1 _1190_ (
    .A(_0523_),
    .B(_0524_),
    .Y(_0545_)
  );
  sky130_fd_sc_hd__clkinv_1 _1191_ (
    .A(_0545_),
    .Y(_0546_)
  );
  sky130_fd_sc_hd__nand3_1 _1192_ (
    .A(_0542_),
    .B(_0543_),
    .C(_0545_),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__o41ai_1 _1193_ (
    .A1(addsub_man[0]),
    .A2(_0541_),
    .A3(_0544_),
    .A4(_0546_),
    .B1(_0540_),
    .Y(_0548_)
  );
  sky130_fd_sc_hd__xnor2_1 _1194_ (
    .A(_0519_),
    .B(_0520_),
    .Y(_0549_)
  );
  sky130_fd_sc_hd__a21oi_1 _1195_ (
    .A1(_0548_),
    .A2(_0549_),
    .B1(_0539_),
    .Y(_0550_)
  );
  sky130_fd_sc_hd__xnor2_1 _1196_ (
    .A(_0516_),
    .B(_0518_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__maj3_1 _1197_ (
    .A(_0517_),
    .B(_0518_),
    .C(_0550_),
    .X(_0552_)
  );
  sky130_fd_sc_hd__xnor2_1 _1198_ (
    .A(_0513_),
    .B(_0515_),
    .Y(_0553_)
  );
  sky130_fd_sc_hd__maj3_1 _1199_ (
    .A(_0514_),
    .B(_0515_),
    .C(_0552_),
    .X(_0554_)
  );
  sky130_fd_sc_hd__xnor2_1 _1200_ (
    .A(_0508_),
    .B(_0510_),
    .Y(_0555_)
  );
  sky130_fd_sc_hd__maj3_1 _1201_ (
    .A(_0509_),
    .B(_0510_),
    .C(_0554_),
    .X(_0556_)
  );
  sky130_fd_sc_hd__xnor2_1 _1202_ (
    .A(_0505_),
    .B(_0507_),
    .Y(_0557_)
  );
  sky130_fd_sc_hd__maj3_1 _1203_ (
    .A(_0506_),
    .B(_0507_),
    .C(_0556_),
    .X(_0558_)
  );
  sky130_fd_sc_hd__xnor2_1 _1204_ (
    .A(_0502_),
    .B(_0504_),
    .Y(_0559_)
  );
  sky130_fd_sc_hd__maj3_1 _1205_ (
    .A(_0502_),
    .B(_0504_),
    .C(_0558_),
    .X(_0560_)
  );
  sky130_fd_sc_hd__nor2b_1 _1206_ (
    .A(_0498_),
    .B_N(_0499_),
    .Y(_0561_)
  );
  sky130_fd_sc_hd__maj3_1 _1207_ (
    .A(_0496_),
    .B(_0497_),
    .C(_0560_),
    .X(_0562_)
  );
  sky130_fd_sc_hd__mux2i_1 _1208_ (
    .A0(_0533_),
    .A1(_0562_),
    .S(subtract),
    .Y(_0563_)
  );
  sky130_fd_sc_hd__xnor2_1 _1209_ (
    .A(_0538_),
    .B(_0563_),
    .Y(_0564_)
  );
  sky130_fd_sc_hd__nand2_1 _1210_ (
    .A(_0481_),
    .B(_0525_),
    .Y(_0565_)
  );
  sky130_fd_sc_hd__o21ai_0 _1211_ (
    .A1(_0481_),
    .A2(_0548_),
    .B1(_0565_),
    .Y(_0566_)
  );
  sky130_fd_sc_hd__xnor2_1 _1212_ (
    .A(_0549_),
    .B(_0566_),
    .Y(_0567_)
  );
  sky130_fd_sc_hd__nor2_1 _1213_ (
    .A(_0547_),
    .B(_0567_),
    .Y(_0568_)
  );
  sky130_fd_sc_hd__nor2_1 _1214_ (
    .A(subtract),
    .B(_0526_),
    .Y(_0569_)
  );
  sky130_fd_sc_hd__a21oi_1 _1215_ (
    .A1(subtract),
    .A2(_0550_),
    .B1(_0569_),
    .Y(_0570_)
  );
  sky130_fd_sc_hd__xnor2_1 _1216_ (
    .A(_0551_),
    .B(_0570_),
    .Y(_0571_)
  );
  sky130_fd_sc_hd__nand2_1 _1217_ (
    .A(_0481_),
    .B(_0527_),
    .Y(_0572_)
  );
  sky130_fd_sc_hd__o21ai_0 _1218_ (
    .A1(_0481_),
    .A2(_0552_),
    .B1(_0572_),
    .Y(_0573_)
  );
  sky130_fd_sc_hd__xnor2_1 _1219_ (
    .A(_0553_),
    .B(_0573_),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__nand3_1 _1220_ (
    .A(_0568_),
    .B(_0571_),
    .C(_0574_),
    .Y(_0575_)
  );
  sky130_fd_sc_hd__mux2i_1 _1221_ (
    .A0(_0529_),
    .A1(_0554_),
    .S(subtract),
    .Y(_0576_)
  );
  sky130_fd_sc_hd__xnor2_1 _1222_ (
    .A(_0555_),
    .B(_0576_),
    .Y(_0577_)
  );
  sky130_fd_sc_hd__nand4_1 _1223_ (
    .A(_0568_),
    .B(_0571_),
    .C(_0574_),
    .D(_0577_),
    .Y(_0578_)
  );
  sky130_fd_sc_hd__nor2_1 _1224_ (
    .A(subtract),
    .B(_0530_),
    .Y(_0579_)
  );
  sky130_fd_sc_hd__a21oi_1 _1225_ (
    .A1(subtract),
    .A2(_0556_),
    .B1(_0579_),
    .Y(_0580_)
  );
  sky130_fd_sc_hd__xor2_1 _1226_ (
    .A(_0557_),
    .B(_0580_),
    .X(_0581_)
  );
  sky130_fd_sc_hd__nor2_1 _1227_ (
    .A(_0578_),
    .B(_0581_),
    .Y(_0582_)
  );
  sky130_fd_sc_hd__nor2_1 _1228_ (
    .A(subtract),
    .B(_0531_),
    .Y(_0583_)
  );
  sky130_fd_sc_hd__a21oi_1 _1229_ (
    .A1(subtract),
    .A2(_0558_),
    .B1(_0583_),
    .Y(_0584_)
  );
  sky130_fd_sc_hd__xnor2_1 _1230_ (
    .A(_0559_),
    .B(_0584_),
    .Y(_0585_)
  );
  sky130_fd_sc_hd__or3_1 _1231_ (
    .A(_0578_),
    .B(_0581_),
    .C(_0585_),
    .X(_0586_)
  );
  sky130_fd_sc_hd__nor2_1 _1232_ (
    .A(subtract),
    .B(_0532_),
    .Y(_0587_)
  );
  sky130_fd_sc_hd__a21oi_1 _1233_ (
    .A1(subtract),
    .A2(_0560_),
    .B1(_0587_),
    .Y(_0588_)
  );
  sky130_fd_sc_hd__xnor2_1 _1234_ (
    .A(_0561_),
    .B(_0588_),
    .Y(_0589_)
  );
  sky130_fd_sc_hd__and2_0 _1235_ (
    .A(_0484_),
    .B(_0536_),
    .X(_0590_)
  );
  sky130_fd_sc_hd__maj3_1 _1236_ (
    .A(_0492_),
    .B(_0493_),
    .C(_0562_),
    .X(_0591_)
  );
  sky130_fd_sc_hd__xor2_1 _1237_ (
    .A(_0486_),
    .B(_0488_),
    .X(_0592_)
  );
  sky130_fd_sc_hd__maj3_1 _1238_ (
    .A(_0486_),
    .B(_0488_),
    .C(_0591_),
    .X(_0593_)
  );
  sky130_fd_sc_hd__o21ai_0 _1239_ (
    .A1(_0029_),
    .A2(_0052_),
    .B1(_0483_),
    .Y(_0594_)
  );
  sky130_fd_sc_hd__o211a_1 _1240_ (
    .A1(_0590_),
    .A2(_0593_),
    .B1(_0594_),
    .C1(subtract),
    .X(_0595_)
  );
  sky130_fd_sc_hd__o211ai_1 _1241_ (
    .A1(_0590_),
    .A2(_0593_),
    .B1(_0594_),
    .C1(subtract),
    .Y(_0596_)
  );
  sky130_fd_sc_hd__o21ai_0 _1242_ (
    .A1(_0586_),
    .A2(_0589_),
    .B1(_0595_),
    .Y(_0597_)
  );
  sky130_fd_sc_hd__xor2_1 _1243_ (
    .A(_0564_),
    .B(_0597_),
    .X(addsub_man[11])
  );
  sky130_fd_sc_hd__nand2_1 _1244_ (
    .A(_0578_),
    .B(_0595_),
    .Y(_0598_)
  );
  sky130_fd_sc_hd__xnor2_1 _1245_ (
    .A(_0581_),
    .B(_0598_),
    .Y(addsub_man[8])
  );
  sky130_fd_sc_hd__nor2_1 _1246_ (
    .A(_0582_),
    .B(_0596_),
    .Y(_0599_)
  );
  sky130_fd_sc_hd__xor2_1 _1247_ (
    .A(_0585_),
    .B(_0599_),
    .X(addsub_man[9])
  );
  sky130_fd_sc_hd__nand2_1 _1248_ (
    .A(_0586_),
    .B(_0595_),
    .Y(_0600_)
  );
  sky130_fd_sc_hd__xnor2_1 _1249_ (
    .A(_0589_),
    .B(_0600_),
    .Y(addsub_man[10])
  );
  sky130_fd_sc_hd__mux2i_1 _1250_ (
    .A0(_0534_),
    .A1(_0591_),
    .S(subtract),
    .Y(_0601_)
  );
  sky130_fd_sc_hd__xnor2_1 _1251_ (
    .A(_0592_),
    .B(_0601_),
    .Y(_0602_)
  );
  sky130_fd_sc_hd__nor3b_1 _1252_ (
    .A(_0586_),
    .B(_0589_),
    .C_N(_0564_),
    .Y(_0603_)
  );
  sky130_fd_sc_hd__nor2_1 _1253_ (
    .A(_0596_),
    .B(_0603_),
    .Y(_0604_)
  );
  sky130_fd_sc_hd__xnor2_1 _1254_ (
    .A(_0602_),
    .B(_0604_),
    .Y(addsub_man[12])
  );
  sky130_fd_sc_hd__nand2_1 _1255_ (
    .A(_0481_),
    .B(_0535_),
    .Y(_0605_)
  );
  sky130_fd_sc_hd__o21ai_0 _1256_ (
    .A1(_0481_),
    .A2(_0593_),
    .B1(_0605_),
    .Y(_0606_)
  );
  sky130_fd_sc_hd__xor2_1 _1257_ (
    .A(_0590_),
    .B(_0606_),
    .X(_0607_)
  );
  sky130_fd_sc_hd__a21oi_1 _1258_ (
    .A1(_0602_),
    .A2(_0603_),
    .B1(_0596_),
    .Y(_0608_)
  );
  sky130_fd_sc_hd__xnor2_1 _1259_ (
    .A(_0607_),
    .B(_0608_),
    .Y(addsub_man[13])
  );
  sky130_fd_sc_hd__a21oi_1 _1260_ (
    .A1(_0568_),
    .A2(_0571_),
    .B1(_0596_),
    .Y(_0609_)
  );
  sky130_fd_sc_hd__xnor2_1 _1261_ (
    .A(_0574_),
    .B(_0609_),
    .Y(addsub_man[6])
  );
  sky130_fd_sc_hd__nand2_1 _1262_ (
    .A(_0575_),
    .B(_0595_),
    .Y(_0610_)
  );
  sky130_fd_sc_hd__xor2_1 _1263_ (
    .A(_0577_),
    .B(_0610_),
    .X(addsub_man[7])
  );
  sky130_fd_sc_hd__nand2_1 _1264_ (
    .A(_0547_),
    .B(_0595_),
    .Y(_0611_)
  );
  sky130_fd_sc_hd__xnor2_1 _1265_ (
    .A(_0567_),
    .B(_0611_),
    .Y(addsub_man[4])
  );
  sky130_fd_sc_hd__nor2_1 _1266_ (
    .A(_0568_),
    .B(_0596_),
    .Y(_0612_)
  );
  sky130_fd_sc_hd__xnor2_1 _1267_ (
    .A(_0571_),
    .B(_0612_),
    .Y(addsub_man[5])
  );
  sky130_fd_sc_hd__nor2_1 _1268_ (
    .A(_0481_),
    .B(_0542_),
    .Y(_0613_)
  );
  sky130_fd_sc_hd__xnor2_1 _1269_ (
    .A(_0543_),
    .B(_0613_),
    .Y(addsub_man[2])
  );
  sky130_fd_sc_hd__a21oi_1 _1270_ (
    .A1(_0542_),
    .A2(_0543_),
    .B1(_0481_),
    .Y(_0614_)
  );
  sky130_fd_sc_hd__xnor2_1 _1271_ (
    .A(_0545_),
    .B(_0614_),
    .Y(addsub_man[3])
  );
  sky130_fd_sc_hd__nand2_1 _1272_ (
    .A(addsub_man[0]),
    .B(subtract),
    .Y(_0615_)
  );
  sky130_fd_sc_hd__xnor2_1 _1273_ (
    .A(_0541_),
    .B(_0615_),
    .Y(addsub_man[1])
  );
  sky130_fd_sc_hd__and3_1 _1274_ (
    .A(zeroA),
    .B(zeroB),
    .C(signB_reg),
    .X(_0616_)
  );
  sky130_fd_sc_hd__o21ai_0 _1275_ (
    .A1(infinA),
    .A2(_0616_),
    .B1(signA_reg),
    .Y(_0617_)
  );
  sky130_fd_sc_hd__and3b_1 _1276_ (
    .A_N(infinB),
    .B(sign_reg),
    .C(_0138_),
    .X(_0618_)
  );
  sky130_fd_sc_hd__a21oi_1 _1277_ (
    .A1(infinB),
    .A2(signB_reg),
    .B1(_0618_),
    .Y(_0619_)
  );
  sky130_fd_sc_hd__o21ai_0 _1278_ (
    .A1(infinA),
    .A2(_0619_),
    .B1(_0617_),
    .Y(_0620_)
  );
  sky130_fd_sc_hd__and2_0 _1279_ (
    .A(_0468_),
    .B(_0620_),
    .X(ans[15])
  );
  sky130_fd_sc_hd__nor4_1 _1280_ (
    .A(b[6]),
    .B(b[7]),
    .C(b[8]),
    .D(b[9]),
    .Y(_0621_)
  );
  sky130_fd_sc_hd__nor2_1 _1281_ (
    .A(b[3]),
    .B(b[4]),
    .Y(_0622_)
  );
  sky130_fd_sc_hd__nor4_1 _1282_ (
    .A(b[0]),
    .B(b[1]),
    .C(b[2]),
    .D(b[5]),
    .Y(_0623_)
  );
  sky130_fd_sc_hd__nand3_1 _1283_ (
    .A(_0621_),
    .B(_0622_),
    .C(_0623_),
    .Y(_0624_)
  );
  sky130_fd_sc_hd__nor2_1 _1284_ (
    .A(_0031_),
    .B(_0624_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__nor4_1 _1285_ (
    .A(a[6]),
    .B(a[7]),
    .C(a[8]),
    .D(a[9]),
    .Y(_0625_)
  );
  sky130_fd_sc_hd__nor2_1 _1286_ (
    .A(a[3]),
    .B(a[4]),
    .Y(_0626_)
  );
  sky130_fd_sc_hd__nor4_1 _1287_ (
    .A(a[0]),
    .B(a[1]),
    .C(a[2]),
    .D(a[5]),
    .Y(_0627_)
  );
  sky130_fd_sc_hd__nand3_1 _1288_ (
    .A(_0625_),
    .B(_0626_),
    .C(_0627_),
    .Y(_0628_)
  );
  sky130_fd_sc_hd__nor2_1 _1289_ (
    .A(_0029_),
    .B(_0628_),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__nor2_1 _1290_ (
    .A(_0039_),
    .B(_0624_),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__nor2_1 _1291_ (
    .A(_0043_),
    .B(_0628_),
    .Y(_0000_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1292_ (
    .A(_0624_),
    .SLEEP(_0039_),
    .X(_0003_)
  );
  sky130_fd_sc_hd__and3_1 _1293_ (
    .A(a[14]),
    .B(_0010_),
    .C(_0628_),
    .X(_0002_)
  );
  sky130_fd_sc_hd__mux2i_1 _1294_ (
    .A0(a[15]),
    .A1(signB),
    .S(_0052_),
    .Y(_0629_)
  );
  sky130_fd_sc_hd__xnor2_1 _1295_ (
    .A(_0596_),
    .B(_0629_),
    .Y(_0630_)
  );
  sky130_fd_sc_hd__a41oi_1 _1296_ (
    .A1(subtract),
    .A2(_0602_),
    .A3(_0603_),
    .A4(_0607_),
    .B1(_0630_),
    .Y(_0006_)
  );
  (* src = "src/fpu_FADDSUB.sv:200.5-203.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1297_ (
    .CLK(clk),
    .D(a[15]),
    .Q(signA_reg)
  );
  (* src = "src/fpu_FADDSUB.sv:200.5-203.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1298_ (
    .CLK(clk),
    .D(signB),
    .Q(signB_reg)
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1299_ (
    .CLK(clk),
    .D(subtract),
    .Q(subtract_reg)
  );
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1300_ (
    .CLK(clk),
    .D(_0002_),
    .Q(nanA)
  );
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1301_ (
    .CLK(clk),
    .D(_0003_),
    .Q(nanB)
  );
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1302_ (
    .CLK(clk),
    .D(_0000_),
    .Q(infinA)
  );
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1303_ (
    .CLK(clk),
    .D(_0001_),
    .Q(infinB)
  );
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1304_ (
    .CLK(clk),
    .D(_0004_),
    .Q(zeroA)
  );
  (* src = "src/fpu_FADDSUB.sv:19.5-26.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1305_ (
    .CLK(clk),
    .D(_0005_),
    .Q(zeroB)
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1306_ (
    .CLK(clk),
    .D(_0006_),
    .Q(sign_reg)
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1307_ (
    .CLK(clk),
    .D(addsub_man[0]),
    .Q(pre_norm_man[7])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1308_ (
    .CLK(clk),
    .D(addsub_man[1]),
    .Q(pre_norm_man[8])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1309_ (
    .CLK(clk),
    .D(addsub_man[2]),
    .Q(pre_norm_man[9])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1310_ (
    .CLK(clk),
    .D(addsub_man[3]),
    .Q(pre_norm_man[10])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1311_ (
    .CLK(clk),
    .D(addsub_man[4]),
    .Q(pre_norm_man[11])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1312_ (
    .CLK(clk),
    .D(addsub_man[5]),
    .Q(pre_norm_man[12])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1313_ (
    .CLK(clk),
    .D(addsub_man[6]),
    .Q(pre_norm_man[13])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1314_ (
    .CLK(clk),
    .D(addsub_man[7]),
    .Q(pre_norm_man[14])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1315_ (
    .CLK(clk),
    .D(addsub_man[8]),
    .Q(pre_norm_man[15])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1316_ (
    .CLK(clk),
    .D(addsub_man[9]),
    .Q(pre_norm_man[16])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1317_ (
    .CLK(clk),
    .D(addsub_man[10]),
    .Q(pre_norm_man[17])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1318_ (
    .CLK(clk),
    .D(addsub_man[11]),
    .Q(pre_norm_man[18])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1319_ (
    .CLK(clk),
    .D(addsub_man[12]),
    .Q(pre_norm_man[19])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1320_ (
    .CLK(clk),
    .D(addsub_man[13]),
    .Q(pre_norm_man[20])
  );
  (* src = "src/fpu_FADDSUB.sv:85.5-89.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1321_ (
    .CLK(clk),
    .D(addsub_man[14]),
    .Q(pre_norm_man[21])
  );
  assign ans_corrected = ans;
  assign ans_calculated[15] = sign_reg;
  assign man_fixing[5:0] = 6'h00;
  assign pre_norm_man[6:0] = 7'h00;
  assign addsub_man_norm[0] = addsub_man[0];
  assign alu_smaller[0] = addsub_man[0];
  assign alu_bigger[2:0] = 3'h0;
  assign final_exp[6] = final_exp[5];
  assign man_smaller[10:0] = 11'h000;
  assign man_bigger = { alu_bigger[13:3], 11'h000 };
  assign corrected_expB[6] = corrected_expB[5];
  assign corrected_expA[6] = corrected_expA[5];
  assign init_manB[20:0] = { b[9:0], 11'h000 };
  assign init_manA[20:0] = { a[9:0], 11'h000 };
  assign init_expA = a[14:10];
  assign init_expB = b[14:10];
  assign signA = a[15];
endmodule
