/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* top =  1  *)
(* src = "src/fdiv_blocks.sv:137.1-196.10" *)
module fdiv_post_process(normalised_prod, normalised_exp, nanA, nanB, infinA, infinB, A0, B0, final_sign, out);
  (* src = "src/fdiv_blocks.sv:138.25-138.40" *)
  input [24:0] normalised_prod;
  wire [24:0] normalised_prod;
  (* src = "src/fdiv_blocks.sv:139.25-139.39" *)
  input [6:0] normalised_exp;
  wire [6:0] normalised_exp;
  (* src = "src/fdiv_blocks.sv:140.25-140.29" *)
  input nanA;
  wire nanA;
  (* src = "src/fdiv_blocks.sv:140.31-140.35" *)
  input nanB;
  wire nanB;
  (* src = "src/fdiv_blocks.sv:140.37-140.43" *)
  input infinA;
  wire infinA;
  (* src = "src/fdiv_blocks.sv:140.45-140.51" *)
  input infinB;
  wire infinB;
  (* src = "src/fdiv_blocks.sv:140.53-140.55" *)
  input A0;
  wire A0;
  (* src = "src/fdiv_blocks.sv:140.57-140.59" *)
  input B0;
  wire B0;
  (* src = "src/fdiv_blocks.sv:140.61-140.71" *)
  input final_sign;
  wire final_sign;
  (* src = "src/fdiv_blocks.sv:141.25-141.28" *)
  output [15:0] out;
  wire [15:0] out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  (* src = "src/fdiv_blocks.sv:179.17-179.27" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [15:0] normal_ans;
  (* src = "src/fdiv_blocks.sv:147.17-147.26" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24" *)
  wire [24:0] prefix_or;
  (* src = "src/fdiv_blocks.sv:184.18-184.29" *)
  (* unused_bits = "9 10 11 12 13 14" *)
  wire [15:0] special_ans;
  (* src = "src/fdiv_blocks.sv:144.16-144.29" *)
  (* unused_bits = "1 2 3 4 5 6" *)
  wire [6:0] underflow_amt;
  sky130_fd_sc_hd__clkinv_1 _210_ (
    .A(normalised_exp[1]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__clkinv_1 _211_ (
    .A(normalised_prod[22]),
    .Y(_165_)
  );
  sky130_fd_sc_hd__clkinv_1 _212_ (
    .A(normalised_prod[14]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__clkinv_1 _213_ (
    .A(normalised_prod[20]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor4_1 _214_ (
    .A(nanA),
    .B(nanB),
    .C(infinA),
    .D(B0),
    .Y(_168_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _215_ (
    .A(normalised_exp[3]),
    .SLEEP(normalised_exp[6]),
    .X(_169_)
  );
  sky130_fd_sc_hd__or4_1 _216_ (
    .A(normalised_exp[1]),
    .B(normalised_exp[3]),
    .C(normalised_exp[2]),
    .D(normalised_exp[0]),
    .X(_170_)
  );
  sky130_fd_sc_hd__nor3_1 _217_ (
    .A(normalised_exp[4]),
    .B(normalised_exp[5]),
    .C(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _218_ (
    .A(normalised_exp[6]),
    .B(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _219_ (
    .A(normalised_exp[6]),
    .SLEEP(_171_),
    .X(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _220_ (
    .A(normalised_exp[0]),
    .B(_172_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__and2_0 _221_ (
    .A(normalised_prod[13]),
    .B(_172_),
    .X(_175_)
  );
  sky130_fd_sc_hd__nand2b_1 _222_ (
    .A_N(normalised_exp[6]),
    .B(normalised_exp[1]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__and2_0 _223_ (
    .A(normalised_exp[1]),
    .B(normalised_exp[0]),
    .X(_177_)
  );
  sky130_fd_sc_hd__o21ai_0 _224_ (
    .A1(normalised_exp[1]),
    .A2(normalised_exp[0]),
    .B1(normalised_exp[6]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__o21ai_0 _225_ (
    .A1(_177_),
    .A2(_178_),
    .B1(_176_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(normalised_exp[0]),
    .B(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xnor2_1 _227_ (
    .A(normalised_exp[2]),
    .B(_178_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand3_1 _228_ (
    .A(normalised_exp[0]),
    .B(_179_),
    .C(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__o31ai_1 _229_ (
    .A1(normalised_exp[1]),
    .A2(normalised_exp[2]),
    .A3(normalised_exp[0]),
    .B1(normalised_exp[6]),
    .Y(_183_)
  );
  sky130_fd_sc_hd__xnor2_1 _230_ (
    .A(normalised_exp[3]),
    .B(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand4_1 _231_ (
    .A(normalised_exp[0]),
    .B(_179_),
    .C(_181_),
    .D(_184_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__xnor2_1 _232_ (
    .A(_182_),
    .B(_184_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xor2_1 _233_ (
    .A(_182_),
    .B(_184_),
    .X(_187_)
  );
  sky130_fd_sc_hd__mux2_1 _234_ (
    .A0(_164_),
    .A1(_179_),
    .S(normalised_exp[0]),
    .X(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(normalised_exp[0]),
    .B(normalised_prod[21]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__o21ai_0 _236_ (
    .A1(normalised_exp[0]),
    .A2(_165_),
    .B1(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__mux2_1 _237_ (
    .A0(normalised_prod[24]),
    .A1(normalised_prod[23]),
    .S(normalised_exp[0]),
    .X(_191_)
  );
  sky130_fd_sc_hd__mux2i_1 _238_ (
    .A0(_191_),
    .A1(_190_),
    .S(_188_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__xnor2_1 _239_ (
    .A(_180_),
    .B(_181_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__xor2_1 _240_ (
    .A(_180_),
    .B(_181_),
    .X(_194_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _241_ (
    .A(normalised_exp[4]),
    .SLEEP(normalised_exp[6]),
    .X(_195_)
  );
  sky130_fd_sc_hd__o21a_1 _242_ (
    .A1(normalised_exp[4]),
    .A2(_170_),
    .B1(normalised_exp[6]),
    .X(_196_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(normalised_exp[4]),
    .B(_170_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__a21oi_1 _244_ (
    .A1(_196_),
    .A2(_197_),
    .B1(_195_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__a21o_1 _245_ (
    .A1(_196_),
    .A2(_197_),
    .B1(_195_),
    .X(_199_)
  );
  sky130_fd_sc_hd__xor2_1 _246_ (
    .A(normalised_exp[5]),
    .B(_196_),
    .X(_200_)
  );
  sky130_fd_sc_hd__xnor2_1 _247_ (
    .A(normalised_exp[5]),
    .B(_196_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nor3_1 _248_ (
    .A(_185_),
    .B(_198_),
    .C(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(normalised_exp[6]),
    .B(_171_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__o31a_1 _250_ (
    .A1(_185_),
    .A2(_198_),
    .A3(_201_),
    .B1(_203_),
    .X(_204_)
  );
  sky130_fd_sc_hd__o31ai_1 _251_ (
    .A1(_185_),
    .A2(_198_),
    .A3(_201_),
    .B1(_203_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor3_1 _252_ (
    .A(_192_),
    .B(_193_),
    .C(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(normalised_prod[18]),
    .A1(normalised_prod[17]),
    .S(normalised_exp[0]),
    .X(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(normalised_exp[0]),
    .B(normalised_prod[19]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o21ai_0 _255_ (
    .A1(normalised_exp[0]),
    .A2(_167_),
    .B1(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__mux2i_1 _256_ (
    .A0(_209_),
    .A1(_207_),
    .S(_188_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__and3_1 _257_ (
    .A(_185_),
    .B(_198_),
    .C(_201_),
    .X(_001_)
  );
  sky130_fd_sc_hd__o21ai_0 _258_ (
    .A1(_202_),
    .A2(_001_),
    .B1(_173_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor4_1 _259_ (
    .A(_194_),
    .B(_205_),
    .C(_000_),
    .D(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__mux2i_1 _260_ (
    .A0(normalised_prod[16]),
    .A1(normalised_prod[15]),
    .S(normalised_exp[0]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _261_ (
    .A(_188_),
    .B(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _262_ (
    .A(normalised_exp[0]),
    .B(normalised_prod[13]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21ai_0 _263_ (
    .A1(normalised_exp[0]),
    .A2(_166_),
    .B1(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a21oi_1 _264_ (
    .A1(_188_),
    .A2(_007_),
    .B1(_005_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o211ai_1 _265_ (
    .A1(_202_),
    .A2(_001_),
    .B1(_173_),
    .C1(_194_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__o32ai_1 _266_ (
    .A1(_205_),
    .A2(_008_),
    .A3(_009_),
    .B1(_002_),
    .B2(_187_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o22a_1 _267_ (
    .A1(_187_),
    .A2(_206_),
    .B1(_003_),
    .B2(_010_),
    .X(_011_)
  );
  sky130_fd_sc_hd__o211a_1 _268_ (
    .A1(_202_),
    .A2(_001_),
    .B1(_173_),
    .C1(_187_),
    .X(_012_)
  );
  sky130_fd_sc_hd__o211ai_1 _269_ (
    .A1(_202_),
    .A2(_001_),
    .B1(_173_),
    .C1(_187_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(normalised_exp[0]),
    .B(normalised_prod[24]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__mux2i_1 _271_ (
    .A0(normalised_prod[23]),
    .A1(normalised_prod[22]),
    .S(normalised_exp[0]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _272_ (
    .A0(_014_),
    .A1(_015_),
    .S(_188_),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _273_ (
    .A(_205_),
    .SLEEP(_016_),
    .X(_017_)
  );
  sky130_fd_sc_hd__o21ai_0 _274_ (
    .A1(_009_),
    .A2(_017_),
    .B1(_013_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__mux2i_1 _275_ (
    .A0(normalised_prod[21]),
    .A1(normalised_prod[20]),
    .S(normalised_exp[0]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(_188_),
    .B(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _277_ (
    .A0(normalised_prod[19]),
    .A1(normalised_prod[18]),
    .S(normalised_exp[0]),
    .X(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _278_ (
    .A(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a31oi_1 _279_ (
    .A1(_188_),
    .A2(_204_),
    .A3(_021_),
    .B1(_020_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__mux2i_1 _280_ (
    .A0(normalised_prod[17]),
    .A1(normalised_prod[16]),
    .S(normalised_exp[0]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__mux2i_1 _281_ (
    .A0(normalised_prod[15]),
    .A1(normalised_prod[14]),
    .S(normalised_exp[0]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__mux2i_1 _282_ (
    .A0(_024_),
    .A1(_025_),
    .S(_188_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a31oi_1 _283_ (
    .A1(_194_),
    .A2(_204_),
    .A3(_026_),
    .B1(_186_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _284_ (
    .A1(_194_),
    .A2(_023_),
    .B1(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a22o_1 _285_ (
    .A1(normalised_prod[14]),
    .A2(_172_),
    .B1(_018_),
    .B2(_028_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2i_1 _286_ (
    .A0(_015_),
    .A1(_019_),
    .S(_188_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _287_ (
    .A1(_204_),
    .A2(_030_),
    .B1(_193_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a41oi_1 _288_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[24]),
    .A3(_188_),
    .A4(_204_),
    .B1(_194_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__o32a_1 _289_ (
    .A1(_013_),
    .A2(_031_),
    .A3(_032_),
    .B1(_173_),
    .B2(_167_),
    .X(_033_)
  );
  sky130_fd_sc_hd__a22o_1 _290_ (
    .A1(normalised_prod[21]),
    .A2(_172_),
    .B1(_206_),
    .B2(_012_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nor2b_1 _291_ (
    .A(_033_),
    .B_N(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a311o_1 _292_ (
    .A1(_188_),
    .A2(_204_),
    .A3(_021_),
    .B1(_020_),
    .C1(_193_),
    .X(_036_)
  );
  sky130_fd_sc_hd__o21ai_0 _293_ (
    .A1(_205_),
    .A2(_016_),
    .B1(_193_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a32o_1 _294_ (
    .A1(_012_),
    .A2(_036_),
    .A3(_037_),
    .B1(_172_),
    .B2(normalised_prod[18]),
    .X(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(normalised_prod[19]),
    .B(_172_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _296_ (
    .A0(_190_),
    .A1(_209_),
    .S(_188_),
    .X(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(_204_),
    .A2(_040_),
    .B1(_193_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand3_1 _298_ (
    .A(_188_),
    .B(_191_),
    .C(_204_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a31oi_1 _299_ (
    .A1(_188_),
    .A2(_191_),
    .A3(_204_),
    .B1(_194_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o31ai_1 _300_ (
    .A1(_013_),
    .A2(_041_),
    .A3(_043_),
    .B1(_039_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(_038_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand3_1 _302_ (
    .A(_035_),
    .B(_038_),
    .C(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__mux2i_1 _303_ (
    .A0(_022_),
    .A1(_024_),
    .S(_188_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21oi_1 _304_ (
    .A1(_204_),
    .A2(_047_),
    .B1(_193_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21oi_1 _305_ (
    .A1(_204_),
    .A2(_030_),
    .B1(_194_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor3_1 _306_ (
    .A(_013_),
    .B(_048_),
    .C(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor4b_1 _307_ (
    .A(_205_),
    .B(_009_),
    .C(_014_),
    .D_N(_188_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a211o_1 _308_ (
    .A1(normalised_prod[16]),
    .A2(_172_),
    .B1(_050_),
    .C1(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__o21ai_0 _309_ (
    .A1(_009_),
    .A2(_042_),
    .B1(_013_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand3_1 _310_ (
    .A(_193_),
    .B(_204_),
    .C(_040_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _311_ (
    .A(_188_),
    .B(_004_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o2111ai_1 _312_ (
    .A1(_188_),
    .A2(_207_),
    .B1(_055_),
    .C1(_194_),
    .D1(_204_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand3_1 _313_ (
    .A(_187_),
    .B(_054_),
    .C(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a22o_1 _314_ (
    .A1(normalised_prod[15]),
    .A2(_172_),
    .B1(_053_),
    .B2(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__nand3_1 _315_ (
    .A(_193_),
    .B(_204_),
    .C(_047_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__mux2i_1 _316_ (
    .A0(normalised_prod[13]),
    .A1(normalised_prod[12]),
    .S(normalised_exp[0]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__mux2i_1 _317_ (
    .A0(_025_),
    .A1(_060_),
    .S(_188_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand3_1 _318_ (
    .A(_194_),
    .B(_204_),
    .C(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a21oi_1 _319_ (
    .A1(_059_),
    .A2(_062_),
    .B1(_013_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(normalised_prod[12]),
    .B(_172_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__o41ai_1 _321_ (
    .A1(_187_),
    .A2(_002_),
    .A3(_031_),
    .A4(_032_),
    .B1(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _322_ (
    .A(_063_),
    .SLEEP(_065_),
    .X(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _323_ (
    .A1(_205_),
    .A2(_000_),
    .B1(_194_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o21ai_0 _324_ (
    .A1(_192_),
    .A2(_205_),
    .B1(_193_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a32o_1 _325_ (
    .A1(_012_),
    .A2(_067_),
    .A3(_068_),
    .B1(_172_),
    .B2(normalised_prod[17]),
    .X(_069_)
  );
  sky130_fd_sc_hd__o32ai_1 _326_ (
    .A1(_186_),
    .A2(_009_),
    .A3(_017_),
    .B1(_173_),
    .B2(_165_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o21ai_0 _327_ (
    .A1(_063_),
    .A2(_065_),
    .B1(_038_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(_044_),
    .B(_069_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand4bb_1 _329_ (
    .A_N(_071_),
    .B_N(_072_),
    .C(_052_),
    .D(_058_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_035_),
    .B(_070_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o2111ai_1 _331_ (
    .A1(_175_),
    .A2(_011_),
    .B1(_029_),
    .C1(_035_),
    .D1(_070_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor4_1 _332_ (
    .A(_164_),
    .B(_174_),
    .C(_073_),
    .D(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o2111ai_1 _333_ (
    .A1(_175_),
    .A2(_011_),
    .B1(_038_),
    .C1(_066_),
    .D1(_069_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand4_1 _334_ (
    .A(_029_),
    .B(_044_),
    .C(_052_),
    .D(_058_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor4_1 _335_ (
    .A(_174_),
    .B(_074_),
    .C(_077_),
    .D(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a21oi_1 _336_ (
    .A1(normalised_exp[2]),
    .A2(_076_),
    .B1(_169_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand4_1 _337_ (
    .A(normalised_exp[1]),
    .B(normalised_exp[3]),
    .C(normalised_exp[2]),
    .D(_079_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2b_1 _338_ (
    .A(_080_),
    .B_N(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2b_1 _339_ (
    .A_N(normalised_exp[6]),
    .B(normalised_exp[5]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand4_1 _340_ (
    .A(normalised_exp[3]),
    .B(normalised_exp[2]),
    .C(_195_),
    .D(_076_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__mux2i_1 _341_ (
    .A0(normalised_exp[5]),
    .A1(_083_),
    .S(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(infinB),
    .B(A0),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _343_ (
    .A1(_082_),
    .A2(_085_),
    .B1(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(_168_),
    .B(_087_),
    .Y(out[13])
  );
  sky130_fd_sc_hd__nand2b_1 _345_ (
    .A_N(normalised_exp[6]),
    .B(normalised_exp[2]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__mux2i_1 _346_ (
    .A0(_088_),
    .A1(normalised_exp[2]),
    .S(_076_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o21ai_0 _347_ (
    .A1(_085_),
    .A2(_089_),
    .B1(_086_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(_168_),
    .B(_090_),
    .Y(out[12])
  );
  sky130_fd_sc_hd__mux2i_1 _349_ (
    .A0(_176_),
    .A1(normalised_exp[1]),
    .S(_079_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _350_ (
    .A1(_184_),
    .A2(_199_),
    .B1(_200_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _351_ (
    .A(_203_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor4_1 _352_ (
    .A(normalised_prod[1]),
    .B(normalised_prod[0]),
    .C(normalised_prod[3]),
    .D(normalised_prod[2]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _353_ (
    .A(_094_),
    .SLEEP(normalised_prod[4]),
    .X(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(normalised_prod[6]),
    .B(normalised_prod[5]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(normalised_prod[7]),
    .B(normalised_prod[8]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__and4b_1 _356_ (
    .A_N(normalised_prod[4]),
    .B(_094_),
    .C(_096_),
    .D(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(normalised_prod[10]),
    .B(normalised_prod[9]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _358_ (
    .A(normalised_prod[12]),
    .B(normalised_prod[11]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand3_1 _359_ (
    .A(_098_),
    .B(_099_),
    .C(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a211oi_1 _360_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[15]),
    .B1(normalised_prod[14]),
    .C1(normalised_prod[13]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__mux2i_1 _361_ (
    .A0(_006_),
    .A1(_102_),
    .S(_179_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(normalised_exp[0]),
    .B(normalised_prod[7]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand4_1 _363_ (
    .A(_179_),
    .B(_095_),
    .C(_096_),
    .D(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _364_ (
    .A(normalised_exp[0]),
    .B(normalised_prod[5]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand3b_1 _365_ (
    .A_N(normalised_prod[4]),
    .B(_094_),
    .C(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(normalised_exp[0]),
    .B(normalised_prod[11]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21oi_1 _367_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[9]),
    .B1(_179_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__and4_1 _368_ (
    .A(_179_),
    .B(_098_),
    .C(_099_),
    .D(_108_),
    .X(_110_)
  );
  sky130_fd_sc_hd__a2111oi_0 _369_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[3]),
    .B1(normalised_prod[2]),
    .C1(normalised_prod[1]),
    .D1(normalised_prod[0]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a211o_1 _370_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[1]),
    .B1(normalised_prod[0]),
    .C1(_179_),
    .X(_112_)
  );
  sky130_fd_sc_hd__o21a_1 _371_ (
    .A1(_179_),
    .A2(_107_),
    .B1(_181_),
    .X(_113_)
  );
  sky130_fd_sc_hd__a21oi_1 _372_ (
    .A1(_179_),
    .A2(_111_),
    .B1(_181_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a221oi_1 _373_ (
    .A1(_105_),
    .A2(_113_),
    .B1(_114_),
    .B2(_112_),
    .C1(_184_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a211o_1 _374_ (
    .A1(_098_),
    .A2(_109_),
    .B1(_110_),
    .C1(_181_),
    .X(_116_)
  );
  sky130_fd_sc_hd__o21ai_0 _375_ (
    .A1(_101_),
    .A2(_103_),
    .B1(_181_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a31oi_1 _376_ (
    .A1(_184_),
    .A2(_116_),
    .A3(_117_),
    .B1(_115_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor4_1 _377_ (
    .A(normalised_prod[13]),
    .B(normalised_prod[14]),
    .C(normalised_prod[15]),
    .D(normalised_prod[16]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand4_1 _378_ (
    .A(_098_),
    .B(_099_),
    .C(_100_),
    .D(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(_179_),
    .B(_208_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor4_1 _380_ (
    .A(normalised_prod[17]),
    .B(normalised_prod[18]),
    .C(_120_),
    .D(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a211oi_1 _381_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[17]),
    .B1(_179_),
    .C1(_120_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_1 _382_ (
    .A(normalised_prod[19]),
    .B(normalised_prod[20]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor4b_1 _383_ (
    .A(normalised_prod[17]),
    .B(normalised_prod[18]),
    .C(_120_),
    .D_N(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(_179_),
    .B(_189_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a211o_1 _385_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[23]),
    .B1(normalised_prod[21]),
    .C1(normalised_prod[22]),
    .X(_127_)
  );
  sky130_fd_sc_hd__a21oi_1 _386_ (
    .A1(_179_),
    .A2(_127_),
    .B1(_126_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21boi_0 _387_ (
    .A1(_125_),
    .A2(_128_),
    .B1_N(_181_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o31ai_1 _388_ (
    .A1(_181_),
    .A2(_122_),
    .A3(_123_),
    .B1(_199_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o22a_1 _389_ (
    .A1(_199_),
    .A2(_118_),
    .B1(_129_),
    .B2(_130_),
    .X(_131_)
  );
  sky130_fd_sc_hd__nor4_1 _390_ (
    .A(normalised_prod[23]),
    .B(normalised_prod[24]),
    .C(normalised_prod[21]),
    .D(normalised_prod[22]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a31oi_1 _391_ (
    .A1(_093_),
    .A2(_125_),
    .A3(_132_),
    .B1(_172_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _392_ (
    .A1(_093_),
    .A2(_131_),
    .B1(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__or3b_1 _393_ (
    .A(_073_),
    .B(_075_),
    .C_N(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__a21oi_1 _394_ (
    .A1(_174_),
    .A2(_135_),
    .B1(_079_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__and4_1 _395_ (
    .A(normalised_exp[1]),
    .B(_195_),
    .C(_089_),
    .D(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__xnor2_1 _396_ (
    .A(_195_),
    .B(_081_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a211oi_1 _397_ (
    .A1(_082_),
    .A2(_137_),
    .B1(_091_),
    .C1(_085_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o31ai_1 _398_ (
    .A1(infinB),
    .A2(A0),
    .A3(_139_),
    .B1(_168_),
    .Y(out[11])
  );
  sky130_fd_sc_hd__o21ai_0 _399_ (
    .A1(_085_),
    .A2(_136_),
    .B1(_086_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _400_ (
    .A(_168_),
    .B(_140_),
    .Y(out[10])
  );
  sky130_fd_sc_hd__a211o_1 _401_ (
    .A1(infinA),
    .A2(infinB),
    .B1(nanA),
    .C1(nanB),
    .X(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _402_ (
    .A1(B0),
    .A2(A0),
    .B1(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(_168_),
    .B(_086_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a211o_1 _404_ (
    .A1(_082_),
    .A2(_137_),
    .B1(_143_),
    .C1(_085_),
    .X(_144_)
  );
  sky130_fd_sc_hd__o21a_1 _405_ (
    .A1(_175_),
    .A2(_011_),
    .B1(_134_),
    .X(_145_)
  );
  sky130_fd_sc_hd__o211a_1 _406_ (
    .A1(_175_),
    .A2(_011_),
    .B1(_029_),
    .C1(_134_),
    .X(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(_058_),
    .B(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__and3_1 _408_ (
    .A(_052_),
    .B(_058_),
    .C(_146_),
    .X(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _409_ (
    .A(_069_),
    .B(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2_1 _410_ (
    .A(_046_),
    .B(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _411_ (
    .A(_038_),
    .SLEEP(_149_),
    .X(_151_)
  );
  sky130_fd_sc_hd__nand2_1 _412_ (
    .A(_044_),
    .B(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__xnor2_1 _413_ (
    .A(_070_),
    .B(_150_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _414_ (
    .A1(_144_),
    .A2(_153_),
    .B1(_142_),
    .Y(out[9])
  );
  sky130_fd_sc_hd__nor3_1 _415_ (
    .A(_033_),
    .B(_045_),
    .C(_149_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o22ai_1 _416_ (
    .A1(_046_),
    .A2(_149_),
    .B1(_154_),
    .B2(_034_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _417_ (
    .A(_144_),
    .B(_155_),
    .Y(out[8])
  );
  sky130_fd_sc_hd__a211oi_1 _418_ (
    .A1(_033_),
    .A2(_152_),
    .B1(_154_),
    .C1(_144_),
    .Y(out[7])
  );
  sky130_fd_sc_hd__xnor2_1 _419_ (
    .A(_044_),
    .B(_151_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _420_ (
    .A(_144_),
    .B(_156_),
    .Y(out[6])
  );
  sky130_fd_sc_hd__xor2_1 _421_ (
    .A(_038_),
    .B(_149_),
    .X(_157_)
  );
  sky130_fd_sc_hd__nor2_1 _422_ (
    .A(_144_),
    .B(_157_),
    .Y(out[5])
  );
  sky130_fd_sc_hd__xnor2_1 _423_ (
    .A(_069_),
    .B(_148_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor2_1 _424_ (
    .A(_144_),
    .B(_158_),
    .Y(out[4])
  );
  sky130_fd_sc_hd__a21oi_1 _425_ (
    .A1(_058_),
    .A2(_146_),
    .B1(_052_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor3_1 _426_ (
    .A(_144_),
    .B(_148_),
    .C(_159_),
    .Y(out[3])
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(_058_),
    .B(_146_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nor3b_1 _428_ (
    .A(_160_),
    .B(_144_),
    .C_N(_147_),
    .Y(out[2])
  );
  sky130_fd_sc_hd__nor2_1 _429_ (
    .A(_029_),
    .B(_145_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nor3_1 _430_ (
    .A(_144_),
    .B(_146_),
    .C(_161_),
    .Y(out[1])
  );
  sky130_fd_sc_hd__nor2_1 _431_ (
    .A(_011_),
    .B(_134_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor3_1 _432_ (
    .A(_144_),
    .B(_145_),
    .C(_162_),
    .Y(out[0])
  );
  sky130_fd_sc_hd__o21ai_0 _433_ (
    .A1(_085_),
    .A2(_138_),
    .B1(_086_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _434_ (
    .A(_168_),
    .B(_163_),
    .Y(out[14])
  );
  assign { special_ans[15:11], special_ans[8:0] } = { final_sign, special_ans[10], special_ans[10], special_ans[10], special_ans[10], 9'h000 };
  assign normal_ans[15] = final_sign;
  assign prefix_or[0] = normalised_prod[0];
  assign underflow_amt[0] = normalised_exp[0];
  assign out[15] = final_sign;
endmodule
