/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* top =  1  *)
(* src = "src/fdiv_blocks.sv:2.1-71.10" *)
module fdiv_input_stage(a, b, final_manA, final_manB, final_expA, final_expB, tentative_exp, nanA, nanB, infinA, infinB, A0, B0, final_sign);
  (* src = "src/fdiv_blocks.sv:3.25-3.26" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "src/fdiv_blocks.sv:3.28-3.29" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "src/fdiv_blocks.sv:4.25-4.35" *)
  output [10:0] final_manA;
  wire [10:0] final_manA;
  (* src = "src/fdiv_blocks.sv:4.37-4.47" *)
  output [10:0] final_manB;
  wire [10:0] final_manB;
  (* src = "src/fdiv_blocks.sv:5.25-5.35" *)
  output [6:0] final_expA;
  wire [6:0] final_expA;
  (* src = "src/fdiv_blocks.sv:5.37-5.47" *)
  output [6:0] final_expB;
  wire [6:0] final_expB;
  (* src = "src/fdiv_blocks.sv:6.25-6.38" *)
  output [6:0] tentative_exp;
  wire [6:0] tentative_exp;
  (* src = "src/fdiv_blocks.sv:7.25-7.29" *)
  output nanA;
  wire nanA;
  (* src = "src/fdiv_blocks.sv:7.31-7.35" *)
  output nanB;
  wire nanB;
  (* src = "src/fdiv_blocks.sv:7.37-7.43" *)
  output infinA;
  wire infinA;
  (* src = "src/fdiv_blocks.sv:7.45-7.51" *)
  output infinB;
  wire infinB;
  (* src = "src/fdiv_blocks.sv:7.53-7.55" *)
  output A0;
  wire A0;
  (* src = "src/fdiv_blocks.sv:7.57-7.59" *)
  output B0;
  wire B0;
  (* src = "src/fdiv_blocks.sv:7.61-7.71" *)
  output final_sign;
  wire final_sign;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  (* src = "src/fdiv_blocks.sv:23.10-23.15" *)
  wire signA;
  (* src = "src/fdiv_blocks.sv:24.10-24.15" *)
  wire signB;
  (* src = "src/fdiv_blocks.sv:62.16-62.24" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] sub_expA;
  (* src = "src/fdiv_blocks.sv:63.16-63.24" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] sub_expB;
  sky130_fd_sc_hd__clkinv_1 _166_ (
    .A(a[11]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__clkinv_1 _167_ (
    .A(a[6]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__clkinv_1 _168_ (
    .A(a[9]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__clkinv_1 _169_ (
    .A(b[9]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(a[14]),
    .B(a[13]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor3_1 _171_ (
    .A(a[12]),
    .B(a[11]),
    .C(a[10]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand2_1 _172_ (
    .A(_149_),
    .B(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _173_ (
    .A(a[9]),
    .B(a[7]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor3_1 _174_ (
    .A(a[8]),
    .B(a[9]),
    .C(a[7]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__or3_1 _175_ (
    .A(a[8]),
    .B(a[9]),
    .C(a[7]),
    .X(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(a[6]),
    .B(a[5]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor3_1 _177_ (
    .A(a[4]),
    .B(a[6]),
    .C(a[5]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor3_1 _178_ (
    .A(a[3]),
    .B(a[2]),
    .C(a[1]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__and4b_1 _179_ (
    .A_N(a[0]),
    .B(_153_),
    .C(_156_),
    .D(_157_),
    .X(_158_)
  );
  sky130_fd_sc_hd__nand4b_1 _180_ (
    .A_N(a[0]),
    .B(_153_),
    .C(_156_),
    .D(_157_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_151_),
    .B(_158_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(a[3]),
    .B(_153_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__and3_1 _183_ (
    .A(a[3]),
    .B(_153_),
    .C(_156_),
    .X(_162_)
  );
  sky130_fd_sc_hd__and3_1 _184_ (
    .A(a[4]),
    .B(_153_),
    .C(_155_),
    .X(_163_)
  );
  sky130_fd_sc_hd__o211ai_1 _185_ (
    .A1(a[4]),
    .A2(a[3]),
    .B1(_153_),
    .C1(_155_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand4_1 _186_ (
    .A(a[0]),
    .B(_153_),
    .C(_156_),
    .D(_157_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _187_ (
    .A(a[8]),
    .SLEEP(a[9]),
    .X(_000_)
  );
  sky130_fd_sc_hd__o21ai_0 _188_ (
    .A1(a[8]),
    .A2(a[7]),
    .B1(_147_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o2111ai_1 _189_ (
    .A1(_154_),
    .A2(_155_),
    .B1(_164_),
    .C1(_165_),
    .D1(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand3_1 _190_ (
    .A(a[2]),
    .B(_153_),
    .C(_156_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(a[3]),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand3_1 _192_ (
    .A(a[1]),
    .B(_153_),
    .C(_156_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _193_ (
    .A(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor3_1 _194_ (
    .A(a[3]),
    .B(a[2]),
    .C(_005_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__or3_1 _195_ (
    .A(a[3]),
    .B(a[2]),
    .C(_005_),
    .X(_008_)
  );
  sky130_fd_sc_hd__o31a_1 _196_ (
    .A1(_002_),
    .A2(_004_),
    .A3(_007_),
    .B1(_160_),
    .X(final_expA[5])
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(a[14]),
    .B(final_expA[5]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _198_ (
    .A(_009_),
    .Y(final_expA[4])
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(b[14]),
    .B(b[13]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor3_1 _200_ (
    .A(b[12]),
    .B(b[11]),
    .C(b[10]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor3_1 _202_ (
    .A(b[3]),
    .B(b[2]),
    .C(b[1]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(b[9]),
    .B(b[7]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _204_ (
    .A(b[9]),
    .B(b[8]),
    .C(b[7]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(b[5]),
    .B(b[6]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor3_1 _206_ (
    .A(b[5]),
    .B(b[6]),
    .C(b[4]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand4b_1 _207_ (
    .A_N(b[0]),
    .B(_013_),
    .C(_015_),
    .D(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _208_ (
    .A(_018_),
    .SLEEP(_012_),
    .X(_019_)
  );
  sky130_fd_sc_hd__and3_1 _209_ (
    .A(b[3]),
    .B(_015_),
    .C(_017_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and3_1 _210_ (
    .A(b[4]),
    .B(_015_),
    .C(_016_),
    .X(_021_)
  );
  sky130_fd_sc_hd__o211ai_1 _211_ (
    .A1(b[4]),
    .A2(b[3]),
    .B1(_015_),
    .C1(_016_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _212_ (
    .A(b[8]),
    .SLEEP(b[9]),
    .X(_023_)
  );
  sky130_fd_sc_hd__nor3b_1 _213_ (
    .A(b[9]),
    .B(b[8]),
    .C_N(b[7]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _214_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand4_1 _215_ (
    .A(b[0]),
    .B(_013_),
    .C(_015_),
    .D(_017_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand3_1 _216_ (
    .A(_022_),
    .B(_025_),
    .C(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _217_ (
    .A1(b[5]),
    .A2(b[6]),
    .B1(_015_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand4_1 _218_ (
    .A(_022_),
    .B(_025_),
    .C(_026_),
    .D(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand3_1 _219_ (
    .A(b[1]),
    .B(_015_),
    .C(_017_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _220_ (
    .A(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor3_1 _221_ (
    .A(b[3]),
    .B(b[2]),
    .C(_030_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__or3_1 _222_ (
    .A(b[3]),
    .B(b[2]),
    .C(_030_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand3_1 _223_ (
    .A(b[2]),
    .B(_015_),
    .C(_017_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(b[3]),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__o21ai_0 _225_ (
    .A1(b[3]),
    .A2(_034_),
    .B1(_026_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o31a_1 _226_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_036_),
    .B1(_019_),
    .X(final_expB[5])
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(b[14]),
    .B(final_expB[5]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _228_ (
    .A(_037_),
    .Y(final_expB[4])
  );
  sky130_fd_sc_hd__and3b_1 _229_ (
    .A_N(b[6]),
    .B(_015_),
    .C(b[5]),
    .X(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _230_ (
    .A(_014_),
    .B(_023_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor3_1 _231_ (
    .A(_020_),
    .B(_038_),
    .C(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a31o_1 _232_ (
    .A1(_019_),
    .A2(_033_),
    .A3(_040_),
    .B1(b[10]),
    .X(final_expB[0])
  );
  sky130_fd_sc_hd__a21oi_1 _233_ (
    .A1(_165_),
    .A2(final_expA[5]),
    .B1(a[13]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _234_ (
    .A(_041_),
    .Y(final_expA[3])
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(_152_),
    .B(_000_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__and3_1 _236_ (
    .A(_146_),
    .B(a[5]),
    .C(_153_),
    .X(_043_)
  );
  sky130_fd_sc_hd__nor3_1 _237_ (
    .A(_162_),
    .B(_042_),
    .C(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a31oi_1 _238_ (
    .A1(_160_),
    .A2(_008_),
    .A3(_044_),
    .B1(a[10]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _239_ (
    .A(_045_),
    .Y(final_expA[0])
  );
  sky130_fd_sc_hd__a21oi_1 _240_ (
    .A1(_019_),
    .A2(_027_),
    .B1(b[11]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _241_ (
    .A(_046_),
    .Y(final_expB[1])
  );
  sky130_fd_sc_hd__a311o_1 _242_ (
    .A1(_164_),
    .A2(_165_),
    .A3(_001_),
    .B1(_158_),
    .C1(_151_),
    .X(_047_)
  );
  sky130_fd_sc_hd__and2_0 _243_ (
    .A(_145_),
    .B(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _244_ (
    .A(_048_),
    .Y(final_expA[1])
  );
  sky130_fd_sc_hd__a31oi_1 _245_ (
    .A1(_019_),
    .A2(_022_),
    .A3(_029_),
    .B1(b[12]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkinv_1 _246_ (
    .A(_049_),
    .Y(final_expB[2])
  );
  sky130_fd_sc_hd__a31oi_1 _247_ (
    .A1(_160_),
    .A2(_164_),
    .A3(_002_),
    .B1(a[12]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _248_ (
    .A(_050_),
    .Y(final_expA[2])
  );
  sky130_fd_sc_hd__nor2_1 _249_ (
    .A(final_expB[0]),
    .B(_045_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a221oi_1 _250_ (
    .A1(_019_),
    .A2(_027_),
    .B1(_047_),
    .B2(_145_),
    .C1(b[11]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xnor2_1 _251_ (
    .A(_046_),
    .B(_048_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(_051_),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(_049_),
    .B(final_expA[2]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__xnor2_1 _254_ (
    .A(_049_),
    .B(_050_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xnor3_1 _255_ (
    .A(_049_),
    .B(_050_),
    .C(_052_),
    .X(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _256_ (
    .A(_054_),
    .B(_057_),
    .Y(tentative_exp[2])
  );
  sky130_fd_sc_hd__a21o_1 _257_ (
    .A1(_026_),
    .A2(final_expB[5]),
    .B1(b[13]),
    .X(final_expB[3])
  );
  sky130_fd_sc_hd__xnor2_1 _258_ (
    .A(_009_),
    .B(_037_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _259_ (
    .A(_041_),
    .SLEEP(final_expB[3]),
    .X(_059_)
  );
  sky130_fd_sc_hd__xor2_1 _260_ (
    .A(_058_),
    .B(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__xnor2_1 _261_ (
    .A(_041_),
    .B(final_expB[3]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a32oi_1 _262_ (
    .A1(_051_),
    .A2(_053_),
    .A3(_057_),
    .B1(_056_),
    .B2(_052_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__maj3_1 _263_ (
    .A(_055_),
    .B(_061_),
    .C(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__maj3_1 _264_ (
    .A(_058_),
    .B(_059_),
    .C(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nand2b_1 _265_ (
    .A_N(final_expA[5]),
    .B(final_expB[5]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(final_expA[5]),
    .B(final_expB[5]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _267_ (
    .A1(final_expA[4]),
    .A2(_037_),
    .B1(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o21ai_0 _268_ (
    .A1(a[14]),
    .A2(_065_),
    .B1(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__xor2_1 _269_ (
    .A(_064_),
    .B(_068_),
    .X(tentative_exp[5])
  );
  sky130_fd_sc_hd__and3_1 _270_ (
    .A(_064_),
    .B(_065_),
    .C(_067_),
    .X(tentative_exp[6])
  );
  sky130_fd_sc_hd__xor2_1 _271_ (
    .A(final_expB[0]),
    .B(_045_),
    .X(tentative_exp[0])
  );
  sky130_fd_sc_hd__nor2_1 _272_ (
    .A(b[8]),
    .B(_019_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _273_ (
    .A(b[7]),
    .SLEEP(_023_),
    .X(_070_)
  );
  sky130_fd_sc_hd__o21ai_0 _274_ (
    .A1(b[5]),
    .A2(b[9]),
    .B1(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a21o_1 _275_ (
    .A1(b[4]),
    .A2(_015_),
    .B1(_023_),
    .X(_072_)
  );
  sky130_fd_sc_hd__o21ai_0 _276_ (
    .A1(_031_),
    .A2(_038_),
    .B1(b[3]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a222oi_1 _277_ (
    .A1(b[0]),
    .A2(_035_),
    .B1(_072_),
    .B2(b[6]),
    .C1(b[2]),
    .C2(_021_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a41oi_1 _278_ (
    .A1(_019_),
    .A2(_071_),
    .A3(_073_),
    .A4(_074_),
    .B1(_069_),
    .Y(final_manB[8])
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(b[2]),
    .B(_038_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(b[6]),
    .B(b[9]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a32o_1 _281_ (
    .A1(b[6]),
    .A2(b[3]),
    .A3(_015_),
    .B1(_020_),
    .B2(b[0]),
    .X(_077_)
  );
  sky130_fd_sc_hd__a222oi_1 _282_ (
    .A1(b[5]),
    .A2(_023_),
    .B1(_024_),
    .B2(b[4]),
    .C1(b[1]),
    .C2(_021_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand4_1 _283_ (
    .A(_019_),
    .B(_075_),
    .C(_076_),
    .D(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o22a_1 _284_ (
    .A1(b[7]),
    .A2(_019_),
    .B1(_077_),
    .B2(_079_),
    .X(final_manB[7])
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(b[6]),
    .B(_019_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand3_1 _286_ (
    .A(b[6]),
    .B(b[2]),
    .C(_015_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a222oi_1 _287_ (
    .A1(b[5]),
    .A2(b[9]),
    .B1(b[3]),
    .B2(_024_),
    .C1(_023_),
    .C2(b[4]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _288_ (
    .A(_081_),
    .B(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a221oi_1 _289_ (
    .A1(b[0]),
    .A2(_021_),
    .B1(_038_),
    .B2(b[1]),
    .C1(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a21oi_1 _290_ (
    .A1(_019_),
    .A2(_084_),
    .B1(_080_),
    .Y(final_manB[6])
  );
  sky130_fd_sc_hd__nand2_1 _291_ (
    .A(b[0]),
    .B(_038_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand3_1 _292_ (
    .A(b[6]),
    .B(b[1]),
    .C(_015_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a222oi_1 _293_ (
    .A1(b[4]),
    .A2(b[9]),
    .B1(b[3]),
    .B2(_023_),
    .C1(_024_),
    .C2(b[2]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(b[5]),
    .B(_019_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a41oi_1 _295_ (
    .A1(_019_),
    .A2(_085_),
    .A3(_086_),
    .A4(_087_),
    .B1(_088_),
    .Y(final_manB[5])
  );
  sky130_fd_sc_hd__nand3_1 _296_ (
    .A(b[0]),
    .B(b[6]),
    .C(_015_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a222oi_1 _297_ (
    .A1(b[9]),
    .A2(b[3]),
    .B1(b[2]),
    .B2(_023_),
    .C1(_024_),
    .C2(b[1]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _298_ (
    .A(b[4]),
    .B(_019_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a31oi_1 _299_ (
    .A1(_019_),
    .A2(_089_),
    .A3(_090_),
    .B1(_091_),
    .Y(final_manB[4])
  );
  sky130_fd_sc_hd__a222oi_1 _300_ (
    .A1(b[9]),
    .A2(b[2]),
    .B1(b[1]),
    .B2(_023_),
    .C1(_024_),
    .C2(b[0]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(b[3]),
    .B(_019_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a21oi_1 _302_ (
    .A1(_019_),
    .A2(_092_),
    .B1(_093_),
    .Y(final_manB[3])
  );
  sky130_fd_sc_hd__a22oi_1 _303_ (
    .A1(b[9]),
    .A2(b[1]),
    .B1(_023_),
    .B2(b[0]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _304_ (
    .A(b[2]),
    .B(_019_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _305_ (
    .A1(_019_),
    .A2(_094_),
    .B1(_095_),
    .Y(final_manB[2])
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(b[0]),
    .B(b[9]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(b[1]),
    .B(_012_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _308_ (
    .A1(_012_),
    .A2(_096_),
    .B1(_097_),
    .Y(final_manB[1])
  );
  sky130_fd_sc_hd__and2_0 _309_ (
    .A(b[0]),
    .B(_012_),
    .X(final_manB[0])
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(a[8]),
    .B(_160_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(a[4]),
    .A2(_153_),
    .B1(_000_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor3b_1 _312_ (
    .A(a[8]),
    .B(a[9]),
    .C_N(a[7]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a222oi_1 _313_ (
    .A1(a[9]),
    .A2(a[7]),
    .B1(_163_),
    .B2(a[2]),
    .C1(_100_),
    .C2(a[5]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _314_ (
    .A1(_006_),
    .A2(_043_),
    .B1(a[3]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o2111ai_1 _315_ (
    .A1(_146_),
    .A2(_099_),
    .B1(_101_),
    .C1(_102_),
    .D1(_160_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a21oi_1 _316_ (
    .A1(a[0]),
    .A2(_004_),
    .B1(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_098_),
    .B(_104_),
    .Y(final_manA[8])
  );
  sky130_fd_sc_hd__nor2_1 _318_ (
    .A(a[7]),
    .B(_160_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a222oi_1 _319_ (
    .A1(a[1]),
    .A2(_163_),
    .B1(_043_),
    .B2(a[2]),
    .C1(a[4]),
    .C2(_100_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(_147_),
    .B(_161_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a222oi_1 _321_ (
    .A1(a[0]),
    .A2(_162_),
    .B1(_000_),
    .B2(a[5]),
    .C1(_107_),
    .C2(a[6]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a31oi_1 _322_ (
    .A1(_160_),
    .A2(_106_),
    .A3(_108_),
    .B1(_105_),
    .Y(final_manA[7])
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(a[6]),
    .B(_160_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a22oi_1 _324_ (
    .A1(a[0]),
    .A2(_163_),
    .B1(_043_),
    .B2(a[1]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a32o_1 _325_ (
    .A1(a[6]),
    .A2(a[2]),
    .A3(_153_),
    .B1(_000_),
    .B2(a[4]),
    .X(_111_)
  );
  sky130_fd_sc_hd__a221oi_1 _326_ (
    .A1(a[5]),
    .A2(a[9]),
    .B1(a[3]),
    .B2(_100_),
    .C1(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a31oi_1 _327_ (
    .A1(_160_),
    .A2(_110_),
    .A3(_112_),
    .B1(_109_),
    .Y(final_manA[6])
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(a[0]),
    .B(_043_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand3_1 _329_ (
    .A(a[6]),
    .B(a[1]),
    .C(_153_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a222oi_1 _330_ (
    .A1(a[4]),
    .A2(a[9]),
    .B1(a[3]),
    .B2(_000_),
    .C1(_100_),
    .C2(a[2]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(a[5]),
    .B(_160_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a41oi_1 _332_ (
    .A1(_160_),
    .A2(_113_),
    .A3(_114_),
    .A4(_115_),
    .B1(_116_),
    .Y(final_manA[5])
  );
  sky130_fd_sc_hd__nand3_1 _333_ (
    .A(a[0]),
    .B(a[6]),
    .C(_153_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a222oi_1 _334_ (
    .A1(a[9]),
    .A2(a[3]),
    .B1(a[2]),
    .B2(_000_),
    .C1(_100_),
    .C2(a[1]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _335_ (
    .A(a[4]),
    .B(_160_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a31oi_1 _336_ (
    .A1(_160_),
    .A2(_117_),
    .A3(_118_),
    .B1(_119_),
    .Y(final_manA[4])
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(a[9]),
    .B(a[2]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a22oi_1 _338_ (
    .A1(a[1]),
    .A2(_000_),
    .B1(_100_),
    .B2(a[0]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(a[3]),
    .B(_160_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a31oi_1 _340_ (
    .A1(_160_),
    .A2(_120_),
    .A3(_121_),
    .B1(_122_),
    .Y(final_manA[3])
  );
  sky130_fd_sc_hd__a22oi_1 _341_ (
    .A1(a[9]),
    .A2(a[1]),
    .B1(_000_),
    .B2(a[0]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(a[2]),
    .B(_160_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a21oi_1 _343_ (
    .A1(_160_),
    .A2(_123_),
    .B1(_124_),
    .Y(final_manA[2])
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(a[1]),
    .B(_151_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(a[0]),
    .B(a[9]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o21ai_0 _346_ (
    .A1(_151_),
    .A2(_126_),
    .B1(_125_),
    .Y(final_manA[1])
  );
  sky130_fd_sc_hd__and2_0 _347_ (
    .A(a[0]),
    .B(_151_),
    .X(final_manA[0])
  );
  sky130_fd_sc_hd__xor2_1 _348_ (
    .A(_051_),
    .B(_053_),
    .X(tentative_exp[1])
  );
  sky130_fd_sc_hd__xnor2_1 _349_ (
    .A(_060_),
    .B(_063_),
    .Y(tentative_exp[4])
  );
  sky130_fd_sc_hd__o2111ai_1 _350_ (
    .A1(b[4]),
    .A2(b[2]),
    .B1(_015_),
    .C1(_016_),
    .D1(b[3]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o211ai_1 _351_ (
    .A1(b[6]),
    .A2(b[4]),
    .B1(_015_),
    .C1(b[5]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _352_ (
    .A1(b[6]),
    .A2(_148_),
    .B1(b[8]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor2_1 _353_ (
    .A(b[0]),
    .B(b[2]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o211ai_1 _354_ (
    .A1(_014_),
    .A2(_129_),
    .B1(_128_),
    .C1(_127_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o31ai_1 _355_ (
    .A1(b[3]),
    .A2(_030_),
    .A3(_130_),
    .B1(_019_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o22a_1 _356_ (
    .A1(b[9]),
    .A2(_019_),
    .B1(_131_),
    .B2(_132_),
    .X(final_manB[9])
  );
  sky130_fd_sc_hd__o2111ai_1 _357_ (
    .A1(a[4]),
    .A2(a[2]),
    .B1(_153_),
    .C1(_155_),
    .D1(a[3]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o211ai_1 _358_ (
    .A1(a[4]),
    .A2(a[6]),
    .B1(a[5]),
    .C1(_153_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _359_ (
    .A1(a[6]),
    .A2(_147_),
    .B1(a[8]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _360_ (
    .A1(_152_),
    .A2(_135_),
    .B1(_134_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _361_ (
    .A(a[0]),
    .B(a[2]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor3_1 _362_ (
    .A(a[3]),
    .B(_005_),
    .C(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _363_ (
    .A(_136_),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor2_1 _364_ (
    .A(a[9]),
    .B(_160_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a31oi_1 _365_ (
    .A1(_160_),
    .A2(_133_),
    .A3(_139_),
    .B1(_140_),
    .Y(final_manA[9])
  );
  sky130_fd_sc_hd__xnor3_1 _366_ (
    .A(_055_),
    .B(_061_),
    .C(_062_),
    .X(tentative_exp[3])
  );
  sky130_fd_sc_hd__xor2_1 _367_ (
    .A(a[15]),
    .B(b[15]),
    .X(final_sign)
  );
  sky130_fd_sc_hd__nor2_1 _368_ (
    .A(_012_),
    .B(_018_),
    .Y(B0)
  );
  sky130_fd_sc_hd__nor2_1 _369_ (
    .A(_151_),
    .B(_159_),
    .Y(A0)
  );
  sky130_fd_sc_hd__and3_1 _370_ (
    .A(b[14]),
    .B(b[13]),
    .C(b[11]),
    .X(_141_)
  );
  sky130_fd_sc_hd__nand3_1 _371_ (
    .A(b[12]),
    .B(b[10]),
    .C(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _372_ (
    .A(_018_),
    .B(_142_),
    .Y(infinB)
  );
  sky130_fd_sc_hd__and3_1 _373_ (
    .A(a[14]),
    .B(a[13]),
    .C(a[11]),
    .X(_143_)
  );
  sky130_fd_sc_hd__nand3_1 _374_ (
    .A(a[12]),
    .B(a[10]),
    .C(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _375_ (
    .A(_159_),
    .B(_144_),
    .Y(infinA)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _376_ (
    .A(_018_),
    .SLEEP(_142_),
    .X(nanB)
  );
  sky130_fd_sc_hd__nor2_1 _377_ (
    .A(_158_),
    .B(_144_),
    .Y(nanA)
  );
  assign sub_expB[6:5] = { sub_expB[4], sub_expB[4] };
  assign sub_expA[6:5] = { sub_expA[4], sub_expA[4] };
  assign signB = b[15];
  assign signA = a[15];
  assign final_expB[6] = final_expB[5];
  assign final_expA[6] = final_expA[5];
  assign final_manB[10] = 1'h1;
  assign final_manA[10] = 1'h1;
endmodule
