/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* top =  1  *)
(* src = "src/fpu_FDIV.sv:4.1-228.10" *)
module DIV(a, b, clk, nanA, nanB, infinA, infinB, A0, B0, out);
  (* src = "src/fpu_FDIV.sv:5.24-5.25" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "src/fpu_FDIV.sv:5.27-5.28" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "src/fpu_FDIV.sv:6.17-6.20" *)
  input clk;
  wire clk;
  (* src = "src/fpu_FDIV.sv:7.17-7.21" *)
  input nanA;
  wire nanA;
  (* src = "src/fpu_FDIV.sv:7.23-7.27" *)
  input nanB;
  wire nanB;
  (* src = "src/fpu_FDIV.sv:7.29-7.35" *)
  input infinA;
  wire infinA;
  (* src = "src/fpu_FDIV.sv:7.37-7.43" *)
  input infinB;
  wire infinB;
  (* src = "src/fpu_FDIV.sv:7.45-7.47" *)
  input A0;
  wire A0;
  (* src = "src/fpu_FDIV.sv:7.49-7.51" *)
  input B0;
  wire B0;
  (* src = "src/fpu_FDIV.sv:8.25-8.28" *)
  output [15:0] out;
  wire [15:0] out;
  (* src = "src/fpu_FDIV.sv:202.5-211.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "src/fpu_FDIV.sv:96.25-96.38" *)
  wire [14:0] B_align_small;
  (* src = "src/fpu_FDIV.sv:81.16-81.31" *)
  wire [10:0] final_manB_reg2;
  (* src = "src/fpu_FDIV.sv:22.10-22.20" *)
  wire final_sign;
  (* hdlname = "fixA a" *)
  (* src = "src/fpu_modules.sv:14.24-14.25" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9" *)
  wire [9:0] \fixA.a ;
  (* hdlname = "fixB a" *)
  (* src = "src/fpu_modules.sv:14.24-14.25" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9" *)
  wire [9:0] \fixB.a ;
  (* src = "src/fpu_FDIV.sv:194.17-194.27" *)
  wire [15:0] normal_ans;
  (* src = "src/fpu_FDIV.sv:16.10-16.15" *)
  wire signA;
  (* src = "src/fpu_FDIV.sv:17.10-17.15" *)
  wire signB;
  (* src = "src/fpu_FDIV.sv:199.21-199.32" *)
  wire [47:0] special_ans;
  (* src = "src/fpu_FDIV.sv:200.15-200.27" *)
  wire [2:0] special_flag;
  (* src = "src/fpu_FDIV.sv:30.18-30.26" *)
  wire [10:0] sub_manA;
  (* src = "src/fpu_FDIV.sv:30.28-30.36" *)
  wire [10:0] sub_manB;
  sky130_fd_sc_hd__and2_0 _03_ (
    .A(special_flag[2]),
    .B(special_ans[46]),
    .X(out[10])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _04_ (
    .A(nanA),
    .SLEEP(nanB),
    .X(_02_)
  );
  sky130_fd_sc_hd__or4_1 _05_ (
    .A(infinA),
    .B(B0),
    .C(nanA),
    .D(nanB),
    .X(_01_)
  );
  sky130_fd_sc_hd__or3_1 _06_ (
    .A(A0),
    .B(infinB),
    .C(_01_),
    .X(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(a[15]),
    .B(b[15]),
    .X(final_sign)
  );
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(final_sign),
    .A1(special_ans[47]),
    .S(special_flag[2]),
    .X(out[15])
  );
  sky130_fd_sc_hd__and2_0 _09_ (
    .A(special_flag[2]),
    .B(special_ans[41]),
    .X(out[9])
  );
  (* src = "src/fpu_FDIV.sv:218.5-221.8" *)
  sky130_fd_sc_hd__dfxtp_1 _10_ (
    .CLK(clk),
    .D(special_ans[25]),
    .Q(special_ans[41])
  );
  (* src = "src/fpu_FDIV.sv:218.5-221.8" *)
  sky130_fd_sc_hd__dfxtp_1 _11_ (
    .CLK(clk),
    .D(special_ans[30]),
    .Q(special_ans[46])
  );
  (* src = "src/fpu_FDIV.sv:218.5-221.8" *)
  sky130_fd_sc_hd__dfxtp_1 _12_ (
    .CLK(clk),
    .D(special_ans[31]),
    .Q(special_ans[47])
  );
  (* src = "src/fpu_FDIV.sv:213.5-216.8" *)
  sky130_fd_sc_hd__dfxtp_1 _13_ (
    .CLK(clk),
    .D(special_ans[9]),
    .Q(special_ans[25])
  );
  (* src = "src/fpu_FDIV.sv:213.5-216.8" *)
  sky130_fd_sc_hd__dfxtp_1 _14_ (
    .CLK(clk),
    .D(special_ans[13]),
    .Q(special_ans[30])
  );
  (* src = "src/fpu_FDIV.sv:213.5-216.8" *)
  sky130_fd_sc_hd__dfxtp_1 _15_ (
    .CLK(clk),
    .D(special_ans[15]),
    .Q(special_ans[31])
  );
  (* src = "src/fpu_FDIV.sv:202.5-211.8" *)
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_02_),
    .Q(special_ans[9])
  );
  (* src = "src/fpu_FDIV.sv:202.5-211.8" *)
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(special_ans[13])
  );
  (* src = "src/fpu_FDIV.sv:202.5-211.8" *)
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(final_sign),
    .Q(special_ans[15])
  );
  (* src = "src/fpu_FDIV.sv:218.5-221.8" *)
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(special_flag[1]),
    .Q(special_flag[2])
  );
  (* src = "src/fpu_FDIV.sv:213.5-216.8" *)
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(special_flag[0]),
    .Q(special_flag[1])
  );
  (* src = "src/fpu_FDIV.sv:202.5-211.8" *)
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_00_),
    .Q(special_flag[0])
  );
  assign B_align_small = 15'b0000xxxxxxxxxxx;
  assign \fixA.a  = a[9:0];
  assign { special_ans[45:42], special_ans[40:32], special_ans[29:26], special_ans[24:16], special_ans[14], special_ans[12:10], special_ans[8:0] } = { special_ans[46], special_ans[46], special_ans[46], special_ans[46], 9'h000, special_ans[30], special_ans[30], special_ans[30], special_ans[30], 9'h000, special_ans[13], special_ans[13], special_ans[13], special_ans[13], 9'h000 };
  assign sub_manB = 11'b1xxxxxxxxxx;
  assign sub_manA = 11'b1xxxxxxxxxx;
  assign normal_ans = { final_sign, 15'h0000 };
  assign signB = b[15];
  assign signA = a[15];
  assign final_manB_reg2 = 11'hxxx;
  assign \fixB.a  = b[9:0];
  assign { out[14:11], out[8:0] } = { out[10], out[10], out[10], out[10], 9'h000 };
endmodule
