/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* top =  1  *)
(* src = "src/fdiv_datapath_blocks.sv:24.1-57.10" *)
module div_region_compare(diff, B_align_signed, q_adjust, sticky_final);
  (* src = "src/fdiv_datapath_blocks.sv:25.32-25.36" *)
  input [27:0] diff;
  wire [27:0] diff;
  (* src = "src/fdiv_datapath_blocks.sv:26.32-26.46" *)
  input [27:0] B_align_signed;
  wire [27:0] B_align_signed;
  (* src = "src/fdiv_datapath_blocks.sv:27.32-27.40" *)
  output [3:0] q_adjust;
  wire [3:0] q_adjust;
  (* src = "src/fdiv_datapath_blocks.sv:28.31-28.43" *)
  output sticky_final;
  wire sticky_final;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  (* src = "src/fdiv_datapath_blocks.sv:30.25-30.29" *)
  wire [27:0] B_x2;
  sky130_fd_sc_hd__clkinv_1 _378_ (
    .A(B_align_signed[26]),
    .Y(_339_)
  );
  sky130_fd_sc_hd__clkinv_1 _379_ (
    .A(diff[27]),
    .Y(_340_)
  );
  sky130_fd_sc_hd__clkinv_1 _380_ (
    .A(B_align_signed[25]),
    .Y(_341_)
  );
  sky130_fd_sc_hd__clkinv_1 _381_ (
    .A(B_align_signed[24]),
    .Y(_342_)
  );
  sky130_fd_sc_hd__clkinv_1 _382_ (
    .A(B_align_signed[22]),
    .Y(_343_)
  );
  sky130_fd_sc_hd__clkinv_1 _383_ (
    .A(B_align_signed[23]),
    .Y(_344_)
  );
  sky130_fd_sc_hd__clkinv_1 _384_ (
    .A(B_align_signed[21]),
    .Y(_345_)
  );
  sky130_fd_sc_hd__clkinv_1 _385_ (
    .A(B_align_signed[20]),
    .Y(_346_)
  );
  sky130_fd_sc_hd__clkinv_1 _386_ (
    .A(B_align_signed[19]),
    .Y(_347_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(B_align_signed[18]),
    .Y(_348_)
  );
  sky130_fd_sc_hd__clkinv_1 _388_ (
    .A(diff[19]),
    .Y(_349_)
  );
  sky130_fd_sc_hd__clkinv_1 _389_ (
    .A(diff[18]),
    .Y(_350_)
  );
  sky130_fd_sc_hd__clkinv_1 _390_ (
    .A(B_align_signed[16]),
    .Y(_351_)
  );
  sky130_fd_sc_hd__clkinv_1 _391_ (
    .A(diff[17]),
    .Y(_352_)
  );
  sky130_fd_sc_hd__clkinv_1 _392_ (
    .A(diff[15]),
    .Y(_353_)
  );
  sky130_fd_sc_hd__clkinv_1 _393_ (
    .A(diff[16]),
    .Y(_354_)
  );
  sky130_fd_sc_hd__clkinv_1 _394_ (
    .A(diff[14]),
    .Y(_355_)
  );
  sky130_fd_sc_hd__clkinv_1 _395_ (
    .A(diff[13]),
    .Y(_356_)
  );
  sky130_fd_sc_hd__clkinv_1 _396_ (
    .A(diff[12]),
    .Y(_357_)
  );
  sky130_fd_sc_hd__clkinv_1 _397_ (
    .A(diff[11]),
    .Y(_358_)
  );
  sky130_fd_sc_hd__clkinv_1 _398_ (
    .A(B_align_signed[10]),
    .Y(_359_)
  );
  sky130_fd_sc_hd__clkinv_1 _399_ (
    .A(diff[10]),
    .Y(_360_)
  );
  sky130_fd_sc_hd__clkinv_1 _400_ (
    .A(B_align_signed[9]),
    .Y(_361_)
  );
  sky130_fd_sc_hd__clkinv_1 _401_ (
    .A(diff[9]),
    .Y(_362_)
  );
  sky130_fd_sc_hd__clkinv_1 _402_ (
    .A(B_align_signed[7]),
    .Y(_363_)
  );
  sky130_fd_sc_hd__clkinv_1 _403_ (
    .A(diff[8]),
    .Y(_364_)
  );
  sky130_fd_sc_hd__clkinv_1 _404_ (
    .A(B_align_signed[6]),
    .Y(_365_)
  );
  sky130_fd_sc_hd__clkinv_1 _405_ (
    .A(diff[6]),
    .Y(_366_)
  );
  sky130_fd_sc_hd__clkinv_1 _406_ (
    .A(B_align_signed[1]),
    .Y(_367_)
  );
  sky130_fd_sc_hd__clkinv_1 _407_ (
    .A(diff[2]),
    .Y(_368_)
  );
  sky130_fd_sc_hd__clkinv_1 _408_ (
    .A(diff[4]),
    .Y(_369_)
  );
  sky130_fd_sc_hd__clkinv_1 _409_ (
    .A(B_align_signed[3]),
    .Y(_370_)
  );
  sky130_fd_sc_hd__clkinv_1 _410_ (
    .A(diff[5]),
    .Y(_371_)
  );
  sky130_fd_sc_hd__clkinv_1 _411_ (
    .A(diff[3]),
    .Y(_372_)
  );
  sky130_fd_sc_hd__clkinv_1 _412_ (
    .A(B_align_signed[2]),
    .Y(_373_)
  );
  sky130_fd_sc_hd__nor2_1 _413_ (
    .A(B_align_signed[26]),
    .B(_340_),
    .Y(_374_)
  );
  sky130_fd_sc_hd__a22o_1 _414_ (
    .A1(_341_),
    .A2(diff[26]),
    .B1(_342_),
    .B2(diff[25]),
    .X(_375_)
  );
  sky130_fd_sc_hd__nand2b_1 _415_ (
    .A_N(diff[26]),
    .B(B_align_signed[25]),
    .Y(_376_)
  );
  sky130_fd_sc_hd__o21ai_0 _416_ (
    .A1(_342_),
    .A2(diff[25]),
    .B1(_376_),
    .Y(_377_)
  );
  sky130_fd_sc_hd__nor2_1 _417_ (
    .A(_375_),
    .B(_377_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xor2_1 _418_ (
    .A(B_align_signed[23]),
    .B(diff[24]),
    .X(_001_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _419_ (
    .A(diff[23]),
    .SLEEP(B_align_signed[22]),
    .X(_002_)
  );
  sky130_fd_sc_hd__o22ai_1 _420_ (
    .A1(diff[23]),
    .A2(_343_),
    .B1(diff[22]),
    .B2(_345_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__or3_1 _421_ (
    .A(_001_),
    .B(_002_),
    .C(_003_),
    .X(_004_)
  );
  sky130_fd_sc_hd__a22oi_1 _422_ (
    .A1(diff[22]),
    .A2(_345_),
    .B1(_346_),
    .B2(diff[21]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__o21ai_0 _423_ (
    .A1(_346_),
    .A2(diff[21]),
    .B1(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _424_ (
    .A(_004_),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a22oi_1 _425_ (
    .A1(_347_),
    .A2(diff[20]),
    .B1(_348_),
    .B2(diff[19]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _426_ (
    .A(_347_),
    .B(diff[20]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _427_ (
    .A1(B_align_signed[18]),
    .A2(_349_),
    .B1(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o22ai_1 _428_ (
    .A1(B_align_signed[17]),
    .A2(_350_),
    .B1(B_align_signed[16]),
    .B2(_352_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _429_ (
    .A(B_align_signed[17]),
    .SLEEP(diff[18]),
    .X(_012_)
  );
  sky130_fd_sc_hd__o2111ai_1 _430_ (
    .A1(_351_),
    .A2(diff[17]),
    .B1(_007_),
    .C1(_008_),
    .D1(_010_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor3_1 _431_ (
    .A(_011_),
    .B(_012_),
    .C(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _432_ (
    .A(diff[11]),
    .B(_359_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__o22ai_1 _433_ (
    .A1(diff[11]),
    .A2(_359_),
    .B1(diff[10]),
    .B2(_361_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o22ai_1 _434_ (
    .A1(_360_),
    .A2(B_align_signed[9]),
    .B1(B_align_signed[8]),
    .B2(_362_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o22ai_1 _435_ (
    .A1(_363_),
    .A2(diff[8]),
    .B1(diff[7]),
    .B2(_365_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _436_ (
    .A(diff[7]),
    .SLEEP(B_align_signed[6]),
    .X(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _437_ (
    .A(_366_),
    .B(B_align_signed[5]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2b_1 _438_ (
    .A_N(diff[1]),
    .B(B_align_signed[0]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _439_ (
    .A(B_align_signed[1]),
    .B(_368_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a22o_1 _440_ (
    .A1(_369_),
    .A2(B_align_signed[3]),
    .B1(_371_),
    .B2(B_align_signed[4]),
    .X(_023_)
  );
  sky130_fd_sc_hd__a221oi_1 _441_ (
    .A1(B_align_signed[1]),
    .A2(_368_),
    .B1(_372_),
    .B2(B_align_signed[2]),
    .C1(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o21ai_0 _442_ (
    .A1(_021_),
    .A2(_022_),
    .B1(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o22ai_1 _443_ (
    .A1(_366_),
    .A2(B_align_signed[5]),
    .B1(_371_),
    .B2(B_align_signed[4]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a221oi_1 _444_ (
    .A1(diff[4]),
    .A2(_370_),
    .B1(diff[3]),
    .B2(_373_),
    .C1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _445_ (
    .A(_023_),
    .SLEEP(_026_),
    .X(_028_)
  );
  sky130_fd_sc_hd__o21ai_0 _446_ (
    .A1(_027_),
    .A2(_028_),
    .B1(_025_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _447_ (
    .A1(_020_),
    .A2(_029_),
    .B1(_019_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o22ai_1 _448_ (
    .A1(B_align_signed[7]),
    .A2(_364_),
    .B1(_018_),
    .B2(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _449_ (
    .A(B_align_signed[8]),
    .B(_362_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _450_ (
    .A1(_031_),
    .A2(_032_),
    .B1(_017_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o221ai_1 _451_ (
    .A1(B_align_signed[11]),
    .A2(_357_),
    .B1(_016_),
    .B2(_033_),
    .C1(_015_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xnor2_1 _452_ (
    .A(B_align_signed[15]),
    .B(diff[16]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2b_1 _453_ (
    .A_N(B_align_signed[14]),
    .B(diff[15]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a22oi_1 _454_ (
    .A1(_353_),
    .A2(B_align_signed[14]),
    .B1(_355_),
    .B2(B_align_signed[13]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand3_1 _455_ (
    .A(_035_),
    .B(_036_),
    .C(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o22ai_1 _456_ (
    .A1(_355_),
    .A2(B_align_signed[13]),
    .B1(B_align_signed[12]),
    .B2(_356_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a211oi_1 _457_ (
    .A1(B_align_signed[12]),
    .A2(_356_),
    .B1(_038_),
    .C1(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _458_ (
    .A(B_align_signed[11]),
    .B(_357_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand3_1 _459_ (
    .A(_034_),
    .B(_040_),
    .C(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _460_ (
    .A(_039_),
    .SLEEP(_038_),
    .X(_043_)
  );
  sky130_fd_sc_hd__maj3_1 _461_ (
    .A(B_align_signed[15]),
    .B(_354_),
    .C(_036_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _462_ (
    .A(_042_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o21ai_0 _463_ (
    .A1(_043_),
    .A2(_045_),
    .B1(_014_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand3_1 _464_ (
    .A(_008_),
    .B(_010_),
    .C(_011_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o22ai_1 _465_ (
    .A1(_008_),
    .A2(_009_),
    .B1(_012_),
    .B2(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__maj3_1 _466_ (
    .A(_344_),
    .B(diff[24]),
    .C(_002_),
    .X(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _467_ (
    .A1(_007_),
    .A2(_048_),
    .B1(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o211ai_1 _468_ (
    .A1(_004_),
    .A2(_005_),
    .B1(_046_),
    .C1(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _469_ (
    .A(_339_),
    .B(diff[27]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a221oi_1 _470_ (
    .A1(_375_),
    .A2(_376_),
    .B1(_000_),
    .B2(_051_),
    .C1(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _471_ (
    .A(_374_),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _472_ (
    .A(B_align_signed[1]),
    .B(B_align_signed[0]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__or4_1 _473_ (
    .A(B_align_signed[1]),
    .B(B_align_signed[0]),
    .C(B_align_signed[3]),
    .D(B_align_signed[2]),
    .X(_056_)
  );
  sky130_fd_sc_hd__nor2_1 _474_ (
    .A(B_align_signed[4]),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__or4_1 _475_ (
    .A(B_align_signed[6]),
    .B(B_align_signed[5]),
    .C(B_align_signed[4]),
    .D(_056_),
    .X(_058_)
  );
  sky130_fd_sc_hd__nor3_1 _476_ (
    .A(B_align_signed[8]),
    .B(B_align_signed[7]),
    .C(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor4_1 _477_ (
    .A(B_align_signed[9]),
    .B(B_align_signed[8]),
    .C(B_align_signed[7]),
    .D(_058_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _478_ (
    .A(_359_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor3b_1 _479_ (
    .A(B_align_signed[11]),
    .B(B_align_signed[10]),
    .C_N(_060_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or4b_1 _480_ (
    .A(B_align_signed[12]),
    .B(B_align_signed[11]),
    .C(B_align_signed[10]),
    .D_N(_060_),
    .X(_063_)
  );
  sky130_fd_sc_hd__nor3_1 _481_ (
    .A(B_align_signed[14]),
    .B(B_align_signed[13]),
    .C(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__or3_1 _482_ (
    .A(B_align_signed[14]),
    .B(B_align_signed[13]),
    .C(_063_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nor4_1 _483_ (
    .A(B_align_signed[14]),
    .B(B_align_signed[15]),
    .C(B_align_signed[13]),
    .D(_063_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor3_1 _484_ (
    .A(B_align_signed[16]),
    .B(B_align_signed[15]),
    .C(_065_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor4_1 _485_ (
    .A(B_align_signed[17]),
    .B(B_align_signed[16]),
    .C(B_align_signed[15]),
    .D(_065_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand4b_1 _486_ (
    .A_N(B_align_signed[17]),
    .B(_066_),
    .C(_351_),
    .D(_348_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor3_1 _487_ (
    .A(B_align_signed[20]),
    .B(B_align_signed[19]),
    .C(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor4_1 _488_ (
    .A(B_align_signed[21]),
    .B(B_align_signed[20]),
    .C(B_align_signed[19]),
    .D(_069_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__and3_1 _489_ (
    .A(_343_),
    .B(_344_),
    .C(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__and4_1 _490_ (
    .A(_342_),
    .B(_343_),
    .C(_344_),
    .D(_071_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _491_ (
    .A(_341_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _492_ (
    .A(B_align_signed[26]),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xor2_1 _493_ (
    .A(B_align_signed[27]),
    .B(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hd__and2_0 _494_ (
    .A(diff[27]),
    .B(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _495_ (
    .A(_342_),
    .B(_072_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xnor2_1 _496_ (
    .A(_341_),
    .B(_073_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a22oi_1 _497_ (
    .A1(diff[24]),
    .A2(_078_),
    .B1(_079_),
    .B2(diff[25]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _498_ (
    .A(_348_),
    .B(_068_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__xnor2_1 _499_ (
    .A(B_align_signed[19]),
    .B(_069_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a22o_1 _500_ (
    .A1(diff[18]),
    .A2(_081_),
    .B1(_082_),
    .B2(diff[19]),
    .X(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _501_ (
    .A(diff[19]),
    .B(_082_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xor2_1 _502_ (
    .A(B_align_signed[17]),
    .B(_067_),
    .X(_085_)
  );
  sky130_fd_sc_hd__xnor2_1 _503_ (
    .A(_351_),
    .B(_066_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a22o_1 _504_ (
    .A1(diff[17]),
    .A2(_085_),
    .B1(_086_),
    .B2(diff[16]),
    .X(_087_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _505_ (
    .A(diff[16]),
    .SLEEP(_086_),
    .X(_088_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _506_ (
    .A(diff[17]),
    .SLEEP(_085_),
    .X(_089_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _507_ (
    .A(diff[18]),
    .SLEEP(_081_),
    .X(_090_)
  );
  sky130_fd_sc_hd__o221ai_1 _508_ (
    .A1(diff[18]),
    .A2(_081_),
    .B1(_085_),
    .B2(diff[17]),
    .C1(_088_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__or4_1 _509_ (
    .A(_083_),
    .B(_084_),
    .C(_087_),
    .D(_091_),
    .X(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _510_ (
    .A(B_align_signed[15]),
    .B(_065_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _511_ (
    .A(diff[15]),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _512_ (
    .A(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__o21a_1 _513_ (
    .A1(B_align_signed[13]),
    .A2(_063_),
    .B1(B_align_signed[14]),
    .X(_096_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _514_ (
    .A(_064_),
    .SLEEP(_096_),
    .X(_097_)
  );
  sky130_fd_sc_hd__a22o_1 _515_ (
    .A1(diff[15]),
    .A2(_093_),
    .B1(_097_),
    .B2(diff[14]),
    .X(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _516_ (
    .A(B_align_signed[13]),
    .B(_063_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o22ai_1 _517_ (
    .A1(diff[14]),
    .A2(_097_),
    .B1(_099_),
    .B2(diff[13]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xor2_1 _518_ (
    .A(B_align_signed[12]),
    .B(_062_),
    .X(_101_)
  );
  sky130_fd_sc_hd__a22oi_1 _519_ (
    .A1(diff[13]),
    .A2(_099_),
    .B1(_101_),
    .B2(diff[12]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__xnor2_1 _520_ (
    .A(B_align_signed[11]),
    .B(_061_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o22a_1 _521_ (
    .A1(diff[12]),
    .A2(_101_),
    .B1(_103_),
    .B2(diff[11]),
    .X(_104_)
  );
  sky130_fd_sc_hd__xnor2_1 _522_ (
    .A(_359_),
    .B(_060_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__and2_0 _523_ (
    .A(diff[10]),
    .B(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _524_ (
    .A1(diff[11]),
    .A2(_103_),
    .B1(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__xnor2_1 _525_ (
    .A(_361_),
    .B(_059_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o22a_1 _526_ (
    .A1(diff[10]),
    .A2(_105_),
    .B1(_108_),
    .B2(diff[9]),
    .X(_109_)
  );
  sky130_fd_sc_hd__o21ai_0 _527_ (
    .A1(B_align_signed[7]),
    .A2(_058_),
    .B1(B_align_signed[8]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand2b_1 _528_ (
    .A_N(_059_),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a22o_1 _529_ (
    .A1(diff[9]),
    .A2(_108_),
    .B1(_111_),
    .B2(diff[8]),
    .X(_112_)
  );
  sky130_fd_sc_hd__a221o_1 _530_ (
    .A1(diff[11]),
    .A2(_103_),
    .B1(_109_),
    .B2(_112_),
    .C1(_106_),
    .X(_113_)
  );
  sky130_fd_sc_hd__a21boi_0 _531_ (
    .A1(_104_),
    .A2(_113_),
    .B1_N(_102_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21bai_1 _532_ (
    .A1(_100_),
    .A2(_114_),
    .B1_N(_098_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor2_1 _533_ (
    .A(diff[8]),
    .B(_111_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nor3b_1 _534_ (
    .A(_116_),
    .B(_112_),
    .C_N(_109_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand4_1 _535_ (
    .A(_102_),
    .B(_104_),
    .C(_107_),
    .D(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor4_1 _536_ (
    .A(_094_),
    .B(_098_),
    .C(_100_),
    .D(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o31ai_1 _537_ (
    .A1(B_align_signed[1]),
    .A2(B_align_signed[0]),
    .A3(B_align_signed[2]),
    .B1(B_align_signed[3]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _538_ (
    .A(_056_),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _539_ (
    .A(_373_),
    .B(_055_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a22oi_1 _540_ (
    .A1(diff[3]),
    .A2(_121_),
    .B1(_122_),
    .B2(diff[2]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xnor2_1 _541_ (
    .A(B_align_signed[1]),
    .B(B_align_signed[0]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2b_1 _542_ (
    .A_N(diff[0]),
    .B(B_align_signed[0]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a21oi_1 _543_ (
    .A1(diff[1]),
    .A2(_124_),
    .B1(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o22ai_1 _544_ (
    .A1(diff[2]),
    .A2(_122_),
    .B1(_124_),
    .B2(diff[1]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o21ai_0 _545_ (
    .A1(_126_),
    .A2(_127_),
    .B1(_123_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__xnor2_1 _546_ (
    .A(B_align_signed[7]),
    .B(_058_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _547_ (
    .A(diff[7]),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__xor2_1 _548_ (
    .A(B_align_signed[5]),
    .B(_057_),
    .X(_131_)
  );
  sky130_fd_sc_hd__o31ai_1 _549_ (
    .A1(B_align_signed[5]),
    .A2(B_align_signed[4]),
    .A3(_056_),
    .B1(B_align_signed[6]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _550_ (
    .A(_058_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o221ai_1 _551_ (
    .A1(diff[5]),
    .A2(_131_),
    .B1(_133_),
    .B2(diff[6]),
    .C1(_130_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _552_ (
    .A(diff[6]),
    .B(_133_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__xnor2_1 _553_ (
    .A(B_align_signed[4]),
    .B(_056_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a22oi_1 _554_ (
    .A1(diff[5]),
    .A2(_131_),
    .B1(_136_),
    .B2(diff[4]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _555_ (
    .A(_135_),
    .B(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _556_ (
    .A(diff[3]),
    .B(_121_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o22ai_1 _557_ (
    .A1(diff[7]),
    .A2(_129_),
    .B1(_136_),
    .B2(diff[4]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor3_1 _558_ (
    .A(_134_),
    .B(_138_),
    .C(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o211ai_1 _559_ (
    .A1(diff[3]),
    .A2(_121_),
    .B1(_128_),
    .C1(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _560_ (
    .A(_134_),
    .B(_135_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o211ai_1 _561_ (
    .A1(diff[7]),
    .A2(_129_),
    .B1(_138_),
    .C1(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand3_1 _562_ (
    .A(_130_),
    .B(_142_),
    .C(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a22oi_1 _563_ (
    .A1(_095_),
    .A2(_115_),
    .B1(_119_),
    .B2(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a31oi_1 _564_ (
    .A1(_087_),
    .A2(_089_),
    .A3(_090_),
    .B1(_083_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o22ai_1 _565_ (
    .A1(_092_),
    .A2(_146_),
    .B1(_147_),
    .B2(_084_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__xnor2_1 _566_ (
    .A(_343_),
    .B(_071_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__xnor2_1 _567_ (
    .A(_345_),
    .B(_070_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o22a_1 _568_ (
    .A1(diff[22]),
    .A2(_149_),
    .B1(_150_),
    .B2(diff[21]),
    .X(_151_)
  );
  sky130_fd_sc_hd__o21ai_0 _569_ (
    .A1(B_align_signed[19]),
    .A2(_069_),
    .B1(B_align_signed[20]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand2b_1 _570_ (
    .A_N(_070_),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o21a_1 _571_ (
    .A1(diff[20]),
    .A2(_153_),
    .B1(_151_),
    .X(_154_)
  );
  sky130_fd_sc_hd__a21oi_1 _572_ (
    .A1(_343_),
    .A2(_071_),
    .B1(_344_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _573_ (
    .A(_072_),
    .SLEEP(_155_),
    .X(_156_)
  );
  sky130_fd_sc_hd__a22o_1 _574_ (
    .A1(diff[22]),
    .A2(_149_),
    .B1(_156_),
    .B2(diff[23]),
    .X(_157_)
  );
  sky130_fd_sc_hd__a22o_1 _575_ (
    .A1(diff[21]),
    .A2(_150_),
    .B1(_153_),
    .B2(diff[20]),
    .X(_158_)
  );
  sky130_fd_sc_hd__a221oi_1 _576_ (
    .A1(_148_),
    .A2(_154_),
    .B1(_158_),
    .B2(_151_),
    .C1(_157_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o22ai_1 _577_ (
    .A1(diff[24]),
    .A2(_078_),
    .B1(_156_),
    .B2(diff[23]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o21ai_0 _578_ (
    .A1(_159_),
    .A2(_160_),
    .B1(_080_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__xnor2_1 _579_ (
    .A(B_align_signed[26]),
    .B(_074_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _580_ (
    .A(diff[26]),
    .B(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _581_ (
    .A(diff[25]),
    .B(_079_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2_1 _582_ (
    .A(_163_),
    .B(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _583_ (
    .A(diff[26]),
    .B(_162_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o21ai_0 _584_ (
    .A1(diff[27]),
    .A2(_076_),
    .B1(_166_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a21oi_1 _585_ (
    .A1(_161_),
    .A2(_165_),
    .B1(_167_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _586_ (
    .A(_077_),
    .B(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _587_ (
    .A(_077_),
    .SLEEP(_168_),
    .X(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _588_ (
    .A(diff[27]),
    .B(_162_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a21oi_1 _589_ (
    .A1(diff[26]),
    .A2(_079_),
    .B1(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _590_ (
    .A1(diff[27]),
    .A2(_162_),
    .B1(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a22oi_1 _591_ (
    .A1(diff[25]),
    .A2(_078_),
    .B1(_156_),
    .B2(diff[24]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a22o_1 _592_ (
    .A1(diff[23]),
    .A2(_149_),
    .B1(_150_),
    .B2(diff[22]),
    .X(_175_)
  );
  sky130_fd_sc_hd__a22o_1 _593_ (
    .A1(diff[20]),
    .A2(_082_),
    .B1(_153_),
    .B2(diff[21]),
    .X(_176_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _594_ (
    .A(diff[20]),
    .SLEEP(_082_),
    .X(_177_)
  );
  sky130_fd_sc_hd__o22ai_1 _595_ (
    .A1(diff[19]),
    .A2(_081_),
    .B1(_085_),
    .B2(diff[18]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _596_ (
    .A(diff[19]),
    .B(_081_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a22oi_1 _597_ (
    .A1(diff[17]),
    .A2(_086_),
    .B1(_093_),
    .B2(diff[16]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _598_ (
    .A(diff[17]),
    .B(_086_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__o22ai_1 _599_ (
    .A1(diff[17]),
    .A2(_086_),
    .B1(_093_),
    .B2(diff[16]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a21oi_1 _600_ (
    .A1(diff[18]),
    .A2(_085_),
    .B1(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nand4b_1 _601_ (
    .A_N(_178_),
    .B(_179_),
    .C(_180_),
    .D(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__and2_0 _602_ (
    .A(diff[14]),
    .B(_099_),
    .X(_185_)
  );
  sky130_fd_sc_hd__o32ai_1 _603_ (
    .A1(diff[15]),
    .A2(_064_),
    .A3(_096_),
    .B1(_099_),
    .B2(diff[14]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a211o_1 _604_ (
    .A1(diff[15]),
    .A2(_097_),
    .B1(_185_),
    .C1(_186_),
    .X(_187_)
  );
  sky130_fd_sc_hd__a22o_1 _605_ (
    .A1(diff[13]),
    .A2(_101_),
    .B1(_103_),
    .B2(diff[12]),
    .X(_188_)
  );
  sky130_fd_sc_hd__nor2_1 _606_ (
    .A(diff[13]),
    .B(_101_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _607_ (
    .A(diff[12]),
    .B(_103_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__or3_1 _608_ (
    .A(_188_),
    .B(_189_),
    .C(_190_),
    .X(_191_)
  );
  sky130_fd_sc_hd__a22o_1 _609_ (
    .A1(diff[11]),
    .A2(_105_),
    .B1(_108_),
    .B2(diff[10]),
    .X(_192_)
  );
  sky130_fd_sc_hd__o22ai_1 _610_ (
    .A1(diff[10]),
    .A2(_108_),
    .B1(_111_),
    .B2(diff[9]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a22o_1 _611_ (
    .A1(diff[9]),
    .A2(_111_),
    .B1(_129_),
    .B2(diff[8]),
    .X(_194_)
  );
  sky130_fd_sc_hd__o22ai_1 _612_ (
    .A1(diff[11]),
    .A2(_105_),
    .B1(_129_),
    .B2(diff[8]),
    .Y(_195_)
  );
  sky130_fd_sc_hd__or4_1 _613_ (
    .A(_192_),
    .B(_193_),
    .C(_194_),
    .D(_195_),
    .X(_196_)
  );
  sky130_fd_sc_hd__nor3_1 _614_ (
    .A(_187_),
    .B(_191_),
    .C(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nor2_1 _615_ (
    .A(diff[7]),
    .B(_133_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__a22oi_1 _616_ (
    .A1(diff[6]),
    .A2(_131_),
    .B1(_133_),
    .B2(diff[7]),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nor2_1 _617_ (
    .A(_198_),
    .B(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a22oi_1 _618_ (
    .A1(diff[4]),
    .A2(_121_),
    .B1(_136_),
    .B2(diff[5]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _619_ (
    .A(diff[3]),
    .SLEEP(_122_),
    .X(_202_)
  );
  sky130_fd_sc_hd__a22o_1 _620_ (
    .A1(diff[3]),
    .A2(_122_),
    .B1(_124_),
    .B2(diff[2]),
    .X(_203_)
  );
  sky130_fd_sc_hd__o21a_1 _621_ (
    .A1(diff[2]),
    .A2(_124_),
    .B1(_021_),
    .X(_204_)
  );
  sky130_fd_sc_hd__nand2_1 _622_ (
    .A(_202_),
    .B(_204_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor2_1 _623_ (
    .A(_203_),
    .B(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o221ai_1 _624_ (
    .A1(diff[4]),
    .A2(_121_),
    .B1(_203_),
    .B2(_204_),
    .C1(_202_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _625_ (
    .A(_201_),
    .B(_207_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o22ai_1 _626_ (
    .A1(diff[6]),
    .A2(_131_),
    .B1(_136_),
    .B2(diff[5]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor2_1 _627_ (
    .A(_198_),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__a21oi_1 _628_ (
    .A1(_208_),
    .A2(_210_),
    .B1(_200_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nor4_1 _629_ (
    .A(_187_),
    .B(_191_),
    .C(_196_),
    .D(_211_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _630_ (
    .A(_194_),
    .SLEEP(_193_),
    .X(_213_)
  );
  sky130_fd_sc_hd__o22ai_1 _631_ (
    .A1(diff[11]),
    .A2(_105_),
    .B1(_192_),
    .B2(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor3_1 _632_ (
    .A(_187_),
    .B(_191_),
    .C(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__maj3_1 _633_ (
    .A(diff[15]),
    .B(_097_),
    .C(_185_),
    .X(_216_)
  );
  sky130_fd_sc_hd__nor3b_1 _634_ (
    .A(_189_),
    .B(_187_),
    .C_N(_188_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nor4_1 _635_ (
    .A(_212_),
    .B(_215_),
    .C(_216_),
    .D(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nor2_1 _636_ (
    .A(_180_),
    .B(_181_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__a21oi_1 _637_ (
    .A1(diff[18]),
    .A2(_085_),
    .B1(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__o221ai_1 _638_ (
    .A1(_184_),
    .A2(_218_),
    .B1(_220_),
    .B2(_178_),
    .C1(_179_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__a21oi_1 _639_ (
    .A1(_177_),
    .A2(_221_),
    .B1(_176_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__o22ai_1 _640_ (
    .A1(diff[22]),
    .A2(_150_),
    .B1(_153_),
    .B2(diff[21]),
    .Y(_223_)
  );
  sky130_fd_sc_hd__o21ba_1 _641_ (
    .A1(_222_),
    .A2(_223_),
    .B1_N(_175_),
    .X(_224_)
  );
  sky130_fd_sc_hd__o22ai_1 _642_ (
    .A1(diff[23]),
    .A2(_149_),
    .B1(_156_),
    .B2(diff[24]),
    .Y(_225_)
  );
  sky130_fd_sc_hd__o21ai_0 _643_ (
    .A1(_224_),
    .A2(_225_),
    .B1(_174_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__o22ai_1 _644_ (
    .A1(diff[25]),
    .A2(_078_),
    .B1(_079_),
    .B2(diff[26]),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a21oi_1 _645_ (
    .A1(diff[27]),
    .A2(_162_),
    .B1(_227_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__a21oi_1 _646_ (
    .A1(_226_),
    .A2(_228_),
    .B1(_173_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nor2_1 _647_ (
    .A(_340_),
    .B(B_align_signed[27]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__a22oi_1 _648_ (
    .A1(_339_),
    .A2(diff[26]),
    .B1(B_align_signed[27]),
    .B2(_340_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__o22ai_1 _649_ (
    .A1(_339_),
    .A2(diff[26]),
    .B1(diff[25]),
    .B2(_341_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__a22oi_1 _650_ (
    .A1(_341_),
    .A2(diff[25]),
    .B1(diff[24]),
    .B2(_342_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__o21a_1 _651_ (
    .A1(_232_),
    .A2(_233_),
    .B1(_231_),
    .X(_234_)
  );
  sky130_fd_sc_hd__o211ai_1 _652_ (
    .A1(_342_),
    .A2(diff[24]),
    .B1(_231_),
    .C1(_233_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nor3_1 _653_ (
    .A(_230_),
    .B(_232_),
    .C(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__xor2_1 _654_ (
    .A(diff[23]),
    .B(B_align_signed[23]),
    .X(_237_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _655_ (
    .A(diff[22]),
    .SLEEP(B_align_signed[22]),
    .X(_238_)
  );
  sky130_fd_sc_hd__o22ai_1 _656_ (
    .A1(_343_),
    .A2(diff[22]),
    .B1(_345_),
    .B2(diff[21]),
    .Y(_239_)
  );
  sky130_fd_sc_hd__or3_1 _657_ (
    .A(_237_),
    .B(_238_),
    .C(_239_),
    .X(_240_)
  );
  sky130_fd_sc_hd__a22oi_1 _658_ (
    .A1(_345_),
    .A2(diff[21]),
    .B1(diff[20]),
    .B2(_346_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__o21ai_0 _659_ (
    .A1(_346_),
    .A2(diff[20]),
    .B1(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor2_1 _660_ (
    .A(_240_),
    .B(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__o22ai_1 _661_ (
    .A1(B_align_signed[17]),
    .A2(_352_),
    .B1(_354_),
    .B2(B_align_signed[16]),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nor2_1 _662_ (
    .A(B_align_signed[19]),
    .B(_349_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__xor2_1 _663_ (
    .A(B_align_signed[18]),
    .B(diff[18]),
    .X(_246_)
  );
  sky130_fd_sc_hd__nor2_1 _664_ (
    .A(_347_),
    .B(diff[19]),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a2111oi_0 _665_ (
    .A1(B_align_signed[17]),
    .A2(_352_),
    .B1(_245_),
    .C1(_246_),
    .D1(_247_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__and2_0 _666_ (
    .A(_244_),
    .B(_248_),
    .X(_249_)
  );
  sky130_fd_sc_hd__nor3_1 _667_ (
    .A(B_align_signed[18]),
    .B(_350_),
    .C(_247_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__a22o_1 _668_ (
    .A1(B_align_signed[13]),
    .A2(_356_),
    .B1(_357_),
    .B2(B_align_signed[12]),
    .X(_251_)
  );
  sky130_fd_sc_hd__o22ai_1 _669_ (
    .A1(B_align_signed[9]),
    .A2(_362_),
    .B1(_364_),
    .B2(B_align_signed[8]),
    .Y(_252_)
  );
  sky130_fd_sc_hd__a22o_1 _670_ (
    .A1(_353_),
    .A2(B_align_signed[15]),
    .B1(_355_),
    .B2(B_align_signed[14]),
    .X(_253_)
  );
  sky130_fd_sc_hd__o22ai_1 _671_ (
    .A1(B_align_signed[14]),
    .A2(_355_),
    .B1(B_align_signed[13]),
    .B2(_356_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nor4_1 _672_ (
    .A(_251_),
    .B(_252_),
    .C(_253_),
    .D(_254_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o22ai_1 _673_ (
    .A1(B_align_signed[11]),
    .A2(_358_),
    .B1(B_align_signed[10]),
    .B2(_360_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nand2_1 _674_ (
    .A(B_align_signed[11]),
    .B(_358_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__o21ai_0 _675_ (
    .A1(_359_),
    .A2(diff[10]),
    .B1(_257_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nor2_1 _676_ (
    .A(_256_),
    .B(_258_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nor2_1 _677_ (
    .A(B_align_signed[12]),
    .B(_357_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nor2_1 _678_ (
    .A(_361_),
    .B(diff[9]),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor2_1 _679_ (
    .A(_353_),
    .B(B_align_signed[15]),
    .Y(_262_)
  );
  sky130_fd_sc_hd__a2111oi_0 _680_ (
    .A1(B_align_signed[8]),
    .A2(_364_),
    .B1(_260_),
    .C1(_261_),
    .D1(_262_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nand3_1 _681_ (
    .A(_255_),
    .B(_259_),
    .C(_263_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__xor2_1 _682_ (
    .A(B_align_signed[7]),
    .B(diff[7]),
    .X(_265_)
  );
  sky130_fd_sc_hd__nor2_1 _683_ (
    .A(B_align_signed[6]),
    .B(_366_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__a22o_1 _684_ (
    .A1(B_align_signed[6]),
    .A2(_366_),
    .B1(B_align_signed[5]),
    .B2(_371_),
    .X(_267_)
  );
  sky130_fd_sc_hd__nor3_1 _685_ (
    .A(_265_),
    .B(_266_),
    .C(_267_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__o22ai_1 _686_ (
    .A1(B_align_signed[5]),
    .A2(_371_),
    .B1(B_align_signed[4]),
    .B2(_369_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__a21oi_1 _687_ (
    .A1(_369_),
    .A2(B_align_signed[4]),
    .B1(_269_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand2_1 _688_ (
    .A(_268_),
    .B(_270_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _689_ (
    .A(diff[1]),
    .SLEEP(B_align_signed[1]),
    .X(_272_)
  );
  sky130_fd_sc_hd__o22ai_1 _690_ (
    .A1(B_align_signed[3]),
    .A2(_372_),
    .B1(B_align_signed[2]),
    .B2(_368_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__o22ai_1 _691_ (
    .A1(_367_),
    .A2(diff[1]),
    .B1(_370_),
    .B2(diff[3]),
    .Y(_274_)
  );
  sky130_fd_sc_hd__a211oi_1 _692_ (
    .A1(_368_),
    .A2(B_align_signed[2]),
    .B1(_273_),
    .C1(_274_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__o21ai_0 _693_ (
    .A1(_125_),
    .A2(_272_),
    .B1(_275_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__o21ai_0 _694_ (
    .A1(_370_),
    .A2(diff[3]),
    .B1(_273_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__a21oi_1 _695_ (
    .A1(_276_),
    .A2(_277_),
    .B1(_271_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__maj3_1 _696_ (
    .A(_363_),
    .B(diff[7]),
    .C(_266_),
    .X(_279_)
  );
  sky130_fd_sc_hd__a211oi_1 _697_ (
    .A1(_268_),
    .A2(_269_),
    .B1(_278_),
    .C1(_279_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__nor2_1 _698_ (
    .A(_264_),
    .B(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__o211ai_1 _699_ (
    .A1(_361_),
    .A2(diff[9]),
    .B1(_252_),
    .C1(_259_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__a21oi_1 _700_ (
    .A1(_256_),
    .A2(_257_),
    .B1(_260_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__a21oi_1 _701_ (
    .A1(_282_),
    .A2(_283_),
    .B1(_251_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nor2_1 _702_ (
    .A(_254_),
    .B(_284_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__nor2_1 _703_ (
    .A(_253_),
    .B(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__nor3_1 _704_ (
    .A(_262_),
    .B(_281_),
    .C(_286_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__a21oi_1 _705_ (
    .A1(B_align_signed[16]),
    .A2(_354_),
    .B1(_244_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__maj3_1 _706_ (
    .A(diff[23]),
    .B(_344_),
    .C(_238_),
    .X(_289_)
  );
  sky130_fd_sc_hd__nor2_1 _707_ (
    .A(_240_),
    .B(_241_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__nand3_1 _708_ (
    .A(_243_),
    .B(_248_),
    .C(_288_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__o31a_1 _709_ (
    .A1(_245_),
    .A2(_249_),
    .A3(_250_),
    .B1(_243_),
    .X(_292_)
  );
  sky130_fd_sc_hd__nor3_1 _710_ (
    .A(_289_),
    .B(_290_),
    .C(_292_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__o21ai_0 _711_ (
    .A1(_287_),
    .A2(_291_),
    .B1(_293_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _712_ (
    .A1_N(_230_),
    .A2_N(_234_),
    .B1(_236_),
    .B2(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__nand2_1 _713_ (
    .A(diff[27]),
    .B(_295_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__a21oi_1 _714_ (
    .A1(_170_),
    .A2(_229_),
    .B1(_296_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _715_ (
    .A(_054_),
    .SLEEP(_297_),
    .X(q_adjust[1])
  );
  sky130_fd_sc_hd__o21ai_0 _716_ (
    .A1(_169_),
    .A2(_229_),
    .B1(diff[27]),
    .Y(_298_)
  );
  sky130_fd_sc_hd__a21oi_1 _717_ (
    .A1(_295_),
    .A2(_298_),
    .B1(_054_),
    .Y(q_adjust[0])
  );
  sky130_fd_sc_hd__o21ai_0 _718_ (
    .A1(diff[1]),
    .A2(diff[0]),
    .B1(_125_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__o2111a_1 _719_ (
    .A1(diff[4]),
    .A2(_121_),
    .B1(_201_),
    .C1(_206_),
    .D1(_299_),
    .X(_300_)
  );
  sky130_fd_sc_hd__nand4_1 _720_ (
    .A(_197_),
    .B(_199_),
    .C(_210_),
    .D(_300_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__or4b_1 _721_ (
    .A(_176_),
    .B(_184_),
    .C(_301_),
    .D_N(_177_),
    .X(_302_)
  );
  sky130_fd_sc_hd__nor4_1 _722_ (
    .A(_175_),
    .B(_223_),
    .C(_225_),
    .D(_302_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__nand4_1 _723_ (
    .A(_172_),
    .B(_174_),
    .C(_228_),
    .D(_303_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__o21ai_0 _724_ (
    .A1(_077_),
    .A2(_168_),
    .B1(_304_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__xor2_1 _725_ (
    .A(B_align_signed[0]),
    .B(diff[0]),
    .X(_306_)
  );
  sky130_fd_sc_hd__a2111oi_0 _726_ (
    .A1(diff[1]),
    .A2(_124_),
    .B1(_127_),
    .C1(_139_),
    .D1(_306_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__nand4_1 _727_ (
    .A(_119_),
    .B(_123_),
    .C(_141_),
    .D(_307_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__nor3_1 _728_ (
    .A(_092_),
    .B(_158_),
    .C(_308_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__nand3b_1 _729_ (
    .A_N(_164_),
    .B(_309_),
    .C(_154_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__nor2_1 _730_ (
    .A(_157_),
    .B(_160_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__nand2_1 _731_ (
    .A(_080_),
    .B(_311_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__nor4_1 _732_ (
    .A(_163_),
    .B(_167_),
    .C(_310_),
    .D(_312_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__or3_1 _733_ (
    .A(_077_),
    .B(_168_),
    .C(_313_),
    .X(_314_)
  );
  sky130_fd_sc_hd__nor4_1 _734_ (
    .A(diff[4]),
    .B(diff[5]),
    .C(diff[3]),
    .D(diff[0]),
    .Y(_315_)
  );
  sky130_fd_sc_hd__nor4_1 _735_ (
    .A(diff[7]),
    .B(diff[6]),
    .C(diff[2]),
    .D(diff[1]),
    .Y(_316_)
  );
  sky130_fd_sc_hd__nor4_1 _736_ (
    .A(diff[11]),
    .B(diff[10]),
    .C(diff[9]),
    .D(diff[8]),
    .Y(_317_)
  );
  sky130_fd_sc_hd__nand3_1 _737_ (
    .A(_315_),
    .B(_316_),
    .C(_317_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__nor4_1 _738_ (
    .A(diff[24]),
    .B(diff[22]),
    .C(diff[21]),
    .D(diff[20]),
    .Y(_319_)
  );
  sky130_fd_sc_hd__nor4_1 _739_ (
    .A(diff[27]),
    .B(diff[26]),
    .C(diff[25]),
    .D(diff[23]),
    .Y(_320_)
  );
  sky130_fd_sc_hd__nor4_1 _740_ (
    .A(diff[16]),
    .B(diff[14]),
    .C(diff[13]),
    .D(diff[12]),
    .Y(_321_)
  );
  sky130_fd_sc_hd__nor4_1 _741_ (
    .A(diff[19]),
    .B(diff[18]),
    .C(diff[17]),
    .D(diff[15]),
    .Y(_322_)
  );
  sky130_fd_sc_hd__nand4_1 _742_ (
    .A(_319_),
    .B(_320_),
    .C(_321_),
    .D(_322_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__o21ai_0 _743_ (
    .A1(_318_),
    .A2(_323_),
    .B1(_295_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__a31oi_1 _744_ (
    .A1(diff[27]),
    .A2(_305_),
    .A3(_314_),
    .B1(_324_),
    .Y(_325_)
  );
  sky130_fd_sc_hd__nor2_1 _745_ (
    .A(_272_),
    .B(_306_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__nor3_1 _746_ (
    .A(_264_),
    .B(_271_),
    .C(_291_),
    .Y(_327_)
  );
  sky130_fd_sc_hd__a41oi_1 _747_ (
    .A1(_236_),
    .A2(_275_),
    .A3(_326_),
    .A4(_327_),
    .B1(_295_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__nand2_1 _748_ (
    .A(_032_),
    .B(_041_),
    .Y(_329_)
  );
  sky130_fd_sc_hd__nor2_1 _749_ (
    .A(_052_),
    .B(_329_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__nand4_1 _750_ (
    .A(_000_),
    .B(_024_),
    .C(_027_),
    .D(_330_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__or4b_1 _751_ (
    .A(_016_),
    .B(_017_),
    .C(_018_),
    .D_N(_299_),
    .X(_332_)
  );
  sky130_fd_sc_hd__nor2_1 _752_ (
    .A(_019_),
    .B(_022_),
    .Y(_333_)
  );
  sky130_fd_sc_hd__nand3_1 _753_ (
    .A(_020_),
    .B(_021_),
    .C(_333_),
    .Y(_334_)
  );
  sky130_fd_sc_hd__a21oi_1 _754_ (
    .A1(_363_),
    .A2(diff[8]),
    .B1(_374_),
    .Y(_335_)
  );
  sky130_fd_sc_hd__o211ai_1 _755_ (
    .A1(B_align_signed[11]),
    .A2(_357_),
    .B1(_015_),
    .C1(_335_),
    .Y(_336_)
  );
  sky130_fd_sc_hd__nor4_1 _756_ (
    .A(_331_),
    .B(_332_),
    .C(_334_),
    .D(_336_),
    .Y(_337_)
  );
  sky130_fd_sc_hd__nand3_1 _757_ (
    .A(_014_),
    .B(_040_),
    .C(_337_),
    .Y(_338_)
  );
  sky130_fd_sc_hd__o31a_1 _758_ (
    .A1(_054_),
    .A2(_325_),
    .A3(_328_),
    .B1(_338_),
    .X(sticky_final)
  );
  sky130_fd_sc_hd__nor2_1 _759_ (
    .A(_054_),
    .B(_296_),
    .Y(q_adjust[2])
  );
  assign B_x2 = { B_align_signed[26:0], 1'h0 };
  assign q_adjust[3] = q_adjust[2];
endmodule
