/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* top =  1  *)
(* src = "src/fdiv_datapath_blocks.sv:72.1-98.10" *)
module div_norm(prod, tentative_exp, normalised_exp, normalised_prod, underflow, underflow_amt, tentative_S, underflow_man);
  (* src = "src/fdiv_datapath_blocks.sv:73.25-73.29" *)
  input [24:0] prod;
  wire [24:0] prod;
  (* src = "src/fdiv_datapath_blocks.sv:74.25-74.38" *)
  input [6:0] tentative_exp;
  wire [6:0] tentative_exp;
  (* src = "src/fdiv_datapath_blocks.sv:75.25-75.39" *)
  output [6:0] normalised_exp;
  wire [6:0] normalised_exp;
  (* src = "src/fdiv_datapath_blocks.sv:76.25-76.40" *)
  output [24:0] normalised_prod;
  wire [24:0] normalised_prod;
  (* src = "src/fdiv_datapath_blocks.sv:77.25-77.34" *)
  output underflow;
  wire underflow;
  (* src = "src/fdiv_datapath_blocks.sv:78.25-78.38" *)
  output [6:0] underflow_amt;
  wire [6:0] underflow_amt;
  (* src = "src/fdiv_datapath_blocks.sv:79.25-79.36" *)
  output tentative_S;
  wire tentative_S;
  (* src = "src/fdiv_datapath_blocks.sv:80.25-80.38" *)
  output [24:0] underflow_man;
  wire [24:0] underflow_man;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  (* src = "src/fdiv_datapath_blocks.sv:95.18-95.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23" *)
  wire [24:0] underflow_prod;
  sky130_fd_sc_hd__xor2_1 _304_ (
    .A(tentative_exp[0]),
    .B(prod[23]),
    .X(_303_)
  );
  sky130_fd_sc_hd__clkinv_1 _305_ (
    .A(_303_),
    .Y(normalised_exp[0])
  );
  sky130_fd_sc_hd__nor3_1 _306_ (
    .A(tentative_exp[0]),
    .B(prod[23]),
    .C(tentative_exp[1]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__or4_1 _307_ (
    .A(tentative_exp[0]),
    .B(prod[23]),
    .C(tentative_exp[1]),
    .D(tentative_exp[2]),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _308_ (
    .A(tentative_exp[3]),
    .B(_001_),
    .Y(normalised_exp[3])
  );
  sky130_fd_sc_hd__nor3_1 _309_ (
    .A(tentative_exp[3]),
    .B(tentative_exp[4]),
    .C(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor4_1 _310_ (
    .A(tentative_exp[3]),
    .B(tentative_exp[4]),
    .C(tentative_exp[5]),
    .D(_001_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xnor2_1 _311_ (
    .A(tentative_exp[6]),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _312_ (
    .A(_004_),
    .Y(normalised_exp[6])
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(tentative_exp[1]),
    .B(normalised_exp[0]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor3_1 _314_ (
    .A(tentative_exp[1]),
    .B(tentative_exp[2]),
    .C(normalised_exp[0]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _315_ (
    .A(_004_),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _316_ (
    .A(normalised_exp[3]),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _317_ (
    .A(_008_),
    .Y(underflow_amt[3])
  );
  sky130_fd_sc_hd__xor2_1 _318_ (
    .A(tentative_exp[2]),
    .B(_000_),
    .X(normalised_exp[2])
  );
  sky130_fd_sc_hd__o21ai_0 _319_ (
    .A1(tentative_exp[1]),
    .A2(normalised_exp[0]),
    .B1(normalised_exp[2]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a22oi_1 _320_ (
    .A1(_004_),
    .A2(normalised_exp[2]),
    .B1(_009_),
    .B2(_007_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _321_ (
    .A(_010_),
    .Y(underflow_amt[2])
  );
  sky130_fd_sc_hd__xnor2_1 _322_ (
    .A(tentative_exp[5]),
    .B(_002_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _323_ (
    .A(_011_),
    .Y(normalised_exp[5])
  );
  sky130_fd_sc_hd__o21a_1 _324_ (
    .A1(tentative_exp[3]),
    .A2(_001_),
    .B1(tentative_exp[4]),
    .X(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(_002_),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(_013_),
    .Y(normalised_exp[4])
  );
  sky130_fd_sc_hd__nor2b_1 _327_ (
    .A(normalised_exp[3]),
    .B_N(_006_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21oi_1 _328_ (
    .A1(_013_),
    .A2(_014_),
    .B1(_004_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _329_ (
    .A(normalised_exp[5]),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _330_ (
    .A(_016_),
    .Y(underflow_amt[5])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _331_ (
    .A(_004_),
    .SLEEP(_014_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _332_ (
    .A(_013_),
    .B(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _333_ (
    .A(_018_),
    .Y(underflow_amt[4])
  );
  sky130_fd_sc_hd__nand3_1 _334_ (
    .A(_011_),
    .B(_013_),
    .C(_014_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand4_1 _335_ (
    .A(normalised_exp[6]),
    .B(_011_),
    .C(_013_),
    .D(_014_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _336_ (
    .A(_020_),
    .Y(underflow_amt[6])
  );
  sky130_fd_sc_hd__o21ai_0 _337_ (
    .A1(tentative_exp[0]),
    .A2(prod[23]),
    .B1(tentative_exp[1]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2b_1 _338_ (
    .A_N(_000_),
    .B(_021_),
    .Y(normalised_exp[1])
  );
  sky130_fd_sc_hd__and3_1 _339_ (
    .A(normalised_exp[0]),
    .B(normalised_exp[6]),
    .C(normalised_exp[1]),
    .X(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _340_ (
    .A1(normalised_exp[0]),
    .A2(normalised_exp[6]),
    .B1(normalised_exp[1]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _341_ (
    .A(_022_),
    .SLEEP(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _342_ (
    .A(_024_),
    .Y(underflow_amt[1])
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(prod[23]),
    .B(prod[22]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _344_ (
    .A(_025_),
    .Y(normalised_prod[23])
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(_004_),
    .B(_019_),
    .Y(underflow)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(prod[23]),
    .B(prod[24]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _347_ (
    .A(_026_),
    .Y(normalised_prod[24])
  );
  sky130_fd_sc_hd__nor3_1 _348_ (
    .A(tentative_exp[0]),
    .B(underflow_amt[6]),
    .C(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__and3_1 _349_ (
    .A(_010_),
    .B(_024_),
    .C(_027_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(_008_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(underflow_amt[5]),
    .B(underflow_amt[4]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(_016_),
    .B(_018_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o22ai_1 _353_ (
    .A1(_025_),
    .A2(underflow),
    .B1(_029_),
    .B2(_031_),
    .Y(underflow_man[23])
  );
  sky130_fd_sc_hd__mux2_1 _354_ (
    .A0(prod[21]),
    .A1(prod[22]),
    .S(prod[23]),
    .X(normalised_prod[22])
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(underflow_amt[6]),
    .B(_025_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a32o_1 _356_ (
    .A1(tentative_exp[0]),
    .A2(_020_),
    .A3(normalised_prod[24]),
    .B1(_032_),
    .B2(_303_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _357_ (
    .A(_024_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _358_ (
    .A(underflow_amt[2]),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(_008_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21boi_0 _360_ (
    .A1(normalised_exp[5]),
    .A2(_015_),
    .B1_N(_019_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _361_ (
    .A(underflow_amt[4]),
    .SLEEP(_037_),
    .X(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _362_ (
    .A(_036_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a31o_1 _363_ (
    .A1(_004_),
    .A2(_019_),
    .A3(normalised_prod[22]),
    .B1(_039_),
    .X(underflow_man[22])
  );
  sky130_fd_sc_hd__mux2i_1 _364_ (
    .A0(prod[20]),
    .A1(prod[21]),
    .S(prod[23]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _365_ (
    .A(_040_),
    .Y(normalised_prod[21])
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(_020_),
    .B(normalised_prod[22]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(_303_),
    .B(_032_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a21oi_1 _368_ (
    .A1(_303_),
    .A2(_041_),
    .B1(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__mux2i_1 _369_ (
    .A0(_027_),
    .A1(_043_),
    .S(_024_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _370_ (
    .A(underflow_amt[2]),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _371_ (
    .A(_008_),
    .B(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o22ai_1 _372_ (
    .A1(underflow),
    .A2(_040_),
    .B1(_046_),
    .B2(_038_),
    .Y(underflow_man[21])
  );
  sky130_fd_sc_hd__mux2i_1 _373_ (
    .A0(prod[19]),
    .A1(prod[20]),
    .S(prod[23]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__clkinv_1 _374_ (
    .A(_047_),
    .Y(normalised_prod[20])
  );
  sky130_fd_sc_hd__a21oi_1 _375_ (
    .A1(_020_),
    .A2(normalised_prod[21]),
    .B1(normalised_exp[0]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21oi_1 _376_ (
    .A1(normalised_exp[0]),
    .A2(_041_),
    .B1(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__mux2i_1 _377_ (
    .A0(_033_),
    .A1(_049_),
    .S(_024_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _378_ (
    .A(underflow_amt[2]),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(_008_),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o22ai_1 _380_ (
    .A1(underflow),
    .A2(_047_),
    .B1(_052_),
    .B2(_038_),
    .Y(underflow_man[20])
  );
  sky130_fd_sc_hd__mux2_1 _381_ (
    .A0(prod[18]),
    .A1(prod[19]),
    .S(prod[23]),
    .X(normalised_prod[19])
  );
  sky130_fd_sc_hd__clkinv_1 _382_ (
    .A(normalised_prod[19]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a21oi_1 _383_ (
    .A1(_024_),
    .A2(_027_),
    .B1(_010_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(underflow_amt[6]),
    .B(_047_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor3_1 _385_ (
    .A(_303_),
    .B(underflow_amt[6]),
    .C(_040_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a21oi_1 _386_ (
    .A1(_303_),
    .A2(_055_),
    .B1(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(underflow_amt[1]),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21oi_1 _388_ (
    .A1(underflow_amt[1]),
    .A2(_043_),
    .B1(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a21oi_1 _389_ (
    .A1(_010_),
    .A2(_059_),
    .B1(_054_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _390_ (
    .A(_008_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o22ai_1 _391_ (
    .A1(underflow),
    .A2(_053_),
    .B1(_061_),
    .B2(_038_),
    .Y(underflow_man[19])
  );
  sky130_fd_sc_hd__mux2i_1 _392_ (
    .A0(prod[17]),
    .A1(prod[18]),
    .S(prod[23]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _393_ (
    .A(_062_),
    .Y(normalised_prod[18])
  );
  sky130_fd_sc_hd__nand2_1 _394_ (
    .A(_020_),
    .B(normalised_prod[19]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2_1 _395_ (
    .A(normalised_exp[0]),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a21oi_1 _396_ (
    .A1(normalised_exp[0]),
    .A2(_055_),
    .B1(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _397_ (
    .A(underflow_amt[1]),
    .B(_049_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _398_ (
    .A1(underflow_amt[1]),
    .A2(_065_),
    .B1(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _399_ (
    .A(_010_),
    .B(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o21ai_0 _400_ (
    .A1(_010_),
    .A2(_034_),
    .B1(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _401_ (
    .A(_008_),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o22ai_1 _402_ (
    .A1(underflow),
    .A2(_062_),
    .B1(_070_),
    .B2(_038_),
    .Y(underflow_man[18])
  );
  sky130_fd_sc_hd__mux2_1 _403_ (
    .A0(prod[16]),
    .A1(prod[17]),
    .S(prod[23]),
    .X(normalised_prod[17])
  );
  sky130_fd_sc_hd__clkinv_1 _404_ (
    .A(normalised_prod[17]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _405_ (
    .A(underflow_amt[6]),
    .B(_062_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(_303_),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__o21ai_0 _407_ (
    .A1(_303_),
    .A2(_063_),
    .B1(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(_024_),
    .B(_057_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _409_ (
    .A1(_024_),
    .A2(_074_),
    .B1(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__mux2i_1 _410_ (
    .A0(_044_),
    .A1(_076_),
    .S(_010_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _411_ (
    .A(_008_),
    .B(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o22ai_1 _412_ (
    .A1(underflow),
    .A2(_071_),
    .B1(_078_),
    .B2(_038_),
    .Y(underflow_man[17])
  );
  sky130_fd_sc_hd__mux2_1 _413_ (
    .A0(prod[15]),
    .A1(prod[16]),
    .S(prod[23]),
    .X(normalised_prod[16])
  );
  sky130_fd_sc_hd__clkinv_1 _414_ (
    .A(normalised_prod[16]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _415_ (
    .A(normalised_exp[0]),
    .B(_072_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o31ai_1 _416_ (
    .A1(normalised_exp[0]),
    .A2(underflow_amt[6]),
    .A3(_071_),
    .B1(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _417_ (
    .A(_024_),
    .B(_065_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a21oi_1 _418_ (
    .A1(_024_),
    .A2(_081_),
    .B1(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__mux2i_1 _419_ (
    .A0(_050_),
    .A1(_083_),
    .S(_010_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _420_ (
    .A(_008_),
    .B(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o22ai_1 _421_ (
    .A1(underflow),
    .A2(_079_),
    .B1(_085_),
    .B2(_038_),
    .Y(underflow_man[16])
  );
  sky130_fd_sc_hd__mux2i_1 _422_ (
    .A0(prod[14]),
    .A1(prod[15]),
    .S(prod[23]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__clkinv_1 _423_ (
    .A(_086_),
    .Y(normalised_prod[15])
  );
  sky130_fd_sc_hd__nand2_1 _424_ (
    .A(_020_),
    .B(normalised_prod[16]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand3_1 _425_ (
    .A(normalised_exp[0]),
    .B(_020_),
    .C(normalised_prod[17]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21ai_0 _426_ (
    .A1(normalised_exp[0]),
    .A2(_087_),
    .B1(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__mux2i_1 _427_ (
    .A0(_074_),
    .A1(_089_),
    .S(_024_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _428_ (
    .A(_010_),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _429_ (
    .A1(underflow_amt[2]),
    .A2(_059_),
    .B1(underflow_amt[4]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _431_ (
    .A(_008_),
    .B(underflow_amt[4]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _432_ (
    .A(underflow_amt[3]),
    .B(_018_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(_093_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o21ai_0 _434_ (
    .A1(_008_),
    .A2(_028_),
    .B1(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o22ai_1 _435_ (
    .A1(underflow),
    .A2(_086_),
    .B1(_097_),
    .B2(_037_),
    .Y(underflow_man[15])
  );
  sky130_fd_sc_hd__mux2_1 _436_ (
    .A0(prod[13]),
    .A1(prod[14]),
    .S(prod[23]),
    .X(normalised_prod[14])
  );
  sky130_fd_sc_hd__clkinv_1 _437_ (
    .A(normalised_prod[14]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _438_ (
    .A(underflow_amt[6]),
    .B(_086_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(_303_),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o21ai_0 _440_ (
    .A1(_303_),
    .A2(_087_),
    .B1(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__mux2i_1 _441_ (
    .A0(_081_),
    .A1(_101_),
    .S(_024_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(_010_),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o211ai_1 _443_ (
    .A1(_010_),
    .A2(_067_),
    .B1(_103_),
    .C1(_018_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _444_ (
    .A(_095_),
    .B(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21ai_0 _445_ (
    .A1(_008_),
    .A2(_035_),
    .B1(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o22ai_1 _446_ (
    .A1(underflow),
    .A2(_098_),
    .B1(_106_),
    .B2(_037_),
    .Y(underflow_man[14])
  );
  sky130_fd_sc_hd__mux2i_1 _447_ (
    .A0(prod[12]),
    .A1(prod[13]),
    .S(prod[23]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__clkinv_1 _448_ (
    .A(_107_),
    .Y(normalised_prod[13])
  );
  sky130_fd_sc_hd__nand2_1 _449_ (
    .A(normalised_exp[0]),
    .B(_099_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(_020_),
    .B(normalised_prod[14]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__o21ai_0 _451_ (
    .A1(normalised_exp[0]),
    .A2(_109_),
    .B1(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__mux2i_1 _452_ (
    .A0(_089_),
    .A1(_110_),
    .S(_024_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__mux2i_1 _453_ (
    .A0(_076_),
    .A1(_111_),
    .S(_010_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _454_ (
    .A(_018_),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o21ai_0 _455_ (
    .A1(underflow_amt[3]),
    .A2(_112_),
    .B1(_018_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _456_ (
    .A(_008_),
    .B(_045_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o32ai_1 _457_ (
    .A1(_037_),
    .A2(_114_),
    .A3(_115_),
    .B1(_107_),
    .B2(underflow),
    .Y(underflow_man[13])
  );
  sky130_fd_sc_hd__mux2i_1 _458_ (
    .A0(prod[11]),
    .A1(prod[12]),
    .S(prod[23]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__clkinv_1 _459_ (
    .A(_116_),
    .Y(normalised_prod[12])
  );
  sky130_fd_sc_hd__a21oi_1 _460_ (
    .A1(_020_),
    .A2(normalised_prod[13]),
    .B1(normalised_exp[0]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a21oi_1 _461_ (
    .A1(normalised_exp[0]),
    .A2(_109_),
    .B1(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__mux2i_1 _462_ (
    .A0(_101_),
    .A1(_118_),
    .S(_024_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _463_ (
    .A(_010_),
    .B(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21oi_1 _464_ (
    .A1(underflow_amt[2]),
    .A2(_083_),
    .B1(underflow_amt[4]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _465_ (
    .A(_120_),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21oi_1 _466_ (
    .A1(_095_),
    .A2(_122_),
    .B1(_037_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o21ai_0 _467_ (
    .A1(_008_),
    .A2(_051_),
    .B1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _468_ (
    .A1(underflow),
    .A2(_116_),
    .B1(_124_),
    .Y(underflow_man[12])
  );
  sky130_fd_sc_hd__mux2_1 _469_ (
    .A0(prod[10]),
    .A1(prod[11]),
    .S(prod[23]),
    .X(normalised_prod[11])
  );
  sky130_fd_sc_hd__clkinv_1 _470_ (
    .A(normalised_prod[11]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _471_ (
    .A(_008_),
    .B(_060_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_1 _472_ (
    .A(underflow_amt[6]),
    .B(_116_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _473_ (
    .A(_303_),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o31ai_1 _474_ (
    .A1(_303_),
    .A2(underflow_amt[6]),
    .A3(_107_),
    .B1(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__mux2i_1 _475_ (
    .A0(_110_),
    .A1(_129_),
    .S(_024_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__mux2i_1 _476_ (
    .A0(_090_),
    .A1(_130_),
    .S(_010_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _477_ (
    .A(underflow_amt[3]),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o32ai_1 _478_ (
    .A1(_038_),
    .A2(_126_),
    .A3(_132_),
    .B1(_125_),
    .B2(underflow),
    .Y(underflow_man[11])
  );
  sky130_fd_sc_hd__mux2i_1 _479_ (
    .A0(prod[9]),
    .A1(prod[10]),
    .S(prod[23]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__clkinv_1 _480_ (
    .A(_133_),
    .Y(normalised_prod[10])
  );
  sky130_fd_sc_hd__nor2_1 _481_ (
    .A(_008_),
    .B(_069_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _482_ (
    .A(_020_),
    .B(normalised_prod[11]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _483_ (
    .A(normalised_exp[0]),
    .B(_127_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o21ai_0 _484_ (
    .A1(normalised_exp[0]),
    .A2(_135_),
    .B1(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__mux2i_1 _485_ (
    .A0(_118_),
    .A1(_137_),
    .S(_024_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__mux2i_1 _486_ (
    .A0(_102_),
    .A1(_138_),
    .S(_010_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor2_1 _487_ (
    .A(underflow_amt[3]),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o32ai_1 _488_ (
    .A1(_038_),
    .A2(_134_),
    .A3(_140_),
    .B1(_133_),
    .B2(underflow),
    .Y(underflow_man[10])
  );
  sky130_fd_sc_hd__mux2i_1 _489_ (
    .A0(prod[8]),
    .A1(prod[9]),
    .S(prod[23]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__clkinv_1 _490_ (
    .A(_141_),
    .Y(normalised_prod[9])
  );
  sky130_fd_sc_hd__nor2_1 _491_ (
    .A(underflow_amt[6]),
    .B(_133_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _492_ (
    .A(normalised_exp[0]),
    .B(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21oi_1 _493_ (
    .A1(normalised_exp[0]),
    .A2(_135_),
    .B1(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__mux2i_1 _494_ (
    .A0(_129_),
    .A1(_144_),
    .S(_024_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__mux2i_1 _495_ (
    .A0(_111_),
    .A1(_145_),
    .S(_010_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _496_ (
    .A(underflow_amt[3]),
    .B(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _497_ (
    .A(_008_),
    .B(_077_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o32ai_1 _498_ (
    .A1(_038_),
    .A2(_147_),
    .A3(_148_),
    .B1(_141_),
    .B2(underflow),
    .Y(underflow_man[9])
  );
  sky130_fd_sc_hd__mux2i_1 _499_ (
    .A0(prod[7]),
    .A1(prod[8]),
    .S(prod[23]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__clkinv_1 _500_ (
    .A(_149_),
    .Y(normalised_prod[8])
  );
  sky130_fd_sc_hd__nor2_1 _501_ (
    .A(_008_),
    .B(_084_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _502_ (
    .A1(underflow_amt[6]),
    .A2(_141_),
    .B1(_303_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21ai_0 _503_ (
    .A1(_303_),
    .A2(_142_),
    .B1(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _504_ (
    .A(underflow_amt[1]),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _505_ (
    .A1(underflow_amt[1]),
    .A2(_137_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__mux2i_1 _506_ (
    .A0(_119_),
    .A1(_154_),
    .S(_010_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _507_ (
    .A(underflow_amt[3]),
    .B(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o32ai_1 _508_ (
    .A1(_038_),
    .A2(_150_),
    .A3(_156_),
    .B1(_149_),
    .B2(underflow),
    .Y(underflow_man[8])
  );
  sky130_fd_sc_hd__mux2i_1 _509_ (
    .A0(prod[6]),
    .A1(prod[7]),
    .S(prod[23]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__clkinv_1 _510_ (
    .A(_157_),
    .Y(normalised_prod[7])
  );
  sky130_fd_sc_hd__nand2_1 _511_ (
    .A(_008_),
    .B(_018_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand3_1 _512_ (
    .A(_029_),
    .B(_093_),
    .C(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor3_1 _513_ (
    .A(normalised_exp[0]),
    .B(underflow_amt[6]),
    .C(_149_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _514_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[9]),
    .B1(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _515_ (
    .A(underflow_amt[1]),
    .B(_144_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o21ai_0 _516_ (
    .A1(underflow_amt[1]),
    .A2(_161_),
    .B1(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _517_ (
    .A1(_010_),
    .A2(_163_),
    .B1(_158_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o21ai_0 _518_ (
    .A1(_010_),
    .A2(_130_),
    .B1(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _519_ (
    .A(_159_),
    .B(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o22ai_1 _520_ (
    .A1(underflow),
    .A2(_157_),
    .B1(_166_),
    .B2(_037_),
    .Y(underflow_man[7])
  );
  sky130_fd_sc_hd__mux2_1 _521_ (
    .A0(prod[5]),
    .A1(prod[6]),
    .S(prod[23]),
    .X(normalised_prod[6])
  );
  sky130_fd_sc_hd__clkinv_1 _522_ (
    .A(normalised_prod[6]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand3_1 _523_ (
    .A(_036_),
    .B(_104_),
    .C(_158_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _524_ (
    .A(normalised_exp[0]),
    .B(normalised_prod[8]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o31ai_1 _525_ (
    .A1(normalised_exp[0]),
    .A2(underflow_amt[6]),
    .A3(_157_),
    .B1(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _526_ (
    .A(underflow_amt[1]),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a21oi_1 _527_ (
    .A1(underflow_amt[1]),
    .A2(_152_),
    .B1(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _528_ (
    .A1(_010_),
    .A2(_172_),
    .B1(_158_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o21ai_0 _529_ (
    .A1(_010_),
    .A2(_138_),
    .B1(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _530_ (
    .A(_168_),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__o22ai_1 _531_ (
    .A1(underflow),
    .A2(_167_),
    .B1(_175_),
    .B2(_037_),
    .Y(underflow_man[6])
  );
  sky130_fd_sc_hd__mux2i_1 _532_ (
    .A0(prod[4]),
    .A1(prod[5]),
    .S(prod[23]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__clkinv_1 _533_ (
    .A(_176_),
    .Y(normalised_prod[5])
  );
  sky130_fd_sc_hd__nand3_1 _534_ (
    .A(_046_),
    .B(_113_),
    .C(_158_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor2_1 _535_ (
    .A(_303_),
    .B(_157_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a21oi_1 _536_ (
    .A1(_303_),
    .A2(normalised_prod[6]),
    .B1(_178_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2_1 _537_ (
    .A(underflow_amt[6]),
    .B(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _538_ (
    .A(underflow_amt[1]),
    .B(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a21oi_1 _539_ (
    .A1(underflow_amt[1]),
    .A2(_161_),
    .B1(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a21oi_1 _540_ (
    .A1(_010_),
    .A2(_182_),
    .B1(_158_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__o21ai_0 _541_ (
    .A1(_010_),
    .A2(_145_),
    .B1(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand2_1 _542_ (
    .A(_177_),
    .B(_184_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__o22ai_1 _543_ (
    .A1(underflow),
    .A2(_176_),
    .B1(_185_),
    .B2(_037_),
    .Y(underflow_man[5])
  );
  sky130_fd_sc_hd__mux2_1 _544_ (
    .A0(prod[3]),
    .A1(prod[4]),
    .S(prod[23]),
    .X(normalised_prod[4])
  );
  sky130_fd_sc_hd__clkinv_1 _545_ (
    .A(normalised_prod[4]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nand3_1 _546_ (
    .A(_052_),
    .B(_122_),
    .C(_158_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nor2_1 _547_ (
    .A(normalised_exp[0]),
    .B(_176_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21oi_1 _548_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[6]),
    .B1(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _549_ (
    .A(underflow_amt[6]),
    .B(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _550_ (
    .A(underflow_amt[1]),
    .B(_190_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor2_1 _551_ (
    .A(_024_),
    .B(_170_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nor2_1 _552_ (
    .A(_191_),
    .B(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a21oi_1 _553_ (
    .A1(_010_),
    .A2(_193_),
    .B1(_158_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o21ai_0 _554_ (
    .A1(_010_),
    .A2(_154_),
    .B1(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand2_1 _555_ (
    .A(_187_),
    .B(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__o22ai_1 _556_ (
    .A1(underflow),
    .A2(_186_),
    .B1(_196_),
    .B2(_037_),
    .Y(underflow_man[4])
  );
  sky130_fd_sc_hd__mux2i_1 _557_ (
    .A0(prod[2]),
    .A1(prod[3]),
    .S(prod[23]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__clkinv_1 _558_ (
    .A(_197_),
    .Y(normalised_prod[3])
  );
  sky130_fd_sc_hd__nor2_1 _559_ (
    .A(_018_),
    .B(_061_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor2_1 _560_ (
    .A(_010_),
    .B(_163_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nand2_1 _561_ (
    .A(_303_),
    .B(normalised_prod[4]),
    .Y(_200_)
  );
  sky130_fd_sc_hd__o21ai_0 _562_ (
    .A1(_303_),
    .A2(_176_),
    .B1(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _563_ (
    .A(_020_),
    .B(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__o21ai_0 _564_ (
    .A1(underflow_amt[1]),
    .A2(_202_),
    .B1(_010_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__a21oi_1 _565_ (
    .A1(underflow_amt[1]),
    .A2(_180_),
    .B1(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor3_1 _566_ (
    .A(_158_),
    .B(_199_),
    .C(_204_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__a211oi_1 _567_ (
    .A1(_094_),
    .A2(_131_),
    .B1(_198_),
    .C1(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o22ai_1 _568_ (
    .A1(underflow),
    .A2(_197_),
    .B1(_206_),
    .B2(_037_),
    .Y(underflow_man[3])
  );
  sky130_fd_sc_hd__mux2i_1 _569_ (
    .A0(prod[1]),
    .A1(prod[2]),
    .S(prod[23]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__clkinv_1 _570_ (
    .A(_207_),
    .Y(normalised_prod[2])
  );
  sky130_fd_sc_hd__nor2_1 _571_ (
    .A(_018_),
    .B(_070_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nor2_1 _572_ (
    .A(_010_),
    .B(_172_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor2_1 _573_ (
    .A(normalised_exp[0]),
    .B(_197_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__a21oi_1 _574_ (
    .A1(normalised_exp[0]),
    .A2(normalised_prod[4]),
    .B1(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o31ai_1 _575_ (
    .A1(underflow_amt[6]),
    .A2(underflow_amt[1]),
    .A3(_211_),
    .B1(_010_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__a21oi_1 _576_ (
    .A1(underflow_amt[1]),
    .A2(_190_),
    .B1(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor3_1 _577_ (
    .A(_158_),
    .B(_209_),
    .C(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__a211oi_1 _578_ (
    .A1(_094_),
    .A2(_139_),
    .B1(_208_),
    .C1(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__o22ai_1 _579_ (
    .A1(underflow),
    .A2(_207_),
    .B1(_215_),
    .B2(_037_),
    .Y(underflow_man[2])
  );
  sky130_fd_sc_hd__mux2i_1 _580_ (
    .A0(prod[0]),
    .A1(prod[1]),
    .S(prod[23]),
    .Y(_216_)
  );
  sky130_fd_sc_hd__clkinv_1 _581_ (
    .A(_216_),
    .Y(normalised_prod[1])
  );
  sky130_fd_sc_hd__nor2_1 _582_ (
    .A(_018_),
    .B(_078_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nor2_1 _583_ (
    .A(_010_),
    .B(_182_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _584_ (
    .A(_303_),
    .B(_207_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__a21oi_1 _585_ (
    .A1(normalised_exp[0]),
    .A2(_197_),
    .B1(underflow_amt[6]),
    .Y(_220_)
  );
  sky130_fd_sc_hd__o21ai_0 _586_ (
    .A1(_024_),
    .A2(_202_),
    .B1(_010_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__a31oi_1 _587_ (
    .A1(_024_),
    .A2(_219_),
    .A3(_220_),
    .B1(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nor3_1 _588_ (
    .A(_158_),
    .B(_218_),
    .C(_222_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__a211oi_1 _589_ (
    .A1(_094_),
    .A2(_146_),
    .B1(_217_),
    .C1(_223_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__o22ai_1 _590_ (
    .A1(underflow),
    .A2(_216_),
    .B1(_224_),
    .B2(_037_),
    .Y(underflow_man[1])
  );
  sky130_fd_sc_hd__nand2_1 _591_ (
    .A(prod[23]),
    .B(prod[0]),
    .Y(_225_)
  );
  sky130_fd_sc_hd__clkinv_1 _592_ (
    .A(_225_),
    .Y(normalised_prod[0])
  );
  sky130_fd_sc_hd__nor2_1 _593_ (
    .A(_018_),
    .B(_085_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nor2_1 _594_ (
    .A(_010_),
    .B(_193_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand2_1 _595_ (
    .A(_303_),
    .B(_216_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__or3_1 _596_ (
    .A(underflow_amt[6]),
    .B(_024_),
    .C(_211_),
    .X(_229_)
  );
  sky130_fd_sc_hd__o2111ai_1 _597_ (
    .A1(_303_),
    .A2(normalised_prod[2]),
    .B1(_228_),
    .C1(_020_),
    .D1(_024_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__a311oi_1 _598_ (
    .A1(_010_),
    .A2(_229_),
    .A3(_230_),
    .B1(_158_),
    .C1(_227_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__a211oi_1 _599_ (
    .A1(_094_),
    .A2(_155_),
    .B1(_226_),
    .C1(_231_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__o22ai_1 _600_ (
    .A1(underflow),
    .A2(_225_),
    .B1(_232_),
    .B2(_037_),
    .Y(underflow_man[0])
  );
  sky130_fd_sc_hd__nor3_1 _601_ (
    .A(_303_),
    .B(_022_),
    .C(_023_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand2_1 _602_ (
    .A(underflow_amt[2]),
    .B(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__and3_1 _603_ (
    .A(underflow_amt[3]),
    .B(underflow_amt[2]),
    .C(_233_),
    .X(_235_)
  );
  sky130_fd_sc_hd__nand3_1 _604_ (
    .A(underflow_amt[3]),
    .B(underflow_amt[2]),
    .C(_233_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand3_1 _605_ (
    .A(normalised_exp[0]),
    .B(_010_),
    .C(_024_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__o211ai_1 _606_ (
    .A1(underflow_amt[5]),
    .A2(underflow_amt[6]),
    .B1(_235_),
    .C1(underflow_amt[4]),
    .Y(_238_)
  );
  sky130_fd_sc_hd__a41oi_1 _607_ (
    .A1(underflow_amt[3]),
    .A2(underflow_amt[2]),
    .A3(underflow_amt[4]),
    .A4(_233_),
    .B1(underflow_amt[5]),
    .Y(_239_)
  );
  sky130_fd_sc_hd__o21ai_0 _608_ (
    .A1(_018_),
    .A2(_236_),
    .B1(_016_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__nand2_1 _609_ (
    .A(_238_),
    .B(_240_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nand2_1 _610_ (
    .A(underflow_amt[4]),
    .B(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor3_1 _611_ (
    .A(underflow_amt[3]),
    .B(_237_),
    .C(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand4_1 _612_ (
    .A(tentative_exp[1]),
    .B(_303_),
    .C(_008_),
    .D(_010_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nor3_1 _613_ (
    .A(_303_),
    .B(underflow_amt[2]),
    .C(_024_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__nand2_1 _614_ (
    .A(_008_),
    .B(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nor4b_1 _615_ (
    .A(tentative_exp[1]),
    .B(normalised_exp[0]),
    .C(underflow_amt[3]),
    .D_N(normalised_exp[2]),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a31o_1 _616_ (
    .A1(underflow_amt[3]),
    .A2(underflow_amt[2]),
    .A3(_233_),
    .B1(underflow_amt[4]),
    .X(_248_)
  );
  sky130_fd_sc_hd__nand3_1 _617_ (
    .A(normalised_exp[0]),
    .B(underflow_amt[2]),
    .C(_024_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__nand4_1 _618_ (
    .A(normalised_exp[0]),
    .B(_008_),
    .C(underflow_amt[2]),
    .D(_024_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__or4_1 _619_ (
    .A(underflow_amt[3]),
    .B(underflow_amt[5]),
    .C(_018_),
    .D(_249_),
    .X(_251_)
  );
  sky130_fd_sc_hd__and4_1 _620_ (
    .A(tentative_exp[1]),
    .B(_303_),
    .C(_008_),
    .D(underflow_amt[2]),
    .X(_252_)
  );
  sky130_fd_sc_hd__a31oi_1 _621_ (
    .A1(_239_),
    .A2(_248_),
    .A3(_252_),
    .B1(_025_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__o21ai_0 _622_ (
    .A1(normalised_prod[22]),
    .A2(_253_),
    .B1(_251_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__a32oi_1 _623_ (
    .A1(_239_),
    .A2(_247_),
    .A3(_248_),
    .B1(_254_),
    .B2(_040_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o22a_1 _624_ (
    .A1(_242_),
    .A2(_246_),
    .B1(_255_),
    .B2(normalised_prod[20]),
    .X(_256_)
  );
  sky130_fd_sc_hd__o22ai_1 _625_ (
    .A1(_242_),
    .A2(_244_),
    .B1(_256_),
    .B2(normalised_prod[19]),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a21oi_1 _626_ (
    .A1(_062_),
    .A2(_257_),
    .B1(_243_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nand3_1 _627_ (
    .A(normalised_exp[4]),
    .B(_014_),
    .C(_241_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__o21ai_0 _628_ (
    .A1(normalised_prod[17]),
    .A2(_258_),
    .B1(_259_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__a22o_1 _629_ (
    .A1(_030_),
    .A2(_235_),
    .B1(_260_),
    .B2(_079_),
    .X(_261_)
  );
  sky130_fd_sc_hd__nand2_1 _630_ (
    .A(_030_),
    .B(_236_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__a21oi_1 _631_ (
    .A1(_008_),
    .A2(_234_),
    .B1(_262_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__and4_1 _632_ (
    .A(tentative_exp[1]),
    .B(_303_),
    .C(underflow_amt[2]),
    .D(_263_),
    .X(_264_)
  );
  sky130_fd_sc_hd__a21oi_1 _633_ (
    .A1(_086_),
    .A2(_261_),
    .B1(_264_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__and2_0 _634_ (
    .A(_238_),
    .B(_262_),
    .X(_266_)
  );
  sky130_fd_sc_hd__nand2_1 _635_ (
    .A(_238_),
    .B(_262_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__nor2_1 _636_ (
    .A(_008_),
    .B(_266_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__o32ai_1 _637_ (
    .A1(_008_),
    .A2(_249_),
    .A3(_266_),
    .B1(_265_),
    .B2(normalised_prod[14]),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand3_1 _638_ (
    .A(_005_),
    .B(normalised_exp[2]),
    .C(_263_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand3_1 _639_ (
    .A(normalised_exp[3]),
    .B(_006_),
    .C(_267_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nand3_1 _640_ (
    .A(_094_),
    .B(_241_),
    .C(_245_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__nor3_1 _641_ (
    .A(_008_),
    .B(_237_),
    .C(_266_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__nand4_1 _642_ (
    .A(tentative_exp[1]),
    .B(_303_),
    .C(_010_),
    .D(_268_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__nor2_1 _643_ (
    .A(_031_),
    .B(_244_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__nor3_1 _644_ (
    .A(underflow_amt[3]),
    .B(_031_),
    .C(_237_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nor2_1 _645_ (
    .A(_275_),
    .B(_276_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__o21ai_0 _646_ (
    .A1(normalised_exp[6]),
    .A2(_019_),
    .B1(_277_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__a31oi_1 _647_ (
    .A1(_008_),
    .A2(_030_),
    .A3(_245_),
    .B1(_278_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nand2_1 _648_ (
    .A(_247_),
    .B(_267_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__nand2_1 _649_ (
    .A(_279_),
    .B(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nor2_1 _650_ (
    .A(_031_),
    .B(_250_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__a21oi_1 _651_ (
    .A1(_252_),
    .A2(_267_),
    .B1(_282_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__nand2_1 _652_ (
    .A(_271_),
    .B(_283_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nor4_1 _653_ (
    .A(underflow_amt[3]),
    .B(underflow_amt[5]),
    .C(underflow_amt[4]),
    .D(_234_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__nor4_1 _654_ (
    .A(_273_),
    .B(_281_),
    .C(_284_),
    .D(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__and3_1 _655_ (
    .A(_272_),
    .B(_274_),
    .C(_286_),
    .X(_287_)
  );
  sky130_fd_sc_hd__nand2_1 _656_ (
    .A(_270_),
    .B(_287_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__a21oi_1 _657_ (
    .A1(_107_),
    .A2(_269_),
    .B1(_288_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__a21oi_1 _658_ (
    .A1(normalised_prod[11]),
    .A2(_274_),
    .B1(normalised_prod[10]),
    .Y(_290_)
  );
  sky130_fd_sc_hd__o21ai_0 _659_ (
    .A1(_031_),
    .A2(_250_),
    .B1(normalised_prod[6]),
    .Y(_291_)
  );
  sky130_fd_sc_hd__o21ai_0 _660_ (
    .A1(_207_),
    .A2(_276_),
    .B1(_216_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__o21ai_0 _661_ (
    .A1(normalised_exp[6]),
    .A2(_019_),
    .B1(_292_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__nand2_1 _662_ (
    .A(_225_),
    .B(_293_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__a21oi_1 _663_ (
    .A1(normalised_prod[4]),
    .A2(_279_),
    .B1(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__o21ai_0 _664_ (
    .A1(_197_),
    .A2(_278_),
    .B1(_295_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__a21oi_1 _665_ (
    .A1(normalised_prod[9]),
    .A2(_271_),
    .B1(normalised_prod[8]),
    .Y(_297_)
  );
  sky130_fd_sc_hd__o21ai_0 _666_ (
    .A1(_285_),
    .A2(_297_),
    .B1(_157_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__nand2_1 _667_ (
    .A(_283_),
    .B(_298_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__a31oi_1 _668_ (
    .A1(_176_),
    .A2(_291_),
    .A3(_299_),
    .B1(_281_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _669_ (
    .A(_286_),
    .SLEEP(_290_),
    .X(_301_)
  );
  sky130_fd_sc_hd__a211o_1 _670_ (
    .A1(normalised_prod[12]),
    .A2(_287_),
    .B1(_296_),
    .C1(_301_),
    .X(_302_)
  );
  sky130_fd_sc_hd__o31a_1 _671_ (
    .A1(_289_),
    .A2(_300_),
    .A3(_302_),
    .B1(underflow),
    .X(tentative_S)
  );
  sky130_fd_sc_hd__nor2_1 _672_ (
    .A(underflow),
    .B(_026_),
    .Y(underflow_man[24])
  );
  assign underflow_prod[24] = 1'h0;
  assign underflow_amt[0] = normalised_exp[0];
endmodule
