/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* top =  1  *)
(* src = "src/fdiv_datapath_blocks.sv:60.1-69.10" *)
module div_quot_correct(q_trial, q_adjust, sticky_final, prod);
  (* src = "src/fdiv_datapath_blocks.sv:61.25-61.32" *)
  input [14:0] q_trial;
  wire [14:0] q_trial;
  (* src = "src/fdiv_datapath_blocks.sv:62.31-62.39" *)
  input [3:0] q_adjust;
  wire [3:0] q_adjust;
  (* src = "src/fdiv_datapath_blocks.sv:63.32-63.44" *)
  input sticky_final;
  wire sticky_final;
  (* src = "src/fdiv_datapath_blocks.sv:64.25-64.29" *)
  output [24:0] prod;
  wire [24:0] prod;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* src = "src/fdiv_datapath_blocks.sv:66.18-66.25" *)
  wire [14:0] q_final;
  sky130_fd_sc_hd__nand2_1 _19_ (
    .A(q_adjust[0]),
    .B(q_trial[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _20_ (
    .A(q_adjust[0]),
    .B(q_trial[0]),
    .X(prod[10])
  );
  sky130_fd_sc_hd__nand2_1 _21_ (
    .A(q_adjust[1]),
    .B(q_trial[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(q_adjust[1]),
    .B(q_trial[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _23_ (
    .A(_01_),
    .SLEEP(_02_),
    .X(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _24_ (
    .A1(_00_),
    .A2(_02_),
    .B1(_01_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _25_ (
    .A(q_adjust[2]),
    .B(q_trial[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__maj3_1 _26_ (
    .A(q_adjust[2]),
    .B(q_trial[2]),
    .C(_04_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _27_ (
    .A(q_adjust[3]),
    .B(q_trial[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__maj3_1 _28_ (
    .A(q_adjust[3]),
    .B(q_trial[3]),
    .C(_06_),
    .X(_08_)
  );
  sky130_fd_sc_hd__and3_1 _29_ (
    .A(q_trial[4]),
    .B(q_trial[5]),
    .C(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__nand4_1 _30_ (
    .A(q_trial[4]),
    .B(q_trial[5]),
    .C(q_trial[6]),
    .D(_08_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _31_ (
    .A(q_trial[7]),
    .SLEEP(_10_),
    .X(_11_)
  );
  sky130_fd_sc_hd__nand2_1 _32_ (
    .A(q_trial[8]),
    .B(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__and4_1 _33_ (
    .A(q_trial[8]),
    .B(q_trial[9]),
    .C(q_trial[10]),
    .D(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__nand3_1 _34_ (
    .A(q_trial[11]),
    .B(q_trial[12]),
    .C(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand4_1 _35_ (
    .A(q_trial[11]),
    .B(q_trial[12]),
    .C(q_trial[13]),
    .D(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(q_trial[14]),
    .B(_15_),
    .Y(prod[24])
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(q_trial[13]),
    .B(_14_),
    .Y(prod[23])
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(q_trial[11]),
    .A2(_13_),
    .B1(q_trial[12]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _39_ (
    .A(_14_),
    .SLEEP(_16_),
    .X(prod[22])
  );
  sky130_fd_sc_hd__xor2_1 _40_ (
    .A(q_trial[11]),
    .B(_13_),
    .X(prod[21])
  );
  sky130_fd_sc_hd__a31oi_1 _41_ (
    .A1(q_trial[8]),
    .A2(q_trial[9]),
    .A3(_11_),
    .B1(q_trial[10]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(_13_),
    .B(_17_),
    .Y(prod[20])
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(q_trial[9]),
    .B(_12_),
    .Y(prod[19])
  );
  sky130_fd_sc_hd__xor2_1 _44_ (
    .A(q_trial[8]),
    .B(_11_),
    .X(prod[18])
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(q_trial[7]),
    .B(_10_),
    .Y(prod[17])
  );
  sky130_fd_sc_hd__xor2_1 _46_ (
    .A(q_trial[6]),
    .B(_09_),
    .X(prod[16])
  );
  sky130_fd_sc_hd__a21oi_1 _47_ (
    .A1(q_trial[4]),
    .A2(_08_),
    .B1(q_trial[5]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _48_ (
    .A(_09_),
    .B(_18_),
    .Y(prod[15])
  );
  sky130_fd_sc_hd__xor2_1 _49_ (
    .A(q_trial[4]),
    .B(_08_),
    .X(prod[14])
  );
  sky130_fd_sc_hd__xnor2_1 _50_ (
    .A(_06_),
    .B(_07_),
    .Y(prod[13])
  );
  sky130_fd_sc_hd__xnor2_1 _51_ (
    .A(_04_),
    .B(_05_),
    .Y(prod[12])
  );
  sky130_fd_sc_hd__xnor2_1 _52_ (
    .A(_00_),
    .B(_03_),
    .Y(prod[11])
  );
  assign q_final = prod[24:10];
  assign prod[9:0] = { 9'h000, sticky_final };
endmodule
